/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/msgpackMacroTest.o /home/cyril/Projects/provider/nimcache/msgpackMacroTest.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <math.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, write_92003)(NIM_CHAR c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, store8_92006)(NU8 val);
N_NIMCALL(void, write8_92009)(NU8 val, NIM_BOOL fix, NI bytes, NU8 prefix);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, HEX5E_117031)(NI x_117035, NI y_117037);
static N_INLINE(void, HEX2AHEX3D_117206)(NI* x, NI y);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, msgpackMacroTestInit000)(void);
NIM_EXTERNC N_NOINLINE(void, msgpackMacroTestDatInit000)(void);
extern TFrame* frameptr_19436;
NI i_117011;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(void, write_92003)(NIM_CHAR c) {
	nimfr("write", "msgpackMacroTest.nim")
	popFrame();
}

N_NIMCALL(void, store8_92006)(NU8 val) {
	nimfr("store8", "msgpackMacroTest.nim")
	popFrame();
}

N_NIMCALL(void, write8_92009)(NU8 val, NIM_BOOL fix, NI bytes, NU8 prefix) {
	nimfr("write8", "msgpackMacroTest.nim")
	nimln(5, "msgpackMacroTest.nim");
	{
		if (!((NU8)(val) < (NU8)(((NU8) ((NI)((NU64)(((NI) 1)) << (NU64)(bytes))))))) goto LA3;
		nimln(6, "msgpackMacroTest.nim");
		{
			if (!!(fix)) goto LA7;
			nimln(7, "msgpackMacroTest.nim");
			write_92003(((NIM_CHAR) (((NI) (prefix)))));
		}
		LA7: ;
		nimln(8, "msgpackMacroTest.nim");
		store8_92006(val);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, HEX2AHEX3D_117206)(NI* x, NI y) {
	NI TMP287;
	nimfr("*=", "system.nim")
	nimln(3261, "system.nim");
	TMP287 = mulInt((*x), y);
	(*x) = (NI)(TMP287);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_mathDatInit000();
	stdlib_macrosDatInit000();
	msgpackMacroTestDatInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_mathInit000();
	stdlib_macrosInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	msgpackMacroTestInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, msgpackMacroTestInit000)(void) {
	NI LOC7;
	NI TMP288;
	NI TMP289;
	NimStringDesc* LOC8;
	nimfr("msgpackMacroTest", "msgpackMacroTest.nim")
	{
		NI res_117024;
		nimln(1862, "system.nim");
		res_117024 = ((NI) 4);
		{
			nimln(1863, "system.nim");
			while (1) {
				NF LOC4;
				NF LOC5;
				NimStringDesc* LOC6;
				NI TMP284;
				nimln(353, "system.nim");
				if (!(((NI) 2) <= res_117024)) goto LA3;
				nimln(1864, "system.nim");
				i_117011 = res_117024;
				nimln(15, "msgpackMacroTest.nim");
				LOC4 = 0;
				LOC4 = pow(2.0000000000000000e+00, ((NF)(1.0000000000000000e+00) + (NF)(((NF) (i_117011)))));
				LOC5 = 0;
				LOC5 = pow(2.0000000000000000e+00, ((NF)(LOC4) - (NF)(1.0000000000000000e+00)));
				LOC6 = 0;
				LOC6 = nimFloatToStr(-(LOC5));
				printf("%s\012", LOC6? (LOC6)->data:"nil");
				fflush(stdout);
				nimln(1865, "system.nim");
				TMP284 = subInt(res_117024, ((NI) 1));
				res_117024 = (NI)(TMP284);
			} LA3: ;
		}
	}
	nimln(16, "msgpackMacroTest.nim");
	LOC7 = 0;
	LOC7 = HEX5E_117031(((NI) 2), ((NI) 31));
	TMP288 = subInt(LOC7, ((NI) 1));
	TMP289 = subInt(((NI) 2147483647), (NI)(TMP288));
	LOC8 = 0;
	LOC8 = nimIntToStr((NI)(TMP289));
	printf("%s\012", LOC8? (LOC8)->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, msgpackMacroTestDatInit000)(void) {
}

