/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/session.o /home/cyril/Projects/provider/nimcache/session.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
#include <string.h>
#include <stdio.h>
#include <setjmp.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Channel90204 Channel90204;
typedef struct TNimType TNimType;
typedef struct Memregion36688 Memregion36688;
typedef struct Smallchunk36640 Smallchunk36640;
typedef struct Llchunk36682 Llchunk36682;
typedef struct Bigchunk36642 Bigchunk36642;
typedef struct Intset36614 Intset36614;
typedef struct Trunk36610 Trunk36610;
typedef struct Avlnode36686 Avlnode36686;
typedef struct Table193063 Table193063;
typedef struct TY193211 TY193211;
typedef struct TY193214 TY193214;
typedef struct TNimNode TNimNode;
typedef struct Keyvaluepairseq193066 Keyvaluepairseq193066;
typedef struct Message193042 Message193042;
typedef struct VimHEX3Aobjecttype193046 VimHEX3Aobjecttype193046;
typedef struct Streamobj129218 Streamobj129218;
typedef struct Streaminterface193034 Streaminterface193034;
typedef struct Keyvaluepair193069 Keyvaluepair193069;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct Cell54507 Cell54507;
typedef struct Cellset54519 Cellset54519;
typedef struct Gcheap56818 Gcheap56818;
typedef struct Gcstack56816 Gcstack56816;
typedef struct Cellseq54523 Cellseq54523;
typedef struct Pagedesc54515 Pagedesc54515;
typedef struct Gcstat56814 Gcstat56814;
typedef struct TY193711 TY193711;
typedef struct TY193723 TY193723;
typedef struct TY193998 TY193998;
typedef struct TY194194 TY194194;
typedef struct Stringstreamobj129949 Stringstreamobj129949;
typedef struct Filestreamobj130048 Filestreamobj130048;
typedef struct Basechunk36638 Basechunk36638;
typedef struct Freecell36630 Freecell36630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* TY193001[1];
typedef Smallchunk36640* TY36703[512];
typedef Trunk36610* Trunkbuckets36612[256];
struct  Intset36614  {
Trunkbuckets36612 data;
};
struct  Memregion36688  {
NI minlargeobj;
NI maxlargeobj;
TY36703 freesmallchunks;
Llchunk36682* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk36642* freechunkslist;
Intset36614 chunkstarts;
Avlnode36686* root;
Avlnode36686* deleted;
Avlnode36686* last;
Avlnode36686* freeavlnodes;
};
struct  Channel90204  {
NI rd;
NI wr;
NI count;
NI mask;
NU8* data;
pthread_mutex_t lock;
pthread_cond_t cond;
TNimType* elemtype;
NIM_BOOL ready;
Memregion36688 region;
};
struct TY193211 {
void* Field0;
TY193214* Field1;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY193214 {
char dummy;
};
struct  Table193063  {
Keyvaluepairseq193066* data;
NI counter;
};
struct  Message193042  {
NU8 kind;
union{
NimStringDesc* s;
} kindU;
};
struct  Streaminterface193034  {
Streamobj129218* s;
};
struct  VimHEX3Aobjecttype193046  {
Streaminterface193034 i;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (VimHEX3Aobjecttype193046* s, void* ClEnv);
void* ClEnv;
} TY193057;
struct Keyvaluepair193069 {
NI Field0;
NimStringDesc* Field1;
TY193057 Field2;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY18211;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY18211 raiseAction;
};
typedef NimStringDesc* TY193424[2];
typedef N_CLOSURE_PTR(void, TMP651) (VimHEX3Aobjecttype193046* s);
typedef N_CLOSURE_PTR(void, TMP652) (VimHEX3Aobjecttype193046* s);
struct  Cell54507  {
NI refcount;
TNimType* typ;
};
struct  Cellseq54523  {
NI len;
NI cap;
Cell54507** d;
};
struct  Cellset54519  {
NI counter;
NI max;
Pagedesc54515* head;
Pagedesc54515** data;
};
struct  Gcstat56814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap56818  {
Gcstack56816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq54523 zct;
Cellseq54523 decstack;
Cellset54519 cycleroots;
Cellseq54523 tempstack;
NI recgclock;
Memregion36688 region;
Gcstat56814 stat;
};
struct  TY193711  {
VimHEX3Aobjecttype193046* vim193714;
};
typedef N_NIMCALL_PTR(void, Workerproc187228) (void* thread, void* args);
struct  TY193723  {
VimHEX3Aobjecttype193046* vim193726;
Table193063 rpctable193730;
};
struct  TY193998  {
NI HEX3Astate;
NI a193939;
NI b193940;
NI c193941;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* ClEnv);
void* ClEnv;
} TY193986;
struct  TY194194  {
TY193986 fn194197;
};
typedef N_NIMCALL_PTR(void, TY129219) (Streamobj129218* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY129223) (Streamobj129218* s);
typedef N_NIMCALL_PTR(void, TY129227) (Streamobj129218* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY129232) (Streamobj129218* s);
typedef N_NIMCALL_PTR(NI, TY129236) (Streamobj129218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY129242) (Streamobj129218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY129248) (Streamobj129218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY129254) (Streamobj129218* s);
struct  Streamobj129218  {
  TNimObject Sup;
TY129219 closeimpl;
TY129223 atendimpl;
TY129227 setpositionimpl;
TY129232 getpositionimpl;
TY129236 readdataimpl;
TY129242 peekdataimpl;
TY129248 writedataimpl;
TY129254 flushimpl;
};
struct  Stringstreamobj129949  {
  Streamobj129218 Sup;
NimStringDesc* data;
NI pos;
};
typedef N_CLOSURE_PTR(void, TMP667) (void);
typedef N_CLOSURE_PTR(void, TMP668) (VimHEX3Aobjecttype193046* s, void* ClEnv);
struct  Basechunk36638  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk36640  {
  Basechunk36638 Sup;
Smallchunk36640* next;
Smallchunk36640* prev;
Freecell36630* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk36682  {
NI size;
NI acc;
Llchunk36682* next;
};
struct  Bigchunk36642  {
  Basechunk36638 Sup;
Bigchunk36642* next;
Bigchunk36642* prev;
NI align;
NF data;
};
typedef NI TY36619[8];
struct  Trunk36610  {
Trunk36610* next;
NI key;
TY36619 bits;
};
typedef Avlnode36686* TY36693[2];
struct  Avlnode36686  {
TY36693 link;
NI key;
NI upperbound;
NI level;
};
struct  Gcstack56816  {
Gcstack56816* prev;
Gcstack56816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Pagedesc54515  {
Pagedesc54515* next;
NI key;
TY36619 bits;
};
struct  Filestreamobj130048  {
  Streamobj129218 Sup;
FILE* f;
};
struct  Freecell36630  {
Freecell36630* next;
NI zerofield;
};
struct Keyvaluepairseq193066 {
  TGenericSeq Sup;
  Keyvaluepair193069 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, addlogger_192076)(FILE* file);
N_NIMCALL(FILE*, open_15417)(NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(void, send_192563)(NimStringDesc* module, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, inittable_193097)(NI initialsize, Table193063* Result);
N_NIMCALL(void, TMP636)(void* p, NI op);
N_NIMCALL(void, initrpctable_193090)(Table193063* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_28801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, fecho_193231)(NimStringDesc* s_193233);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(void, send_193250)(Channel90204* c, Message193042 msg);
N_NIMCALL(void, write_193245)(NimStringDesc* s);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, write_193290)(VimHEX3Aobjecttype193046* vim, NimStringDesc* s);
N_NIMCALL(void, recv_193298)(Channel90204* c, Message193042* Result);
N_NIMCALL(void, writerthread_193294)(VimHEX3Aobjecttype193046* vim);
N_NIMCALL(void, unpack_193405)(VimHEX3Aobjecttype193046* s, NI* it);
N_NIMCALL(void, unpack_193414)(Streamobj129218* s, NI* val);
N_NIMCALL(void, unpack_193467)(VimHEX3Aobjecttype193046* s, NimStringDesc** it);
N_NIMCALL(void, unpack_193476)(Streamobj129218* s, NimStringDesc** val);
N_NIMCALL(void, HEX5BHEX5D_193489)(Table193063 t, NimStringDesc* key, TY193057* Result);
static N_INLINE(NI, rawget_193504)(Table193063 t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_111827)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isfilled_124263)(NI hcode);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NI, nexttry_124401)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, readerthread_193324)(VimHEX3Aobjecttype193046* vim, Table193063 rpctable);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NI, unpackarray_179851)(Streamobj129218* s);
N_NIMCALL(void, failedassertimpl_97116)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
static N_INLINE(NimStringDesc*, getcurrentexceptionmsg_95605)(void);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_60819)(Cell54507* c);
static N_INLINE(NIM_BOOL, canbecycleroot_58476)(Cell54507* c);
static N_INLINE(void, rtladdcycleroot_59220)(Cell54507* c);
N_NOINLINE(void, incl_55247)(Cellset54519* s, Cell54507* cell);
static N_INLINE(Cell54507*, usrtocell_58458)(void* usr);
static N_INLINE(void, decref_60401)(Cell54507* c);
static N_INLINE(void, rtladdzct_60001)(Cell54507* c);
N_NOINLINE(void, addzct_58435)(Cellseq54523* s, Cell54507* c);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, close_193686)(Channel90204* c);
N_NIMCALL(void, stop_193672)(void);
N_NIMCALL(void, sync_191624)(void);
N_NIMCALL(void, open_193700)(Channel90204* c);
N_NIMCALL(void, init_193696)(VimHEX3Aobjecttype193046* vim);
N_NIMCALL(void, nimSpawn3)(Workerproc187228 fn, void* data);
N_NIMCALL(void, writerthreadwrapper_193719)(void* thread, void* args);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP655)(void* p, NI op);
N_NIMCALL(void, genericDeepCopy)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, nimArgsPassingDone)(void* p);
N_NIMCALL(void, readerthreadwrapper_193735)(void* thread, void* args);
N_NIMCALL(void, pack_193988)(Streamobj129218* s, NimStringDesc* val);
N_NIMCALL(void, HEX5BHEX5DHEX3D_194011)(Table193063* t, NimStringDesc* key, TY193057 val);
N_NIMCALL(void, enlarge_194047)(Table193063* t);
static N_INLINE(NI, rawgetknownhc_194100)(Table193063 t, NimStringDesc* key, NI hc);
N_NIMCALL(void, rawinsert_194116)(Table193063* t, Keyvaluepairseq193066** data, NimStringDesc* key, TY193057 val, NI hc, NI h);
N_NIMCALL(NimStringDesc*, abc_193947)(NI a, NI b, NI c);
N_NIMCALL(void, HEX3Aanonymous_193953)(VimHEX3Aobjecttype193046* s);
N_NIMCALL(void, TMP666)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_CLOSURE(void, proxy_193946)(void* ClEnv);
N_NIMCALL(Stringstreamobj129949*, newstringstream_130033)(NimStringDesc* s);
N_NIMCALL(void, HEX3Atmpwrapper_194200)(void* thread, void* args);
N_NIMCALL(Filestreamobj130048*, newfilestream_130101)(FILE* f);
N_NIMCALL(NI, paramcount_160426)(void);
N_NIMCALL(NimStringDesc*, paramstr_160407)(NI i);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_listsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_listsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_queuesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_queuesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_critbitsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_critbitsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_msgpackInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_msgpackDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linuxInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linuxDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_locksInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_locksDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_loggerInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_loggerDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sessionInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sessionDatInit000)(void);
STRING_LITERAL(TMP629, "nivmlog.log", 11);
STRING_LITERAL(TMP630, "session", 7);
STRING_LITERAL(TMP632, "started", 7);
NIM_CONST TY193001 TMP631 = {((NimStringDesc*) &TMP632)}
;
STRING_LITERAL(TMP639, "\012", 1);
TNimNode* NimDT_193042_kind[3];
STRING_LITERAL(TMP643, "s", 1);
STRING_LITERAL(TMP649, "unpack_array(vim.i.s) == 4 ", 27);
STRING_LITERAL(TMP650, "in", 2);
STRING_LITERAL(TMP653, "", 0);
STRING_LITERAL(TMP664, "abc", 3);
Channel90204 outchannel_193088;
TNimType NTI193057; /* (pointer, ref tuple[]) */
extern TNimType NTI142; /* pointer */
TNimType NTI193214; /* tuple[] */
TNimType NTI193213; /* ref tuple[] */
extern TNimType NTI193063; /* Table */
extern NIM_THREADVAR TFrame* frameptr_26036;
Table193063 rpctable_193215;
TNimType NTI193042; /* Message */
TNimType NTI193040; /* MessageKind */
extern TNimType NTI138; /* string */
extern NIM_THREADVAR TSafePoint* exchandler_26037;
extern NIM_THREADVAR Exception* currexception_26039;
extern NIM_THREADVAR Gcheap56818 gch_56859;
TNimType NTI193046; /* Vim:ObjectType */
TNimType NTI193034; /* StreamInterface */
extern TNimType NTI129216; /* Stream */
TNimType NTI193036; /* Vim */
TNimType NTI193998; /* object */
extern TNimType NTI133021; /* range -1..0(int) */
extern TNimType NTI104; /* int */
TNimType NTI193997; /* ref object */
Filestreamobj130048* instream_194202;
Filestreamobj130048* outstream_194203;
NI i_194213;
VimHEX3Aobjecttype193046* i_194254;
N_NIMCALL(void, TMP636)(void* p, NI op) {
	TY193214* a;
	a = (TY193214*)p;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_26036 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_26036).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_26036;
	frameptr_26036 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_28801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_26036 = (*frameptr_26036).prev;
}

N_NIMCALL(void, initrpctable_193090)(Table193063* Result) {
	nimfr("initRpcTable", "session.nim")
	nimln(26, "session.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI193063));
	inittable_193097(((NI) 64), Result);
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(void, fecho_193231)(NimStringDesc* s_193233) {
	NimStringDesc* s;
	NimStringDesc* LOC1;
	nimfr("fecho", "session.nim")
	nimln(32, "session.nim");
	LOC1 = 0;
	LOC1 = rawNewString(s_193233->Sup.len + 1);
appendString(LOC1, s_193233);
appendString(LOC1, ((NimStringDesc*) &TMP639));
	s = LOC1;
	nimln(33, "session.nim");
	fwrite(s->data, ((NI) 1), (s ? s->Sup.len : 0), stdout);
	popFrame();
}

N_NIMCALL(void, write_193245)(NimStringDesc* s) {
	Message193042 LOC1;
	nimfr("write", "session.nim")
	nimln(37, "session.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.kind = ((NU8) 0);
	if (!(((1 &(1U<<((NU)(LOC1.kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TMP643));
	LOC1.kindU.s = copyString(s);
	send_193250((&outchannel_193088), LOC1);
	popFrame();
}

N_NIMCALL(void, write_193290)(VimHEX3Aobjecttype193046* vim, NimStringDesc* s) {
	nimfr("write", "session.nim")
	nimln(40, "session.nim");
	fecho_193231(s);
	popFrame();
}

N_NIMCALL(void, writerthread_193294)(VimHEX3Aobjecttype193046* vim) {
	nimfr("writerThread", "session.nim")
	{
		nimln(42, "session.nim");
		while (1) {
			Message193042 msg;
			memset((void*)(&msg), 0, sizeof(msg));
			nimln(43, "session.nim");
			chckNil((void*)(&msg));
			memset((void*)(&msg), 0, sizeof(msg));
			recv_193298((&outchannel_193088), (&msg));
			nimln(44, "session.nim");
			switch (msg.kind) {
			case ((NU8) 0):
			{
				nimln(46, "session.nim");
				if (!(((1 &(1U<<((NU)(msg.kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TMP643));
				write_193290(vim, msg.kindU.s);
			}
			break;
			case ((NU8) 1):
			{
				nimln(48, "session.nim");
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	popFrame();
}

N_NIMCALL(void, unpack_193405)(VimHEX3Aobjecttype193046* s, NI* it) {
	nimfr("unpack", "session.nim")
	nimln(34, "session.nim");
	unpack_193414((*s).i.s, it);
	popFrame();
}

N_NIMCALL(void, unpack_193467)(VimHEX3Aobjecttype193046* s, NimStringDesc** it) {
	nimfr("unpack", "session.nim")
	nimln(34, "session.nim");
	unpack_193476((*s).i.s, it);
	popFrame();
}

static N_INLINE(NIM_BOOL, isfilled_124263)(NI hcode) {
	NIM_BOOL result;
	nimfr("isFilled", "tableimpl.nim")
	result = 0;
	nimln(18, "tableimpl.nim");
	nimln(349, "system.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_124401)(NI h, NI maxhash) {
	NI result;
	NI TMP646;
	nimfr("nextTry", "tableimpl.nim")
	result = 0;
	nimln(28, "tableimpl.nim");
	TMP646 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TMP646) & maxhash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, rawget_193504)(Table193063 t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI TMP647;
	nimfr("rawGet", "tableimpl.nim")
{	result = 0;
	nimln(43, "tableimpl.nim");
	(*hc) = hash_111827(key);
	nimln(44, "tableimpl.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_124263(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = eqStrings(t.data->data[h].Field1, key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_124401(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(40, "tableimpl.nim");
	TMP647 = subInt(((NI) -1), h);
	result = (NI)(TMP647);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_26037;
	exchandler_26037 = s;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_26037 = (*exchandler_26037).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_26036 = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr("getCurrentException", "system.nim")
	result = 0;
	nimln(2990, "system.nim");
	result = currexception_26039;
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, getcurrentexceptionmsg_95605)(void) {
	NimStringDesc* result;
	Exception* e;
	nimfr("getCurrentExceptionMsg", "system.nim")
{	result = 0;
	nimln(2995, "system.nim");
	e = getCurrentException();
	nimln(2996, "system.nim");
	{
		if (!(e == NIM_NIL)) goto LA3;
		result = copyString(((NimStringDesc*) &TMP653));
	}
	goto LA1;
	LA3: ;
	{
		result = copyString((*e).message);
	}
	LA1: ;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_58476)(Cell54507* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1U<<((NU)(((NU8) 1))&7U)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_59220)(Cell54507* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_55247((&gch_56859.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_60819)(Cell54507* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_58476(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_59220(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(Cell54507*, usrtocell_58458)(void* usr) {
	Cell54507* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell54507*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell54507))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_60001)(Cell54507* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_58435((&gch_56859.zct), c);
	popFrame();
}

static N_INLINE(void, decref_60401)(Cell54507* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_60001(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_58476(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_59220(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell54507* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_58458(src);
		incref_60819(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell54507* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_58458((*dest));
		decref_60401(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_26039), NIM_NIL);
}

N_NIMCALL(void, readerthread_193324)(VimHEX3Aobjecttype193046* vim, Table193063 rpctable) {
	TSafePoint TMP648;
	nimfr("readerThread", "session.nim")
	nimln(51, "session.nim");
	pushSafePoint(&TMP648);
	TMP648.status = setjmp(TMP648.context);
	if (TMP648.status == 0) {
		{
			nimln(52, "session.nim");
			while (1) {
				NI calltype;
				NI msgid;
				NimStringDesc* methodname;
				TY193424 LOC9;
				nimln(53, "session.nim");
				{
					NI LOC6;
					LOC6 = 0;
					LOC6 = unpackarray_179851((*vim).i.s);
					if (!!((LOC6 == ((NI) 4)))) goto LA7;
					failedassertimpl_97116(((NimStringDesc*) &TMP649));
				}
				LA7: ;
				calltype = 0;
				msgid = 0;
				methodname = 0;
				nimln(58, "session.nim");
				unpack_193405(vim, (&calltype));
				nimln(80, "logger.nim");
				memset((void*)LOC9, 0, sizeof(LOC9));
				LOC9[0] = copyString(((NimStringDesc*) &TMP650));
				nimln(59, "session.nim");
				LOC9[1] = nimIntToStr(calltype);
				send_192563(((NimStringDesc*) &TMP630), LOC9, 2);
				nimln(60, "session.nim");
				switch (((NU8)chckRange(calltype, ((NU8) 0), ((NU8) 2)))) {
				case ((NU8) 0):
				{
					TY193057 LOC11;
					nimln(62, "session.nim");
					unpack_193405(vim, (&msgid));
					nimln(63, "session.nim");
					unpack_193467(vim, (&methodname));
					nimln(64, "session.nim");
					memset((void*)(&LOC11), 0, sizeof(LOC11));
					HEX5BHEX5D_193489(rpctable, methodname, (&LOC11));
					LOC11.ClEnv? LOC11.ClPrc(vim, LOC11.ClEnv):((TMP651)(LOC11.ClPrc))(vim);
				}
				break;
				case ((NU8) 1):
				{
				}
				break;
				case ((NU8) 2):
				{
					TY193057 LOC14;
					nimln(68, "session.nim");
					unpack_193467(vim, (&methodname));
					nimln(69, "session.nim");
					memset((void*)(&LOC14), 0, sizeof(LOC14));
					HEX5BHEX5D_193489(rpctable, methodname, (&LOC14));
					LOC14.ClEnv? LOC14.ClPrc(vim, LOC14.ClEnv):((TMP652)(LOC14.ClPrc))(vim);
				}
				break;
				}
			}
		}
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
		{
			TY193001 LOC17;
			TMP648.status = 0;
			nimln(80, "logger.nim");
			memset((void*)LOC17, 0, sizeof(LOC17));
			nimln(71, "session.nim");
			LOC17[0] = getcurrentexceptionmsg_95605();
			send_192563(((NimStringDesc*) &TMP630), LOC17, 1);
			popCurrentException();
		}
	}
	if (TMP648.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(void, stop_193672)(void) {
	Message193042 LOC1;
	nimfr("stop", "session.nim")
	nimln(74, "session.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.kind = ((NU8) 1);
	send_193250((&outchannel_193088), LOC1);
	nimln(75, "session.nim");
	sync_191624();
	nimln(76, "session.nim");
	close_193686((&outchannel_193088));
	popFrame();
}
N_NIMCALL(void, TMP655)(void* p, NI op) {
	VimHEX3Aobjecttype193046* a;
	a = (VimHEX3Aobjecttype193046*)p;
	nimGCvisit((void*)(*a).i.s, op);
}

N_NIMCALL(void, writerthreadwrapper_193719)(void* thread, void* args) {
	VimHEX3Aobjecttype193046* HEX3Atmp_193716;
	nimfr("writerThreadWrapper", "session.nim")
	HEX3Atmp_193716 = 0;
	nimln(80, "session.nim");
	genericDeepCopy((void*)(&HEX3Atmp_193716), (void*)(&(*((TY193711*) (args))).vim193714), (&NTI193036));
	nimArgsPassingDone(thread);
	writerthread_193294(HEX3Atmp_193716);
	popFrame();
}

N_NIMCALL(void, readerthreadwrapper_193735)(void* thread, void* args) {
	VimHEX3Aobjecttype193046* HEX3Atmp_193728;
	Table193063 HEX3Atmp_193732;
	nimfr("readerThreadWrapper", "session.nim")
	HEX3Atmp_193728 = 0;
	memset((void*)(&HEX3Atmp_193732), 0, sizeof(HEX3Atmp_193732));
	nimln(81, "session.nim");
	genericDeepCopy((void*)(&HEX3Atmp_193728), (void*)(&(*((TY193723*) (args))).vim193726), (&NTI193036));
	genericDeepCopy((void*)(&HEX3Atmp_193732), (void*)(&(*((TY193723*) (args))).rpctable193730), (&NTI193063));
	nimArgsPassingDone(thread);
	readerthread_193324(HEX3Atmp_193728, HEX3Atmp_193732);
	popFrame();
}

N_NIMCALL(void, init_193696)(VimHEX3Aobjecttype193046* vim) {
	TY193711 scratch_193713;
	TY193723 scratch_193725;
	nimfr("init", "session.nim")
	nimln(79, "session.nim");
	open_193700((&outchannel_193088));
	nimln(80, "session.nim");
	memset((void*)(&scratch_193713), 0, sizeof(scratch_193713));
	scratch_193713.vim193714 = vim;
	nimSpawn3(writerthreadwrapper_193719, (&scratch_193713));
	nimln(81, "session.nim");
	memset((void*)(&scratch_193725), 0, sizeof(scratch_193725));
	scratch_193725.vim193726 = vim;
	scratch_193725.rpctable193730.data = rpctable_193215.data;
	scratch_193725.rpctable193730.counter = rpctable_193215.counter;
	nimSpawn3(readerthreadwrapper_193735, (&scratch_193725));
	popFrame();
}

static N_INLINE(NI, rawgetknownhc_194100)(Table193063 t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI TMP662;
	nimfr("rawGetKnownHC", "tableimpl.nim")
{	result = 0;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_124263(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = eqStrings(t.data->data[h].Field1, key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_124401(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(40, "tableimpl.nim");
	TMP662 = subInt(((NI) -1), h);
	result = (NI)(TMP662);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, abc_193947)(NI a, NI b, NI c) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NI TMP663;
	NimStringDesc* LOC3;
	nimfr("abc", "session.nim")
{	result = 0;
	nimln(164, "session.nim");
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = nimIntToStr(a);
	TMP663 = addInt(b, c);
	LOC3 = 0;
	LOC3 = nimIntToStr((NI)(TMP663));
	LOC1 = rawNewString(LOC2->Sup.len + LOC3->Sup.len + 0);
appendString(LOC1, LOC2);
appendString(LOC1, LOC3);
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP666)(void* p, NI op) {
	TY193998* a;
	a = (TY193998*)p;
}

N_CLOSURE(void, proxy_193946)(void* ClEnv) {
	TY193998* HEX3Aenvp_194001;
	NimStringDesc* res_193943;
	Stringstreamobj129949* packstream_193945;
	Streamobj129218* LOC1;
	nimfr("proxy", "session.nim")
	HEX3Aenvp_194001 = (TY193998*) ClEnv;
	nimln(126, "session.nim");
	res_193943 = abc_193947((*HEX3Aenvp_194001).a193939, (*HEX3Aenvp_194001).b193940, (*HEX3Aenvp_194001).c193941);
	nimln(127, "session.nim");
	packstream_193945 = newstringstream_130033(((NimStringDesc*) &TMP653));
	nimln(128, "session.nim");
	LOC1 = 0;
	LOC1 = &packstream_193945->Sup;
	pack_193988(LOC1, res_193943);
	nimln(129, "session.nim");
	write_193245((*packstream_193945).data);
	popFrame();
}

N_NIMCALL(void, HEX3Atmpwrapper_194200)(void* thread, void* args) {
	nimfr(":tmpWrapper", "session.nim")
	nimln(163, "session.nim");
	nimArgsPassingDone(thread);
	(*((TY194194*) (args))).fn194197.ClEnv? (*((TY194194*) (args))).fn194197.ClPrc((*((TY194194*) (args))).fn194197.ClEnv):((TMP667)((*((TY194194*) (args))).fn194197.ClPrc))();
	popFrame();
}

N_NIMCALL(void, HEX3Aanonymous_193953)(VimHEX3Aobjecttype193046* s) {
	TY193998* HEX3Aenv_194005;
	NI parlen_193938;
	NI LOC1;
	TY194194 scratch_194196;
	TY193986 LOC2;
	nimfr(":anonymous", "session.nim")
	HEX3Aenv_194005 = 0;
	nimln(198, "system.nim");
	HEX3Aenv_194005 = (TY193998*) newObj((&NTI193997), sizeof(TY193998));
	parlen_193938 = 0;
	nimln(163, "session.nim");
	(*HEX3Aenv_194005).a193939 = ((NI) 2);
	(*HEX3Aenv_194005).b193940 = ((NI) 2);
	(*HEX3Aenv_194005).c193941 = ((NI) 2);
	nimln(99, "session.nim");
	LOC1 = 0;
	LOC1 = unpackarray_179851((*s).i.s);
	nimln(163, "session.nim");
	unpack_193405(s, (&(*HEX3Aenv_194005).a193939));
	unpack_193405(s, (&(*HEX3Aenv_194005).b193940));
	unpack_193405(s, (&(*HEX3Aenv_194005).c193941));
	memset((void*)(&scratch_194196), 0, sizeof(scratch_194196));
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = proxy_193946; LOC2.ClEnv = HEX3Aenv_194005;
	scratch_194196.fn194197.ClEnv = LOC2.ClEnv;
	scratch_194196.fn194197.ClPrc = LOC2.ClPrc;
	nimSpawn3(HEX3Atmpwrapper_194200, (&scratch_194196));
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_timesDatInit000();
	stdlib_mathDatInit000();
	stdlib_tablesDatInit000();
	stdlib_streamsDatInit000();
	stdlib_endiansDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_intsetsDatInit000();
	stdlib_listsDatInit000();
	stdlib_queuesDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	stdlib_setsDatInit000();
	stdlib_strtabsDatInit000();
	stdlib_critbitsDatInit000();
	stdlib_macrosDatInit000();
	HEX00_msgpackDatInit000();
	stdlib_linuxDatInit000();
	stdlib_cpuinfoDatInit000();
	stdlib_cpuloadDatInit000();
	stdlib_locksDatInit000();
	stdlib_threadpoolDatInit000();
	HEX00_loggerDatInit000();
	sessionDatInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_timesInit000();
	stdlib_mathInit000();
	stdlib_tablesInit000();
	stdlib_streamsInit000();
	stdlib_endiansInit000();
	stdlib_sequtilsInit000();
	stdlib_algorithmInit000();
	stdlib_intsetsInit000();
	stdlib_listsInit000();
	stdlib_queuesInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
	stdlib_setsInit000();
	stdlib_strtabsInit000();
	stdlib_critbitsInit000();
	stdlib_macrosInit000();
	HEX00_msgpackInit000();
	stdlib_linuxInit000();
	stdlib_cpuinfoInit000();
	stdlib_cpuloadInit000();
	stdlib_locksInit000();
	stdlib_threadpoolInit000();
	HEX00_loggerInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	sessionInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, sessionInit000)(void) {
	FILE* LOC1;
	Channel90204 LOC2;
	TY193057 LOC3;
	VimHEX3Aobjecttype193046* LOC8;
	Streaminterface193034 LOC9;
	nimfr("session", "session.nim")
	nimln(3, "session.nim");
	LOC1 = 0;
	LOC1 = open_15417(((NimStringDesc*) &TMP629), ((NU8) 1), ((NI) -1));
	addlogger_192076(LOC1);
	nimln(80, "logger.nim");
	send_192563(((NimStringDesc*) &TMP630), TMP631, 1);
	nimln(24, "session.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	outchannel_193088 = LOC2;
	nimln(27, "session.nim");
	chckNil((void*)(&rpctable_193215));
	genericReset((void*)(&rpctable_193215), (&NTI193063));
	initrpctable_193090((&rpctable_193215));
	nimln(163, "session.nim");
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	LOC3.ClPrc = ((TMP668) (HEX3Aanonymous_193953)); LOC3.ClEnv = NIM_NIL;
	HEX5BHEX5DHEX3D_194011((&rpctable_193215), ((NimStringDesc*) &TMP664), LOC3);
	nimln(168, "session.nim");
	asgnRef((void**) (&instream_194202), newfilestream_130101(stdin));
	nimln(169, "session.nim");
	asgnRef((void**) (&outstream_194203), newfilestream_130101(stdout));
	{
		NI HEX3Atmp_194247;
		NI res_194250;
		HEX3Atmp_194247 = 0;
		nimln(172, "session.nim");
		HEX3Atmp_194247 = paramcount_160426();
		nimln(1874, "system.nim");
		res_194250 = ((NI) 1);
		{
			nimln(1875, "system.nim");
			while (1) {
				TY193001 LOC7;
				NI TMP671;
				if (!(res_194250 <= HEX3Atmp_194247)) goto LA6;
				nimln(1876, "system.nim");
				i_194213 = res_194250;
				nimln(80, "logger.nim");
				memset((void*)LOC7, 0, sizeof(LOC7));
				nimln(173, "session.nim");
				LOC7[0] = paramstr_160407(i_194213);
				send_192563(((NimStringDesc*) &TMP630), LOC7, 1);
				nimln(1895, "system.nim");
				TMP671 = addInt(res_194250, ((NI) 1));
				res_194250 = (NI)(TMP671);
			} LA6: ;
		}
	}
	nimln(174, "session.nim");
	LOC8 = 0;
	LOC8 = (VimHEX3Aobjecttype193046*) newObj((&NTI193036), sizeof(VimHEX3Aobjecttype193046));
	memset((void*)(&LOC9), 0, sizeof(LOC9));
	memset((void*)(&LOC9), 0, sizeof(LOC9));
	LOC9.s = &instream_194202->Sup;
	asgnRef((void**) (&(*LOC8).i.s), LOC9.s);
	asgnRef((void**) (&i_194254), LOC8);
	nimln(175, "session.nim");
	init_193696(i_194254);
	nimln(176, "session.nim");
	sync_191624();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sessionDatInit000)(void) {
static TNimNode* TMP635[2];
static TNimNode* TMP640[2];
NI TMP642;
static char* NIM_CONST TMP641[2] = {
"kWrite", 
"kStop"};
static TNimNode* TMP665[4];
static TNimNode TMP141[17];
NTI193057.size = sizeof(TY193211);
NTI193057.kind = 18;
NTI193057.base = 0;
NTI193057.flags = 2;
TMP635[0] = &TMP141[1];
TMP141[1].kind = 1;
TMP141[1].offset = offsetof(TY193211, Field0);
TMP141[1].typ = (&NTI142);
TMP141[1].name = "Field0";
TMP635[1] = &TMP141[2];
NTI193214.size = sizeof(TY193214);
NTI193214.kind = 18;
NTI193214.base = 0;
NTI193214.flags = 3;
TMP141[3].len = 0; TMP141[3].kind = 2;
NTI193214.node = &TMP141[3];
NTI193213.size = sizeof(TY193214*);
NTI193213.kind = 22;
NTI193213.base = (&NTI193214);
NTI193213.flags = 2;
NTI193213.marker = TMP636;
TMP141[2].kind = 1;
TMP141[2].offset = offsetof(TY193211, Field1);
TMP141[2].typ = (&NTI193213);
TMP141[2].name = "Field1";
TMP141[0].len = 2; TMP141[0].kind = 2; TMP141[0].sons = &TMP635[0];
NTI193057.node = &TMP141[0];
NTI193042.size = sizeof(Message193042);
NTI193042.kind = 18;
NTI193042.base = 0;
NTI193042.flags = 2;
NTI193040.size = sizeof(NU8);
NTI193040.kind = 14;
NTI193040.base = 0;
NTI193040.flags = 3;
for (TMP642 = 0; TMP642 < 2; TMP642++) {
TMP141[TMP642+5].kind = 1;
TMP141[TMP642+5].offset = TMP642;
TMP141[TMP642+5].name = TMP641[TMP642];
TMP640[TMP642] = &TMP141[TMP642+5];
}
TMP141[7].len = 2; TMP141[7].kind = 2; TMP141[7].sons = &TMP640[0];
NTI193040.node = &TMP141[7];
TMP141[4].kind = 3;
TMP141[4].offset = offsetof(Message193042, kind);
TMP141[4].typ = (&NTI193040);
TMP141[4].name = "kind";
TMP141[4].sons = &NimDT_193042_kind[0];
TMP141[4].len = 2;
TMP141[8].kind = 1;
TMP141[8].offset = offsetof(Message193042, kindU.s);
TMP141[8].typ = (&NTI138);
TMP141[8].name = "s";
NimDT_193042_kind[0] = &TMP141[8];
TMP141[9].len = 0; TMP141[9].kind = 2;
NimDT_193042_kind[1] = &TMP141[9];
NTI193042.node = &TMP141[4];
NTI193046.size = sizeof(VimHEX3Aobjecttype193046);
NTI193046.kind = 18;
NTI193046.base = 0;
NTI193034.size = sizeof(Streaminterface193034);
NTI193034.kind = 18;
NTI193034.base = 0;
TMP141[11].kind = 1;
TMP141[11].offset = offsetof(Streaminterface193034, s);
TMP141[11].typ = (&NTI129216);
TMP141[11].name = "s";
NTI193034.node = &TMP141[11];
TMP141[10].kind = 1;
TMP141[10].offset = offsetof(VimHEX3Aobjecttype193046, i);
TMP141[10].typ = (&NTI193034);
TMP141[10].name = "i";
NTI193046.node = &TMP141[10];
NTI193036.size = sizeof(VimHEX3Aobjecttype193046*);
NTI193036.kind = 22;
NTI193036.base = (&NTI193046);
NTI193036.marker = TMP655;
NTI193998.size = sizeof(TY193998);
NTI193998.kind = 18;
NTI193998.base = 0;
NTI193998.flags = 3;
TMP665[0] = &TMP141[13];
TMP141[13].kind = 1;
TMP141[13].offset = offsetof(TY193998, HEX3Astate);
TMP141[13].typ = (&NTI133021);
TMP141[13].name = ":state";
TMP665[1] = &TMP141[14];
TMP141[14].kind = 1;
TMP141[14].offset = offsetof(TY193998, a193939);
TMP141[14].typ = (&NTI104);
TMP141[14].name = "a193939";
TMP665[2] = &TMP141[15];
TMP141[15].kind = 1;
TMP141[15].offset = offsetof(TY193998, b193940);
TMP141[15].typ = (&NTI104);
TMP141[15].name = "b193940";
TMP665[3] = &TMP141[16];
TMP141[16].kind = 1;
TMP141[16].offset = offsetof(TY193998, c193941);
TMP141[16].typ = (&NTI104);
TMP141[16].name = "c193941";
TMP141[12].len = 4; TMP141[12].kind = 2; TMP141[12].sons = &TMP665[0];
NTI193998.node = &TMP141[12];
NTI193997.size = sizeof(TY193998*);
NTI193997.kind = 22;
NTI193997.base = (&NTI193998);
NTI193997.flags = 2;
NTI193997.marker = TMP666;
}

