/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/stdlib_strutils.o /home/cyril/Projects/provider/nimcache/stdlib_strutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Slice88082 Slice88082;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR TY102408[6];
typedef NIM_CHAR TY102412[2501];
typedef NIM_CHAR TY102404[3];
struct  Slice88082  {
NI a;
NI b;
};
N_NIMCALL(NimStringDesc*, nsuformatBiggestFloat)(NF f, NU8 format, NI precision, NIM_CHAR decimalsep);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(Slice88082, HEX2EHEX2E_102424)(NI a, NI b);
NIM_CONST TY102404 floatformattochar_102401 = {103,
102,
101}
;

static N_INLINE(Slice88082, HEX2EHEX2E_102424)(NI a, NI b) {
	Slice88082 result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

N_NIMCALL(NimStringDesc*, nsuformatBiggestFloat)(NF f, NU8 format, NI precision, NIM_CHAR decimalsep) {
	NimStringDesc* result;
	TY102408 frmtstr;
	TY102412 buf;
	int L;
	result = 0;
	L = 0;
	frmtstr[(((NI) 0))- 0] = 37;
	{
		if (!(((NI) 0) < ((NI) (precision)))) goto LA3;
		frmtstr[(((NI) 1))- 0] = 35;
		frmtstr[(((NI) 2))- 0] = 46;
		frmtstr[(((NI) 3))- 0] = 42;
		frmtstr[(((NI) 4))- 0] = floatformattochar_102401[(format)- 0];
		frmtstr[(((NI) 5))- 0] = 0;
		L = sprintf(((NCSTRING) (buf)), ((NCSTRING) (frmtstr)), precision, f);
	}
	goto LA1;
	LA3: ;
	{
		frmtstr[(((NI) 1))- 0] = floatformattochar_102401[(format)- 0];
		frmtstr[(((NI) 2))- 0] = 0;
		L = sprintf(((NCSTRING) (buf)), ((NCSTRING) (frmtstr)), f);
	}
	LA1: ;
	result = mnewString(((NI) (L)));
	{
		NI i_102459;
		Slice88082 HEX3Atmp_102475;
		i_102459 = 0;
		memset((void*)(&HEX3Atmp_102475), 0, sizeof(HEX3Atmp_102475));
		HEX3Atmp_102475 = HEX2EHEX2E_102424(((NI) 0), ((NI) ((L - 1))));
		{
			NI x_102479;
			NI HEX3Atmp_102481;
			NI HEX3Atmp_102483;
			NI res_102485;
			x_102479 = 0;
			HEX3Atmp_102481 = 0;
			HEX3Atmp_102483 = 0;
			HEX3Atmp_102481 = HEX3Atmp_102475.a;
			HEX3Atmp_102483 = HEX3Atmp_102475.b;
			res_102485 = HEX3Atmp_102481;
			{
				while (1) {
					if (!(res_102485 <= HEX3Atmp_102483)) goto LA9;
					x_102479 = res_102485;
					i_102459 = x_102479;
					{
						if (!(((NU8)(buf[(i_102459)- 0])) == ((NU8)(46)) || ((NU8)(buf[(i_102459)- 0])) == ((NU8)(44)))) goto LA12;
						result->data[i_102459] = decimalsep;
					}
					goto LA10;
					LA12: ;
					{
						result->data[i_102459] = buf[(i_102459)- 0];
					}
					LA10: ;
					res_102485 += ((NI) 1);
				} LA9: ;
			}
		}
	}
	return result;
}

N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, NU8 format, NI precision, NIM_CHAR decimalsep) {
	NimStringDesc* result;
	result = 0;
	result = nsuformatBiggestFloat(f, format, precision, decimalsep);
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void) {
}

