/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/stdlib_sets.o /home/cyril/Projects/provider/nimcache/stdlib_sets.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isempty_170228)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isfilled_170232)(NI hcode);
static N_INLINE(NIM_BOOL, mustrehash_170271)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, rightsize_170401)(NI count);
N_NIMCALL(NI, nextpoweroftwo_155627)(NI x);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, nexttry_170408)(NI h, NI maxhash);
STRING_LITERAL(TMP734, "\012  counter < length ", 20);
extern TFrame* frameptr_19436;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(NIM_BOOL, isempty_170228)(NI hcode) {
	NIM_BOOL result;
	nimfr("isEmpty", "sets.nim")
	result = 0;
	nimln(47, "sets.nim");
	result = (hcode == ((NI) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isfilled_170232)(NI hcode) {
	NIM_BOOL result;
	nimfr("isFilled", "sets.nim")
	result = 0;
	nimln(50, "sets.nim");
	nimln(349, "system.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustrehash_170271)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP735;
	NI TMP736;
	NI TMP737;
	nimfr("mustRehash", "sets.nim")
	result = 0;
	nimln(114, "sets.nim");
	{
		if (!!((counter < length))) goto LA3;
		failedassertimpl_89116(((NimStringDesc*) &TMP734));
	}
	LA3: ;
	nimln(115, "sets.nim");
	LOC5 = 0;
	TMP735 = mulInt(length, ((NI) 2));
	TMP736 = mulInt(counter, ((NI) 3));
	LOC5 = ((NI)(TMP735) < (NI)(TMP736));
	if (LOC5) goto LA6;
	TMP737 = subInt(length, counter);
	LOC5 = ((NI)(TMP737) < ((NI) 4));
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, rightsize_170401)(NI count) {
	NI result;
	NI TMP738;
	NI TMP739;
	NI TMP740;
	nimfr("rightSize", "sets.nim")
	result = 0;
	nimln(124, "sets.nim");
	TMP738 = mulInt(((NI) (count)), ((NI) 3));
	TMP739 = divInt(((NI) ((NI)(TMP738))), ((NI) 2));
	TMP740 = addInt(((NI) ((NI)(TMP739))), ((NI) 4));
	result = nextpoweroftwo_155627(((NI) ((NI)(TMP740))));
	popFrame();
	return result;
}

static N_INLINE(NI, nexttry_170408)(NI h, NI maxhash) {
	NI result;
	NI TMP741;
	nimfr("nextTry", "sets.nim")
	result = 0;
	nimln(127, "sets.nim");
	TMP741 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TMP741) & maxhash);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_setsInit000)(void) {
	nimfr("sets", "sets.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_setsDatInit000)(void) {
}

