/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/stdlib_threadpool.o /home/cyril/Projects/provider/nimcache/stdlib_threadpool.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
#include <string.h>
#include <pthread.h>
typedef struct Semaphore187002 Semaphore187002;
typedef struct Barrier Barrier;
typedef struct Flowvarbaseobj187220 Flowvarbaseobj187220;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Awaitinfo187216 Awaitinfo187216;
typedef struct Worker187230 Worker187230;
typedef struct Tofreequeue187226 Tofreequeue187226;
typedef struct Cell54507 Cell54507;
typedef struct Cellseq54523 Cellseq54523;
typedef struct Gcheap56818 Gcheap56818;
typedef struct Gcstack56816 Gcstack56816;
typedef struct Cellset54519 Cellset54519;
typedef struct Pagedesc54515 Pagedesc54515;
typedef struct Memregion36688 Memregion36688;
typedef struct Smallchunk36640 Smallchunk36640;
typedef struct Llchunk36682 Llchunk36682;
typedef struct Bigchunk36642 Bigchunk36642;
typedef struct Intset36614 Intset36614;
typedef struct Trunk36610 Trunk36610;
typedef struct Avlnode36686 Avlnode36686;
typedef struct Gcstat56814 Gcstat56814;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Thread188608 Thread188608;
typedef struct Gcthread20006 Gcthread20006;
typedef struct Threadpoolstate185204 Threadpoolstate185204;
typedef struct Basechunk36638 Basechunk36638;
typedef struct Freecell36630 Freecell36630;
struct  Semaphore187002  {
pthread_cond_t c;
pthread_mutex_t L;
NI counter;
};
typedef NU8 TY187060[24];
struct  Barrier  {
NI entered;
Semaphore187002 cv;
NI left;
TY187060 cacheAlign2;
NIM_BOOL interest;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Flowvarbaseobj187220  {
  TNimObject Sup;
NIM_BOOL ready;
NIM_BOOL usessemaphore;
NIM_BOOL awaited;
Semaphore187002 cv;
Awaitinfo187216* ai;
NI idx;
void* data;
void* owner;
};
typedef N_NIMCALL_PTR(void, Workerproc187228) (void* thread, void* args);
typedef void* TY187258[128];
struct  Tofreequeue187226  {
NI len;
pthread_mutex_t lock;
Semaphore187002 empty;
TY187258 data;
};
struct  Worker187230  {
Semaphore187002 taskarrived;
Semaphore187002 taskstarted;
Workerproc187228 f;
void* data;
NIM_BOOL ready;
NIM_BOOL initialized;
NIM_BOOL shutdown;
Tofreequeue187226 q;
Semaphore187002 readyfortask;
};
struct  Cell54507  {
NI refcount;
TNimType* typ;
};
struct  Cellseq54523  {
NI len;
NI cap;
Cell54507** d;
};
struct  Cellset54519  {
NI counter;
NI max;
Pagedesc54515* head;
Pagedesc54515** data;
};
typedef Smallchunk36640* TY36703[512];
typedef Trunk36610* Trunkbuckets36612[256];
struct  Intset36614  {
Trunkbuckets36612 data;
};
struct  Memregion36688  {
NI minlargeobj;
NI maxlargeobj;
TY36703 freesmallchunks;
Llchunk36682* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk36642* freechunkslist;
Intset36614 chunkstarts;
Avlnode36686* root;
Avlnode36686* deleted;
Avlnode36686* last;
Avlnode36686* freeavlnodes;
};
struct  Gcstat56814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap56818  {
Gcstack56816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq54523 zct;
Cellseq54523 decstack;
Cellset54519 cycleroots;
Cellseq54523 tempstack;
NI recgclock;
Memregion36688 region;
Gcstat56814 stat;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Awaitinfo187216  {
Semaphore187002 cv;
NI idx;
};
struct  Gcthread20006  {
pthread_t sys;
};
typedef N_NIMCALL_PTR(void, TY188618) (Worker187230* m_188615);
struct  Thread188608  {
  Gcthread20006 Sup;
TY188618 datafn;
Worker187230* data;
};
typedef Thread188608 TY188621[256];
typedef Worker187230 TY188624[256];
typedef Thread188608 TY188630[32];
typedef Worker187230 TY188633[32];
typedef N_NIMCALL_PTR(void, TY189014) (Worker187230* arg_189016);
struct  Threadpoolstate185204  {
NI calls;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Gcstack56816  {
Gcstack56816* prev;
Gcstack56816* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY36619[8];
struct  Pagedesc54515  {
Pagedesc54515* next;
NI key;
TY36619 bits;
};
struct  Basechunk36638  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk36640  {
  Basechunk36638 Sup;
Smallchunk36640* next;
Smallchunk36640* prev;
Freecell36630* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk36682  {
NI size;
NI acc;
Llchunk36682* next;
};
struct  Bigchunk36642  {
  Basechunk36638 Sup;
Bigchunk36642* next;
Bigchunk36642* prev;
NI align;
NF data;
};
struct  Trunk36610  {
Trunk36610* next;
NI key;
TY36619 bits;
};
typedef Avlnode36686* TY36693[2];
struct  Avlnode36686  {
TY36693 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell36630  {
Freecell36630* next;
NI zerofield;
};
N_NIMCALL(Semaphore187002, createsemaphore_187006)(void);
static N_INLINE(void, initcond_186277)(pthread_cond_t* cond);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_28801)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, initlock_186256)(pthread_mutex_t* lock);
static N_INLINE(void, destroysemaphore_187011)(Semaphore187002* cv);
static N_INLINE(void, deinitcond_186281)(pthread_cond_t* cond);
static N_INLINE(void, deinitlock_186260)(pthread_mutex_t* lock);
N_NIMCALL(void, await_187017)(Semaphore187002* cv);
N_NIMCALL(void, acquire_186269)(pthread_mutex_t* lock);
static N_INLINE(void, wait_186285)(pthread_cond_t* cond, pthread_mutex_t* lock);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, release_186273)(pthread_mutex_t* lock);
N_NIMCALL(void, signal_187035)(Semaphore187002* cv);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, signal_186291)(pthread_cond_t* cond);
static N_INLINE(void, barrierEnter)(Barrier* b);
static N_INLINE(void, barrierLeave)(Barrier* b);
static N_INLINE(NI, atomicinc_16601)(NI* memloc, NI x);
static N_INLINE(void, openBarrier)(Barrier* b);
N_NIMCALL(void, closeBarrier)(Barrier* b);
N_NIMCALL(void, await_187272)(Flowvarbaseobj187220* fv);
N_NIMCALL(NIM_BOOL, selectworker_187277)(Worker187230* w, Workerproc187228 fn, void* data);
N_NIMCALL(void, cleanflowvars_187299)(Worker187230* w);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimGCunref)(void* p);
static N_INLINE(void, decref_60401)(Cell54507* c);
static N_INLINE(void, rtladdzct_60001)(Cell54507* c);
N_NOINLINE(void, addzct_58435)(Cellseq54523* s, Cell54507* c);
static N_INLINE(NIM_BOOL, canbecycleroot_58476)(Cell54507* c);
static N_INLINE(void, rtladdcycleroot_59220)(Cell54507* c);
N_NOINLINE(void, incl_55247)(Cellset54519* s, Cell54507* cell);
static N_INLINE(Cell54507*, usrtocell_58458)(void* usr);
N_NIMCALL(void, wakeupworkertoprocessqueue_187341)(Worker187230* w);
static N_INLINE(void, cpurelax_18001)(void);
N_NIMCALL(void, HEX3Aanonymous_187358)(void* w_187360, void* a);
N_NIMCALL(void, finished_187368)(Flowvarbaseobj187220* fv);
N_NOINLINE(void, raiseassert_97093)(NimStringDesc* msg);
N_NIMCALL(void, nimFlowVarCreateSemaphore)(Flowvarbaseobj187220* fv);
N_NIMCALL(void, nimFlowVarSignal)(Flowvarbaseobj187220* fv);
N_NIMCALL(NI, awaitany_187507)(Flowvarbaseobj187220** flowvars, NI flowvarsLen0);
N_NIMCALL(NIM_BOOL, isready_187597)(Flowvarbaseobj187220* fv);
N_NIMCALL(void, nimArgsPassingDone)(void* p);
N_NIMCALL(void, slave_187623)(Worker187230* w);
N_NIMCALL(void, failedassertimpl_97116)(NimStringDesc* msg);
static N_INLINE(NI, atomicdec_16606)(NI* memloc, NI x);
N_NIMCALL(void, distinguishedslave_188203)(Worker187230* w);
N_NIMCALL(void, setminpoolsize_188801)(NI size);
N_NIMCALL(void, setmaxpoolsize_188805)(NI size);
N_NIMCALL(void, createthread_189007)(Thread188608* t, TY189014 tp, Worker187230* param);
N_NOCONV(void*, threadprocwrapper_189406)(void* closure);
N_NIMCALL(void, threadprocwrapstackframe_189605)(Thread188608* thrd);
N_NIMCALL(void, threadprocwrapdispatch_189809)(Thread188608* thrd);
N_NOINLINE(void, activateworkerthread_189001)(NI i);
N_NOINLINE(void, activatedistinguishedthread_191201)(NI i);
N_NIMCALL(void, setup_191222)(void);
N_NIMCALL(NI, ncpicountProcessors)(void);
N_NIMCALL(NIM_BOOL, preferspawn_191432)(void);
N_NIMCALL(void, nimSpawn3)(Workerproc187228 fn, void* data);
N_NIMCALL(NIM_BOOL, tryacquire_186264)(pthread_mutex_t* lock);
N_NIMCALL(NU8, advice_185209)(Threadpoolstate185204* s);
N_NIMCALL(void, nimSpawn4)(Workerproc187228 fn, void* data, NI id);
N_NIMCALL(void, sync_191624)(void);
STRING_LITERAL(TMP593, "isNil(fv.ai) flowVar is still attached to an \'awaitAny\'", 55);
STRING_LITERAL(TMP599, "not w.ready ", 12);
extern NIM_THREADVAR TFrame* frameptr_26036;
extern NIM_THREADVAR Gcheap56818 gch_56859;
NI currentpoolsize_187615;
NI maxpoolsize_187616;
NI minpoolsize_187617;
Semaphore187002 gsomeready_187618;
Worker187230* readyworker_187620;
TY188621 workers_188622;
TY188624 workersdata_188625;
TY188630 distinguished_188631;
TY188633 distinguisheddata_188634;
Threadpoolstate185204 state_191448;
pthread_mutex_t statelock_191449;
pthread_mutex_t distinguishedlock_191611;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_26036 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_26036).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_26036;
	frameptr_26036 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_28801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_26036 = (*frameptr_26036).prev;
}

static N_INLINE(void, initcond_186277)(pthread_cond_t* cond) {
	nimfr("initCond", "locks.nim")
	nimln(44, "locks.nim");
	pthread_cond_init(cond, NIM_NIL);
	popFrame();
}

static N_INLINE(void, initlock_186256)(pthread_mutex_t* lock) {
	nimfr("initLock", "locks.nim")
	nimln(23, "locks.nim");
	pthread_mutex_init(lock, NIM_NIL);
	popFrame();
}

N_NIMCALL(Semaphore187002, createsemaphore_187006)(void) {
	Semaphore187002 result;
	memset((void*)(&result), 0, sizeof(result));
	initcond_186277((&result.c));
	initlock_186256((&result.L));
	return result;
}

static N_INLINE(void, deinitcond_186281)(pthread_cond_t* cond) {
	nimfr("deinitCond", "locks.nim")
	nimln(48, "locks.nim");
	pthread_cond_destroy(cond);
	popFrame();
}

static N_INLINE(void, deinitlock_186260)(pthread_mutex_t* lock) {
	nimfr("deinitLock", "locks.nim")
	nimln(27, "locks.nim");
	pthread_mutex_destroy(lock);
	popFrame();
}

static N_INLINE(void, destroysemaphore_187011)(Semaphore187002* cv) {
	deinitcond_186281((&(*cv).c));
	deinitlock_186260((&(*cv).L));
}

static N_INLINE(void, wait_186285)(pthread_cond_t* cond, pthread_mutex_t* lock) {
	nimfr("wait", "locks.nim")
	nimln(52, "locks.nim");
	pthread_cond_wait(cond, lock);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, await_187017)(Semaphore187002* cv) {
	NI TMP589;
	acquire_186269((&(*cv).L));
	{
		while (1) {
			if (!((*cv).counter <= ((NI) 0))) goto LA2;
			wait_186285((&(*cv).c), (&(*cv).L));
		} LA2: ;
	}
	TMP589 = subInt((*cv).counter, ((NI) 1));
	(*cv).counter = (NI)(TMP589);
	release_186273((&(*cv).L));
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, signal_186291)(pthread_cond_t* cond) {
	nimfr("signal", "locks.nim")
	nimln(56, "locks.nim");
	pthread_cond_signal(cond);
	popFrame();
}

N_NIMCALL(void, signal_187035)(Semaphore187002* cv) {
	NI TMP590;
	acquire_186269((&(*cv).L));
	TMP590 = addInt((*cv).counter, ((NI) 1));
	(*cv).counter = (NI)(TMP590);
	release_186273((&(*cv).L));
	signal_186291((&(*cv).c));
}

static N_INLINE(void, barrierEnter)(Barrier* b) {
	NI TMP591;
	TMP591 = addInt((*b).entered, ((NI) 1));
	(*b).entered = (NI)(TMP591);
}

static N_INLINE(NI, atomicinc_16601)(NI* memloc, NI x) {
	NI result;
	result = 0;
	result = __atomic_add_fetch(memloc, x, __ATOMIC_RELAXED);
	return result;
}

static N_INLINE(void, barrierLeave)(Barrier* b) {
	NI LOC1;
	LOC1 = 0;
	LOC1 = atomicinc_16601((&(*b).left), ((NI) 1));
	__atomic_thread_fence(__ATOMIC_SEQ_CST);
	{
		NIM_BOOL LOC4;
		LOC4 = 0;
		LOC4 = (*b).interest;
		if (!(LOC4)) goto LA5;
		LOC4 = ((*b).entered <= (*b).left);
		LA5: ;
		if (!LOC4) goto LA6;
		signal_187035((&(*b).cv));
	}
	LA6: ;
}

static N_INLINE(void, openBarrier)(Barrier* b) {
	(*b).entered = ((NI) 0);
	(*b).left = ((NI) 0);
	(*b).interest = NIM_FALSE;
}

N_NIMCALL(void, closeBarrier)(Barrier* b) {
	__atomic_thread_fence(__ATOMIC_SEQ_CST);
	{
		if (!!(((*b).left == (*b).entered))) goto LA3;
		(*b).cv = createsemaphore_187006();
		__atomic_thread_fence(__ATOMIC_SEQ_CST);
		(*b).interest = NIM_TRUE;
		__atomic_thread_fence(__ATOMIC_SEQ_CST);
		{
			while (1) {
				if (!!(((*b).left == (*b).entered))) goto LA6;
				await_187017((&(*b).cv));
			} LA6: ;
		}
		destroysemaphore_187011((&(*b).cv));
	}
	LA3: ;
}

N_NIMCALL(void, await_187272)(Flowvarbaseobj187220* fv) {
	nimfr("await", "threadpool.nim")
	nimln(136, "threadpool.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (*fv).usessemaphore;
		if (!(LOC3)) goto LA4;
		LOC3 = !((*fv).awaited);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(137, "threadpool.nim");
		(*fv).awaited = NIM_TRUE;
		nimln(138, "threadpool.nim");
		await_187017((&(*fv).cv));
		nimln(139, "threadpool.nim");
		destroysemaphore_187011((&(*fv).cv));
	}
	LA5: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, selectworker_187277)(Worker187230* w, Workerproc187228 fn, void* data) {
	NIM_BOOL result;
	nimfr("selectWorker", "threadpool.nim")
	result = 0;
	nimln(142, "threadpool.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = __sync_bool_compare_and_swap((&(*w).ready), NIM_TRUE, NIM_FALSE);
		if (!LOC3) goto LA4;
		nimln(143, "threadpool.nim");
		(*w).data = data;
		nimln(144, "threadpool.nim");
		(*w).f = fn;
		nimln(145, "threadpool.nim");
		signal_187035((&(*w).taskarrived));
		nimln(146, "threadpool.nim");
		await_187017((&(*w).taskstarted));
		nimln(147, "threadpool.nim");
		result = NIM_TRUE;
	}
	LA4: ;
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_60001)(Cell54507* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_58435((&gch_56859.zct), c);
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_58476)(Cell54507* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1U<<((NU)(((NU8) 1))&7U)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_59220)(Cell54507* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_55247((&gch_56859.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, decref_60401)(Cell54507* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_60001(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_58476(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_59220(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(Cell54507*, usrtocell_58458)(void* usr) {
	Cell54507* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell54507*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell54507))))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunref)(void* p) {
	Cell54507* LOC1;
	nimfr("nimGCunref", "gc.nim")
	nimln(236, "gc.nim");
	LOC1 = 0;
	LOC1 = usrtocell_58458(p);
	decref_60401(LOC1);
	popFrame();
}

N_NIMCALL(void, cleanflowvars_187299)(Worker187230* w) {
	Tofreequeue187226* q;
	nimfr("cleanFlowVars", "threadpool.nim")
	nimln(150, "threadpool.nim");
	q = (&(*w).q);
	nimln(151, "threadpool.nim");
	acquire_186269((&(*q).lock));
	{
		NI i_187323;
		NI HEX3Atmp_187334;
		NI res_187337;
		i_187323 = 0;
		HEX3Atmp_187334 = 0;
		nimln(152, "threadpool.nim");
		HEX3Atmp_187334 = subInt((*q).len, 1);
		nimln(1874, "system.nim");
		res_187337 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP592;
				if (!(res_187337 <= HEX3Atmp_187334)) goto LA3;
				nimln(1876, "system.nim");
				i_187323 = res_187337;
				nimln(153, "threadpool.nim");
				if ((NU)(i_187323) > (NU)(127)) raiseIndexError();
				nimGCunref(((TNimObject*) ((*q).data[(i_187323)- 0])));
				nimln(1895, "system.nim");
				TMP592 = addInt(res_187337, ((NI) 1));
				res_187337 = (NI)(TMP592);
			} LA3: ;
		}
	}
	nimln(155, "threadpool.nim");
	(*q).len = ((NI) 0);
	nimln(156, "threadpool.nim");
	release_186273((&(*q).lock));
	popFrame();
}

static N_INLINE(void, cpurelax_18001)(void) {
	asm volatile("pause" ::: "memory");
}

N_NIMCALL(void, HEX3Aanonymous_187358)(void* w_187360, void* a) {
	Worker187230* w;
	nimfr(":anonymous", "threadpool.nim")
	nimln(166, "threadpool.nim");
	w = ((Worker187230*) (w_187360));
	nimln(167, "threadpool.nim");
	cleanflowvars_187299(w);
	nimln(168, "threadpool.nim");
	signal_187035((&(*w).q.empty));
	popFrame();
}

N_NIMCALL(void, wakeupworkertoprocessqueue_187341)(Worker187230* w) {
	nimfr("wakeupWorkerToProcessQueue", "threadpool.nim")
	{
		nimln(161, "threadpool.nim");
		while (1) {
			NIM_BOOL LOC3;
			LOC3 = 0;
			LOC3 = __sync_bool_compare_and_swap((&(*w).ready), NIM_TRUE, NIM_FALSE);
			if (!!(LOC3)) goto LA2;
			nimln(162, "threadpool.nim");
			cpurelax_18001();
		} LA2: ;
	}
	nimln(164, "threadpool.nim");
	(*w).data = NIM_NIL;
	nimln(165, "threadpool.nim");
	(*w).f = HEX3Aanonymous_187358;
	nimln(169, "threadpool.nim");
	signal_187035((&(*w).taskarrived));
	popFrame();
}

N_NIMCALL(void, finished_187368)(Flowvarbaseobj187220* fv) {
	Worker187230* owner;
	Tofreequeue187226* q;
	NI TMP594;
	nimfr("finished", "threadpool.nim")
{	nimln(172, "threadpool.nim");
	{
		if (!!((*fv).ai == 0)) goto LA3;
		raiseassert_97093(((NimStringDesc*) &TMP593));
	}
	LA3: ;
	nimln(176, "threadpool.nim");
	await_187272(fv);
	nimln(177, "threadpool.nim");
	{
		if (!(*fv).data == 0) goto LA7;
		goto BeforeRet;
	}
	LA7: ;
	nimln(178, "threadpool.nim");
	owner = ((Worker187230*) ((*fv).owner));
	nimln(179, "threadpool.nim");
	q = (&(*owner).q);
	nimln(180, "threadpool.nim");
	acquire_186269((&(*q).lock));
	{
		nimln(181, "threadpool.nim");
		while (1) {
			if (!!(((*q).len < ((NI) 128)))) goto LA10;
			nimln(183, "threadpool.nim");
			release_186273((&(*q).lock));
			nimln(184, "threadpool.nim");
			wakeupworkertoprocessqueue_187341(owner);
			nimln(185, "threadpool.nim");
			await_187017((&(*q).empty));
			nimln(186, "threadpool.nim");
			acquire_186269((&(*q).lock));
		} LA10: ;
	}
	nimln(187, "threadpool.nim");
	if ((NU)((*q).len) > (NU)(127)) raiseIndexError();
	(*q).data[((*q).len)- 0] = ((void*) ((*fv).data));
	nimln(188, "threadpool.nim");
	TMP594 = addInt((*q).len, ((NI) 1));
	(*q).len = (NI)(TMP594);
	nimln(189, "threadpool.nim");
	release_186273((&(*q).lock));
	nimln(190, "threadpool.nim");
	(*fv).data = NIM_NIL;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, nimFlowVarCreateSemaphore)(Flowvarbaseobj187220* fv) {
	nimfr("nimFlowVarCreateSemaphore", "threadpool.nim")
	nimln(198, "threadpool.nim");
	(*fv).cv = createsemaphore_187006();
	nimln(199, "threadpool.nim");
	(*fv).usessemaphore = NIM_TRUE;
	popFrame();
}

N_NIMCALL(void, nimFlowVarSignal)(Flowvarbaseobj187220* fv) {
	nimfr("nimFlowVarSignal", "threadpool.nim")
	nimln(202, "threadpool.nim");
	{
		NI TMP595;
		nimln(349, "system.nim");
		if (!!(((*fv).ai == NIM_NIL))) goto LA3;
		nimln(203, "threadpool.nim");
		acquire_186269((&(*(*fv).ai).cv.L));
		nimln(204, "threadpool.nim");
		(*(*fv).ai).idx = (*fv).idx;
		nimln(205, "threadpool.nim");
		TMP595 = addInt((*(*fv).ai).cv.counter, ((NI) 1));
		(*(*fv).ai).cv.counter = (NI)(TMP595);
		nimln(206, "threadpool.nim");
		release_186273((&(*(*fv).ai).cv.L));
		nimln(207, "threadpool.nim");
		signal_186291((&(*(*fv).ai).cv.c));
	}
	LA3: ;
	nimln(208, "threadpool.nim");
	{
		if (!(*fv).usessemaphore) goto LA7;
		nimln(209, "threadpool.nim");
		signal_187035((&(*fv).cv));
	}
	LA7: ;
	popFrame();
}

N_NIMCALL(NI, awaitany_187507)(Flowvarbaseobj187220** flowvars, NI flowvarsLen0) {
	NI result;
	Awaitinfo187216 ai;
	NI conflicts;
	nimfr("awaitAny", "threadpool.nim")
	result = 0;
	memset((void*)(&ai), 0, sizeof(ai));
	nimln(254, "threadpool.nim");
	ai.cv = createsemaphore_187006();
	nimln(255, "threadpool.nim");
	conflicts = ((NI) 0);
	{
		NI i_187523;
		NI HEX3Atmp_187582;
		NI res_187585;
		i_187523 = 0;
		HEX3Atmp_187582 = 0;
		nimln(256, "threadpool.nim");
		HEX3Atmp_187582 = (flowvarsLen0-1);
		nimln(1874, "system.nim");
		res_187585 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP597;
				if (!(res_187585 <= HEX3Atmp_187582)) goto LA3;
				nimln(1876, "system.nim");
				i_187523 = res_187585;
				nimln(257, "threadpool.nim");
				{
					NIM_BOOL LOC6;
					if ((NU)(i_187523) >= (NU)(flowvarsLen0)) raiseIndexError();
					LOC6 = 0;
					LOC6 = __sync_bool_compare_and_swap(&(*flowvars[i_187523]).ai, NIM_NIL, (&ai));
					if (!LOC6) goto LA7;
					nimln(258, "threadpool.nim");
					if ((NU)(i_187523) >= (NU)(flowvarsLen0)) raiseIndexError();
					(*flowvars[i_187523]).idx = i_187523;
				}
				goto LA4;
				LA7: ;
				{
					NI TMP596;
					nimln(260, "threadpool.nim");
					TMP596 = addInt(conflicts, ((NI) 1));
					conflicts = (NI)(TMP596);
				}
				LA4: ;
				nimln(1895, "system.nim");
				TMP597 = addInt(res_187585, ((NI) 1));
				res_187585 = (NI)(TMP597);
			} LA3: ;
		}
	}
	nimln(261, "threadpool.nim");
	{
		if (!(conflicts < flowvarsLen0)) goto LA12;
		nimln(262, "threadpool.nim");
		await_187017((&ai.cv));
		nimln(263, "threadpool.nim");
		result = ai.idx;
		{
			NI i_187564;
			NI HEX3Atmp_187590;
			NI res_187593;
			i_187564 = 0;
			HEX3Atmp_187590 = 0;
			nimln(264, "threadpool.nim");
			HEX3Atmp_187590 = (flowvarsLen0-1);
			nimln(1874, "system.nim");
			res_187593 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					NIM_BOOL LOC17;
					NI TMP598;
					if (!(res_187593 <= HEX3Atmp_187590)) goto LA16;
					nimln(1876, "system.nim");
					i_187564 = res_187593;
					nimln(265, "threadpool.nim");
					if ((NU)(i_187564) >= (NU)(flowvarsLen0)) raiseIndexError();
					LOC17 = 0;
					LOC17 = __sync_bool_compare_and_swap(&(*flowvars[i_187564]).ai, (&ai), NIM_NIL);
					nimln(1895, "system.nim");
					TMP598 = addInt(res_187593, ((NI) 1));
					res_187593 = (NI)(TMP598);
				} LA16: ;
			}
		}
	}
	goto LA10;
	LA12: ;
	{
		nimln(267, "threadpool.nim");
		result = ((NI) -1);
	}
	LA10: ;
	nimln(268, "threadpool.nim");
	destroysemaphore_187011((&ai.cv));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isready_187597)(Flowvarbaseobj187220* fv) {
	NIM_BOOL result;
	nimfr("isReady", "threadpool.nim")
	result = 0;
	nimln(274, "threadpool.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (*fv).usessemaphore;
		if (!(LOC3)) goto LA4;
		LOC3 = !((*fv).awaited);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(275, "threadpool.nim");
		acquire_186269((&(*fv).cv.L));
		nimln(276, "threadpool.nim");
		nimln(357, "system.nim");
		result = (((NI) 0) < (*fv).cv.counter);
		nimln(277, "threadpool.nim");
		release_186273((&(*fv).cv.L));
	}
	goto LA1;
	LA5: ;
	{
		nimln(279, "threadpool.nim");
		result = NIM_TRUE;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nimArgsPassingDone)(void* p) {
	Worker187230* w;
	nimfr("nimArgsPassingDone", "threadpool.nim")
	nimln(282, "threadpool.nim");
	w = ((Worker187230*) (p));
	nimln(283, "threadpool.nim");
	signal_187035((&(*w).taskstarted));
	popFrame();
}

static N_INLINE(NI, atomicdec_16606)(NI* memloc, NI x) {
	NI result;
	result = 0;
	result = __atomic_sub_fetch(memloc, x, __ATOMIC_RELAXED);
	return result;
}

N_NIMCALL(void, slave_187623)(Worker187230* w) {
	nimfr("slave", "threadpool.nim")
	{
		nimln(301, "threadpool.nim");
		while (1) {
			nimln(303, "threadpool.nim");
			__atomic_store_n((&(*w).ready), NIM_TRUE, __ATOMIC_SEQ_CST);
			nimln(306, "threadpool.nim");
			readyworker_187620 = w;
			nimln(307, "threadpool.nim");
			signal_187035((&gsomeready_187618));
			nimln(308, "threadpool.nim");
			await_187017((&(*w).taskarrived));
			nimln(311, "threadpool.nim");
			{
				if (!!(!((*w).ready))) goto LA5;
				failedassertimpl_97116(((NimStringDesc*) &TMP599));
			}
			LA5: ;
			nimln(312, "threadpool.nim");
			(*w).f(((void*) (w)), (*w).data);
			nimln(313, "threadpool.nim");
			{
				nimln(349, "system.nim");
				if (!!(((*w).q.len == ((NI) 0)))) goto LA9;
				nimln(313, "threadpool.nim");
				cleanflowvars_187299(w);
			}
			LA9: ;
			nimln(314, "threadpool.nim");
			{
				NI LOC15;
				if (!(*w).shutdown) goto LA13;
				nimln(315, "threadpool.nim");
				(*w).shutdown = NIM_FALSE;
				nimln(316, "threadpool.nim");
				LOC15 = 0;
				LOC15 = atomicdec_16606((&currentpoolsize_187615), ((NI) 1));
			}
			LA13: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, distinguishedslave_188203)(Worker187230* w) {
	nimfr("distinguishedSlave", "threadpool.nim")
	{
		nimln(319, "threadpool.nim");
		while (1) {
			nimln(321, "threadpool.nim");
			__atomic_store_n((&(*w).ready), NIM_TRUE, __ATOMIC_SEQ_CST);
			nimln(324, "threadpool.nim");
			signal_187035((&(*w).readyfortask));
			nimln(325, "threadpool.nim");
			await_187017((&(*w).taskarrived));
			nimln(326, "threadpool.nim");
			{
				if (!!(!((*w).ready))) goto LA5;
				failedassertimpl_97116(((NimStringDesc*) &TMP599));
			}
			LA5: ;
			nimln(327, "threadpool.nim");
			(*w).f(((void*) (w)), (*w).data);
			nimln(328, "threadpool.nim");
			{
				nimln(349, "system.nim");
				if (!!(((*w).q.len == ((NI) 0)))) goto LA9;
				nimln(328, "threadpool.nim");
				cleanflowvars_187299(w);
			}
			LA9: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, setminpoolsize_188801)(NI size) {
	nimfr("setMinPoolSize", "threadpool.nim")
	nimln(342, "threadpool.nim");
	minpoolsize_187617 = ((NI) (size));
	popFrame();
}

N_NIMCALL(void, setmaxpoolsize_188805)(NI size) {
	nimfr("setMaxPoolSize", "threadpool.nim")
	nimln(347, "threadpool.nim");
	maxpoolsize_187616 = ((NI) (size));
	nimln(348, "threadpool.nim");
	{
		nimln(357, "system.nim");
		if (!(maxpoolsize_187616 < currentpoolsize_187615)) goto LA3;
		{
			NI i_188818;
			NI HEX3Atmp_188822;
			NI TMP600;
			NI res_188825;
			i_188818 = 0;
			HEX3Atmp_188822 = 0;
			nimln(349, "threadpool.nim");
			TMP600 = subInt(currentpoolsize_187615, ((NI) 1));
			HEX3Atmp_188822 = (NI)(TMP600);
			nimln(1874, "system.nim");
			res_188825 = maxpoolsize_187616;
			{
				nimln(1875, "system.nim");
				while (1) {
					Worker187230* w;
					NI TMP601;
					if (!(res_188825 <= HEX3Atmp_188822)) goto LA7;
					nimln(1876, "system.nim");
					i_188818 = res_188825;
					nimln(350, "threadpool.nim");
					if ((NU)(i_188818) > (NU)(255)) raiseIndexError();
					w = (&workersdata_188625[(i_188818)- 0]);
					nimln(351, "threadpool.nim");
					(*w).shutdown = NIM_TRUE;
					nimln(1895, "system.nim");
					TMP601 = addInt(res_188825, ((NI) 1));
					res_188825 = (NI)(TMP601);
				} LA7: ;
			}
		}
	}
	LA3: ;
	popFrame();
}

N_NOINLINE(void, activateworkerthread_189001)(NI i) {
	nimfr("activateWorkerThread", "threadpool.nim")
	nimln(357, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	workersdata_188625[(i)- 0].taskarrived = createsemaphore_187006();
	nimln(358, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	workersdata_188625[(i)- 0].taskstarted = createsemaphore_187006();
	nimln(359, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	workersdata_188625[(i)- 0].initialized = NIM_TRUE;
	nimln(360, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	workersdata_188625[(i)- 0].q.empty = createsemaphore_187006();
	nimln(361, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	initlock_186256((&workersdata_188625[(i)- 0].q.lock));
	nimln(362, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	createthread_189007((&workers_188622[(i)- 0]), slave_187623, (&workersdata_188625[(i)- 0]));
	popFrame();
}

N_NOINLINE(void, activatedistinguishedthread_191201)(NI i) {
	nimfr("activateDistinguishedThread", "threadpool.nim")
	nimln(369, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	distinguisheddata_188634[(i)- 0].taskarrived = createsemaphore_187006();
	nimln(370, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	distinguisheddata_188634[(i)- 0].taskstarted = createsemaphore_187006();
	nimln(371, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	distinguisheddata_188634[(i)- 0].initialized = NIM_TRUE;
	nimln(372, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	distinguisheddata_188634[(i)- 0].q.empty = createsemaphore_187006();
	nimln(373, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	initlock_186256((&distinguisheddata_188634[(i)- 0].q.lock));
	nimln(374, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	distinguisheddata_188634[(i)- 0].readyfortask = createsemaphore_187006();
	nimln(375, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	createthread_189007((&distinguished_188631[(i)- 0]), distinguishedslave_188203, (&distinguisheddata_188634[(i)- 0]));
	popFrame();
}

N_NIMCALL(void, setup_191222)(void) {
	NI p;
	nimfr("setup", "threadpool.nim")
	nimln(378, "threadpool.nim");
	p = ncpicountProcessors();
	nimln(381, "threadpool.nim");
	currentpoolsize_187615 = ((p <= ((NI) 256)) ? p : ((NI) 256));
	nimln(382, "threadpool.nim");
	readyworker_187620 = (&workersdata_188625[(((NI) 0))- 0]);
	{
		NI i_191423;
		NI HEX3Atmp_191425;
		NI res_191428;
		i_191423 = 0;
		HEX3Atmp_191425 = 0;
		nimln(383, "threadpool.nim");
		HEX3Atmp_191425 = subInt(currentpoolsize_187615, 1);
		nimln(1874, "system.nim");
		res_191428 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP602;
				if (!(res_191428 <= HEX3Atmp_191425)) goto LA3;
				nimln(1876, "system.nim");
				i_191423 = res_191428;
				nimln(383, "threadpool.nim");
				activateworkerthread_189001(i_191423);
				nimln(1895, "system.nim");
				TMP602 = addInt(res_191428, ((NI) 1));
				res_191428 = (NI)(TMP602);
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(NIM_BOOL, preferspawn_191432)(void) {
	NIM_BOOL result;
	nimfr("preferSpawn", "threadpool.nim")
	result = 0;
	nimln(389, "threadpool.nim");
	nimln(357, "system.nim");
	result = (((NI) 0) < gsomeready_187618.counter);
	popFrame();
	return result;
}

N_NIMCALL(void, nimSpawn3)(Workerproc187228 fn, void* data) {
	nimfr("nimSpawn3", "threadpool.nim")
{	{
		nimln(426, "threadpool.nim");
		while (1) {
			nimln(427, "threadpool.nim");
			{
				NIM_BOOL LOC5;
				LOC5 = 0;
				LOC5 = selectworker_187277(readyworker_187620, fn, data);
				if (!LOC5) goto LA6;
				goto BeforeRet;
			}
			LA6: ;
			{
				NI i_191474;
				NI HEX3Atmp_191604;
				NI res_191607;
				i_191474 = 0;
				HEX3Atmp_191604 = 0;
				nimln(428, "threadpool.nim");
				HEX3Atmp_191604 = subInt(currentpoolsize_187615, 1);
				nimln(1874, "system.nim");
				res_191607 = ((NI) 0);
				{
					nimln(1875, "system.nim");
					while (1) {
						NI TMP603;
						if (!(res_191607 <= HEX3Atmp_191604)) goto LA10;
						nimln(1876, "system.nim");
						i_191474 = res_191607;
						nimln(429, "threadpool.nim");
						{
							NIM_BOOL LOC13;
							if ((NU)(i_191474) > (NU)(255)) raiseIndexError();
							LOC13 = 0;
							LOC13 = selectworker_187277((&workersdata_188625[(i_191474)- 0]), fn, data);
							if (!LOC13) goto LA14;
							goto BeforeRet;
						}
						LA14: ;
						nimln(1895, "system.nim");
						TMP603 = addInt(res_191607, ((NI) 1));
						res_191607 = (NI)(TMP603);
					} LA10: ;
				}
			}
			nimln(433, "threadpool.nim");
			{
				NIM_BOOL LOC18;
				LOC18 = 0;
				LOC18 = (state_191448.calls < maxpoolsize_187616);
				if (LOC18) goto LA19;
				LOC18 = (((NI) ((NI)(state_191448.calls & ((NI) 127)))) == ((NI) 0));
				LA19: ;
				if (!LOC18) goto LA20;
				nimln(435, "threadpool.nim");
				{
					NIM_BOOL LOC24;
					NU8 LOC27;
					LOC24 = 0;
					LOC24 = tryacquire_186264((&statelock_191449));
					if (!LOC24) goto LA25;
					nimln(436, "threadpool.nim");
					LOC27 = 0;
					LOC27 = advice_185209((&state_191448));
					switch (LOC27) {
					case ((NU8) 0):
					{
					}
					break;
					case ((NU8) 1):
					{
						nimln(439, "threadpool.nim");
						{
							Worker187230* w;
							NI LOC38;
							if (!(currentpoolsize_187615 < maxpoolsize_187616)) goto LA32;
							nimln(440, "threadpool.nim");
							{
								if ((NU)(currentpoolsize_187615) > (NU)(255)) raiseIndexError();
								if (!!(workersdata_188625[(currentpoolsize_187615)- 0].initialized)) goto LA36;
								nimln(441, "threadpool.nim");
								activateworkerthread_189001(currentpoolsize_187615);
							}
							LA36: ;
							nimln(442, "threadpool.nim");
							if ((NU)(currentpoolsize_187615) > (NU)(255)) raiseIndexError();
							w = (&workersdata_188625[(currentpoolsize_187615)- 0]);
							nimln(443, "threadpool.nim");
							LOC38 = 0;
							LOC38 = atomicinc_16601((&currentpoolsize_187615), ((NI) 1));
							nimln(444, "threadpool.nim");
							{
								NIM_BOOL LOC41;
								LOC41 = 0;
								LOC41 = selectworker_187277(w, fn, data);
								if (!LOC41) goto LA42;
								nimln(445, "threadpool.nim");
								release_186273((&statelock_191449));
								nimln(446, "threadpool.nim");
								goto BeforeRet;
							}
							LA42: ;
						}
						LA32: ;
					}
					break;
					case ((NU8) 2):
					{
						nimln(449, "threadpool.nim");
						{
							Worker187230* w;
							NI TMP604;
							nimln(357, "system.nim");
							if (!(minpoolsize_187617 < currentpoolsize_187615)) goto LA47;
							nimln(450, "threadpool.nim");
							TMP604 = subInt(currentpoolsize_187615, ((NI) 1));
							if ((NU)((NI)(TMP604)) > (NU)(255)) raiseIndexError();
							w = (&workersdata_188625[((NI)(TMP604))- 0]);
							nimln(451, "threadpool.nim");
							(*w).shutdown = NIM_TRUE;
						}
						LA47: ;
					}
					break;
					}
					nimln(453, "threadpool.nim");
					release_186273((&statelock_191449));
				}
				LA25: ;
			}
			LA20: ;
			nimln(468, "threadpool.nim");
			await_187017((&gsomeready_187618));
		}
	}
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, nimSpawn4)(Workerproc187228 fn, void* data, NI id) {
	nimfr("nimSpawn4", "threadpool.nim")
	nimln(476, "threadpool.nim");
	acquire_186269((&distinguishedlock_191611));
	nimln(477, "threadpool.nim");
	{
		if (!!(distinguisheddata_188634[(id)- 0].initialized)) goto LA3;
		nimln(478, "threadpool.nim");
		activatedistinguishedthread_191201(((NI) (id)));
	}
	LA3: ;
	nimln(479, "threadpool.nim");
	release_186273((&distinguishedlock_191611));
	{
		nimln(480, "threadpool.nim");
		while (1) {
			nimln(481, "threadpool.nim");
			{
				NIM_BOOL LOC9;
				LOC9 = 0;
				LOC9 = selectworker_187277((&distinguisheddata_188634[(id)- 0]), fn, data);
				if (!LOC9) goto LA10;
				goto LA5;
			}
			LA10: ;
			nimln(482, "threadpool.nim");
			await_187017((&distinguisheddata_188634[(id)- 0].readyfortask));
		}
	} LA5: ;
	popFrame();
}

N_NIMCALL(void, sync_191624)(void) {
	nimfr("sync", "threadpool.nim")
	{
		nimln(488, "threadpool.nim");
		while (1) {
			NIM_BOOL allready;
			nimln(489, "threadpool.nim");
			allready = NIM_TRUE;
			{
				NI i_191644;
				NI HEX3Atmp_191648;
				NI res_191651;
				i_191644 = 0;
				HEX3Atmp_191648 = 0;
				nimln(490, "threadpool.nim");
				HEX3Atmp_191648 = subInt(currentpoolsize_187615, 1);
				nimln(1874, "system.nim");
				res_191651 = ((NI) 0);
				{
					nimln(1875, "system.nim");
					while (1) {
						NIM_BOOL LOC10;
						NI TMP605;
						if (!(res_191651 <= HEX3Atmp_191648)) goto LA5;
						nimln(1876, "system.nim");
						i_191644 = res_191651;
						nimln(491, "threadpool.nim");
						{
							if (!!(allready)) goto LA8;
							goto LA3;
						}
						LA8: ;
						nimln(492, "threadpool.nim");
						LOC10 = 0;
						LOC10 = allready;
						if (!(LOC10)) goto LA11;
						if ((NU)(i_191644) > (NU)(255)) raiseIndexError();
						LOC10 = workersdata_188625[(i_191644)- 0].ready;
						LA11: ;
						allready = LOC10;
						nimln(1895, "system.nim");
						TMP605 = addInt(res_191651, ((NI) 1));
						res_191651 = (NI)(TMP605);
					} LA5: ;
				}
			} LA3: ;
			nimln(493, "threadpool.nim");
			{
				if (!allready) goto LA14;
				goto LA1;
			}
			LA14: ;
			nimln(494, "threadpool.nim");
			await_187017((&gsomeready_187618));
		}
	} LA1: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolInit000)(void) {
	nimfr("threadpool", "threadpool.nim")
	nimln(295, "threadpool.nim");
	maxpoolsize_187616 = ((NI) 256);
	nimln(296, "threadpool.nim");
	minpoolsize_187617 = ((NI) 4);
	nimln(297, "threadpool.nim");
	gsomeready_187618 = createsemaphore_187006();
	nimln(422, "threadpool.nim");
	initlock_186256((&statelock_191449));
	nimln(473, "threadpool.nim");
	initlock_186256((&distinguishedlock_191611));
	nimln(496, "threadpool.nim");
	setup_191222();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolDatInit000)(void) {
}

