/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/stdlib_net.o /home/cyril/Projects/provider/nimcache/stdlib_net.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <errno.h>
#include <netdb.h>
typedef struct Socketimpl140404 Socketimpl140404;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR TY140418[4001];
struct  Socketimpl140404  {
int fd;
NIM_BOOL isbuffered;
union{
struct {TY140418 buffer;
NI currpos;
NI buflen;
} S1;
} isbufferedU;
NI32 lasterror;
NU8 domain;
NU8 socktype;
NU8 protocol;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NIM_CHAR TY109852[256];
N_NIMCALL(NI, send_144677)(Socketimpl140404* socket, void* data, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI32, oslasterror_119819)(void);
N_NIMCALL(NIM_BOOL, isdisconnectionerror_140473)(NU8 flags, NI32 lasterror);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, socketerror_140467)(Socketimpl140404* socket, NI err, NIM_BOOL async, NI32 lasterror);
N_NIMCALL(NI32, getsocketerror_141001)(Socketimpl140404* socket);
N_NOINLINE(void, raiseoserror_119803)(NI32 errorcode, NimStringDesc* additionalinfo);
N_NIMCALL(int, newnativesocket_135001)(NU8 domain, NU8 socktype, NU8 protocol);
N_NIMCALL(Socketimpl140404*, newsocket_140674)(int fd, NU8 domain, NU8 socktype, NU8 protocol, NIM_BOOL buffered);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
N_NIMCALL(void, TMP990)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, FieldDiscriminantCheck)(NI olddiscval, NI newdiscval, TNimNode** a, NI L);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NIMCALL(struct addrinfo*, getaddrinfo_135402)(NimStringDesc* address, NU16 port, NU8 domain, NU8 socktype, NU8 protocol);
N_NIMCALL(void, dealloc_135802)(struct addrinfo* ai);
STRING_LITERAL(TMP830, "No valid socket error code available", 36);
STRING_LITERAL(TMP831, "", 0);
STRING_LITERAL(TMP832, "Could not send all data.", 24);
STRING_LITERAL(TMP978, "\012  not (fd == osInvalidSocket) ", 31);
TNimNode* NimDT_140404_isbuffered[3];
STRING_LITERAL(TMP991, "currPos", 7);
extern TFrame* frameptr_19436;
extern int osinvalidsocket_134645;
TNimType NTI140404; /* SocketImpl */
extern TNimType NTI7208; /* cint */
extern TNimType NTI130; /* bool */
extern TNimType NTI136; /* char */
TNimType NTI140418; /* array[0..4000, char] */
extern TNimType NTI104; /* int */
extern TNimType NTI110; /* int32 */
extern TNimType NTI134604; /* Domain */
extern TNimType NTI134606; /* SockType */
extern TNimType NTI134608; /* Protocol */
TNimType NTI140406; /* Socket */
extern TNimNode* NimDT_140404_isbuffered[3];

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(NI, send_144677)(Socketimpl140404* socket, void* data, NI size) {
	NI result;
	nimfr("send", "net.nim")
	result = 0;
	nimln(919, "net.nim");
	result = send((*socket).fd, data, size, MSG_NOSIGNAL);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, isdisconnectionerror_140473)(NU8 flags, NI32 lasterror) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	nimfr("isDisconnectionError", "net.nim")
	result = 0;
	nimln(112, "net.nim");
	nimln(119, "net.nim");
	LOC1 = 0;
	nimln(1098, "system.nim");
	LOC1 = ((flags &(1U<<((NU)(((NU8) 1))&7U)))!=0);
	if (!(LOC1)) goto LA2;
	LOC1 = (lasterror == ((NI)chckRange(ECONNRESET, ((NI) 0), ((NI) 65535))) || lasterror == ((NI)chckRange(EPIPE, ((NI) 0), ((NI) 65535))) || lasterror == ((NI)chckRange(ENETRESET, ((NI) 0), ((NI) 65535))));
	LA2: ;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(NI32, getsocketerror_141001)(Socketimpl140404* socket) {
	NI32 result;
	nimfr("getSocketError", "net.nim")
	result = 0;
	nimln(290, "net.nim");
	result = oslasterror_119819();
	nimln(291, "net.nim");
	{
		if (!(result == ((NI32) 0))) goto LA3;
		nimln(292, "net.nim");
		result = (*socket).lasterror;
	}
	LA3: ;
	nimln(293, "net.nim");
	{
		if (!(result == ((NI32) 0))) goto LA7;
		nimln(294, "net.nim");
		raiseoserror_119803(result, ((NimStringDesc*) &TMP830));
	}
	LA7: ;
	popFrame();
	return result;
}

N_NIMCALL(void, socketerror_140467)(Socketimpl140404* socket, NI err, NIM_BOOL async, NI32 lasterror) {
	nimfr("socketError", "net.nim")
{	nimln(338, "net.nim");
	{
		NIM_BOOL LOC3;
		NI32 laste;
		LOC3 = 0;
		LOC3 = (err == ((NI) -1));
		if (!(LOC3)) goto LA4;
		LOC3 = NIM_TRUE;
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(339, "net.nim");
		{
			if (!(((NI) (lasterror)) == ((NI) -1))) goto LA9;
			laste = getsocketerror_141001(socket);
		}
		goto LA7;
		LA9: ;
		{
			laste = lasterror;
		}
		LA7: ;
		nimln(340, "net.nim");
		{
			if (!async) goto LA14;
			nimln(346, "net.nim");
			{
				NIM_BOOL LOC18;
				LOC18 = 0;
				LOC18 = (laste == EAGAIN);
				if (LOC18) goto LA19;
				LOC18 = (laste == EWOULDBLOCK);
				LA19: ;
				if (!LOC18) goto LA20;
				nimln(347, "net.nim");
				goto BeforeRet;
			}
			goto LA16;
			LA20: ;
			{
				nimln(348, "net.nim");
				raiseoserror_119803(laste, ((NimStringDesc*) &TMP831));
			}
			LA16: ;
		}
		goto LA12;
		LA14: ;
		{
			nimln(349, "net.nim");
			raiseoserror_119803(laste, ((NimStringDesc*) &TMP831));
		}
		LA12: ;
	}
	LA5: ;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, send_145202)(Socketimpl140404* socket, NimStringDesc* data, NU8 flags) {
	NI sent;
	nimfr("send", "net.nim")
{	nimln(924, "net.nim");
	sent = send_144677(socket, ((void*) (data->data)), (data ? data->Sup.len : 0));
	nimln(925, "net.nim");
	{
		NI32 lasterror;
		if (!(sent < ((NI) 0))) goto LA3;
		nimln(926, "net.nim");
		lasterror = oslasterror_119819();
		nimln(927, "net.nim");
		{
			NIM_BOOL LOC7;
			LOC7 = 0;
			LOC7 = isdisconnectionerror_140473(flags, lasterror);
			if (!LOC7) goto LA8;
			goto BeforeRet;
		}
		LA8: ;
		nimln(928, "net.nim");
		socketerror_140467(socket, ((NI) -1), NIM_FALSE, lasterror);
	}
	LA3: ;
	nimln(930, "net.nim");
	{
		NI32 LOC14;
		nimln(349, "system.nim");
		nimln(930, "net.nim");
		if (!!((sent == (data ? data->Sup.len : 0)))) goto LA12;
		nimln(931, "net.nim");
		LOC14 = 0;
		LOC14 = oslasterror_119819();
		raiseoserror_119803(LOC14, ((NimStringDesc*) &TMP832));
	}
	LA12: ;
	}BeforeRet: ;
	popFrame();
}
N_NIMCALL(void, TMP990)(void* p, NI op) {
	Socketimpl140404* a;
	NI LOC1;
	a = (Socketimpl140404*)p;
	switch ((*a).isbuffered) {
	case NIM_TRUE:
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < 4001; LOC1++) {
	}
	break;
	case NIM_FALSE:
	break;
	} 
}

N_NIMCALL(Socketimpl140404*, newsocket_140674)(int fd, NU8 domain, NU8 socktype, NU8 protocol, NIM_BOOL buffered) {
	Socketimpl140404* result;
	NIM_BOOL LOC5;
	nimfr("newSocket", "net.nim")
	result = 0;
	nimln(134, "net.nim");
	{
		if (!!(!((fd == osinvalidsocket_134645)))) goto LA3;
		failedassertimpl_89116(((NimStringDesc*) &TMP978));
	}
	LA3: ;
	nimln(135, "net.nim");
	result = (Socketimpl140404*) newObj((&NTI140406), sizeof(Socketimpl140404));
	nimln(136, "net.nim");
	(*result).fd = fd;
	nimln(137, "net.nim");
	LOC5 = 0;
	LOC5 = buffered;
	FieldDiscriminantCheck((NI)(NU)((*result).isbuffered), (NI)(NU)(LOC5), NimDT_140404_isbuffered, 3);
	(*result).isbuffered = LOC5;
	nimln(138, "net.nim");
	(*result).domain = domain;
	nimln(139, "net.nim");
	(*result).socktype = socktype;
	nimln(140, "net.nim");
	(*result).protocol = protocol;
	nimln(141, "net.nim");
	{
		if (!buffered) goto LA8;
		nimln(142, "net.nim");
		if (!(((2 &(1U<<((NU)((*result).isbuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TMP991));
		(*result).isbufferedU.S1.currpos = ((NI) 0);
	}
	LA8: ;
	popFrame();
	return result;
}

N_NIMCALL(Socketimpl140404*, newsocket_140821)(NU8 domain, NU8 socktype, NU8 protocol, NIM_BOOL buffered) {
	Socketimpl140404* result;
	int fd;
	nimfr("newSocket", "net.nim")
	result = 0;
	nimln(159, "net.nim");
	fd = newnativesocket_135001(domain, socktype, protocol);
	nimln(160, "net.nim");
	{
		NI32 LOC5;
		if (!(fd == osinvalidsocket_134645)) goto LA3;
		nimln(161, "net.nim");
		LOC5 = 0;
		LOC5 = oslasterror_119819();
		raiseoserror_119803(LOC5, ((NimStringDesc*) &TMP831));
	}
	LA3: ;
	nimln(162, "net.nim");
	result = newsocket_140674(fd, domain, socktype, protocol, buffered);
	popFrame();
	return result;
}

N_NIMCALL(void, connect_142633)(Socketimpl140404* socket, NimStringDesc* address, NU16 port) {
	struct addrinfo* ailist;
	NIM_BOOL success;
	NI32 lasterror;
	struct addrinfo* it;
	nimfr("connect", "net.nim")
	nimln(559, "net.nim");
	ailist = getaddrinfo_135402(address, port, (*socket).domain, ((NU8) 1), ((NU8) 6));
	nimln(561, "net.nim");
	success = NIM_FALSE;
	lasterror = 0;
	nimln(563, "net.nim");
	it = ailist;
	{
		nimln(564, "net.nim");
		while (1) {
			nimln(349, "system.nim");
			if (!!((it == NIM_NIL))) goto LA2;
			nimln(565, "net.nim");
			{
				int LOC5;
				LOC5 = 0;
				LOC5 = connect((*socket).fd, (*it).ai_addr, (*it).ai_addrlen);
				if (!(LOC5 == ((NI32) 0))) goto LA6;
				nimln(566, "net.nim");
				success = NIM_TRUE;
				nimln(567, "net.nim");
				goto LA1;
			}
			goto LA3;
			LA6: ;
			{
				nimln(568, "net.nim");
				lasterror = oslasterror_119819();
			}
			LA3: ;
			nimln(569, "net.nim");
			it = (*it).ai_next;
		} LA2: ;
	} LA1: ;
	nimln(571, "net.nim");
	dealloc_135802(ailist);
	nimln(572, "net.nim");
	{
		if (!!(success)) goto LA11;
		raiseoserror_119803(lasterror, ((NimStringDesc*) &TMP831));
	}
	LA11: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void) {
	nimfr("net", "net.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void) {
static TNimNode* TMP979[6];
static TNimNode* TMP980[3];
static TNimNode TMP140[12];
NTI140404.size = sizeof(Socketimpl140404);
NTI140404.kind = 18;
NTI140404.base = 0;
NTI140404.flags = 3;
TMP979[0] = &TMP140[1];
TMP140[1].kind = 1;
TMP140[1].offset = offsetof(Socketimpl140404, fd);
TMP140[1].typ = (&NTI7208);
TMP140[1].name = "fd";
TMP979[1] = &TMP140[2];
TMP140[2].kind = 3;
TMP140[2].offset = offsetof(Socketimpl140404, isbuffered);
TMP140[2].typ = (&NTI130);
TMP140[2].name = "isBuffered";
TMP140[2].sons = &NimDT_140404_isbuffered[0];
TMP140[2].len = 2;
TMP980[0] = &TMP140[4];
NTI140418.size = sizeof(TY140418);
NTI140418.kind = 16;
NTI140418.base = (&NTI136);
NTI140418.flags = 3;
TMP140[4].kind = 1;
TMP140[4].offset = offsetof(Socketimpl140404, isbufferedU.S1.buffer);
TMP140[4].typ = (&NTI140418);
TMP140[4].name = "buffer";
TMP980[1] = &TMP140[5];
TMP140[5].kind = 1;
TMP140[5].offset = offsetof(Socketimpl140404, isbufferedU.S1.currpos);
TMP140[5].typ = (&NTI104);
TMP140[5].name = "currPos";
TMP980[2] = &TMP140[6];
TMP140[6].kind = 1;
TMP140[6].offset = offsetof(Socketimpl140404, isbufferedU.S1.buflen);
TMP140[6].typ = (&NTI104);
TMP140[6].name = "bufLen";
TMP140[3].len = 3; TMP140[3].kind = 2; TMP140[3].sons = &TMP980[0];
NimDT_140404_isbuffered[1] = &TMP140[3];
TMP140[7].len = 0; TMP140[7].kind = 2;
NimDT_140404_isbuffered[0] = &TMP140[7];
TMP979[2] = &TMP140[8];
TMP140[8].kind = 1;
TMP140[8].offset = offsetof(Socketimpl140404, lasterror);
TMP140[8].typ = (&NTI110);
TMP140[8].name = "lastError";
TMP979[3] = &TMP140[9];
TMP140[9].kind = 1;
TMP140[9].offset = offsetof(Socketimpl140404, domain);
TMP140[9].typ = (&NTI134604);
TMP140[9].name = "domain";
TMP979[4] = &TMP140[10];
TMP140[10].kind = 1;
TMP140[10].offset = offsetof(Socketimpl140404, socktype);
TMP140[10].typ = (&NTI134606);
TMP140[10].name = "sockType";
TMP979[5] = &TMP140[11];
TMP140[11].kind = 1;
TMP140[11].offset = offsetof(Socketimpl140404, protocol);
TMP140[11].typ = (&NTI134608);
TMP140[11].name = "protocol";
TMP140[0].len = 6; TMP140[0].kind = 2; TMP140[0].sons = &TMP979[0];
NTI140404.node = &TMP140[0];
NTI140406.size = sizeof(Socketimpl140404*);
NTI140406.kind = 22;
NTI140406.base = (&NTI140404);
NTI140406.flags = 2;
NTI140406.marker = TMP990;
}

