/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/stdlib_strtabs.o /home/cyril/Projects/provider/nimcache/stdlib_strtabs.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct Stringtableobj173209 Stringtableobj173209;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Keyvaluepairseq173207 Keyvaluepairseq173207;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY104488 TY104488;
typedef struct Keyerror3648 Keyerror3648;
typedef struct Valueerror3646 Valueerror3646;
typedef struct Exception Exception;
typedef struct Cell47905 Cell47905;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Slice88482 Slice88482;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Stringtableobj173209  {
  TNimObject Sup;
NI counter;
Keyvaluepairseq173207* data;
NU8 mode;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY104488 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3646  {
  Exception Sup;
};
struct  Keyerror3648  {
  Valueerror3646 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50214 stat;
};
struct  Slice88482  {
NI a;
NI b;
};
typedef NU8 TY81010[32];
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
struct Keyvaluepairseq173207 {
  TGenericSeq Sup;
  TY104488 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, nstlen)(Stringtableobj173209* t);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, myhash_173302)(Stringtableobj173209* t, NimStringDesc* key);
N_NIMCALL(NI, hash_159827)(NimStringDesc* x);
N_NIMCALL(NI, hashignorecase_160059)(NimStringDesc* x);
N_NIMCALL(NI, hashignorestyle_159892)(NimStringDesc* x);
N_NIMCALL(NIM_BOOL, mycmp_173309)(Stringtableobj173209* t, NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, cmp_5680)(NimStringDesc* x, NimStringDesc* y);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NIM_BOOL, mustrehash_173315)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nexttry_173401)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(NI, rawget_173406)(Stringtableobj173209* t, NimStringDesc* key);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc**, nstTake)(Stringtableobj173209* t, NimStringDesc* key);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47905*, usrtocell_51840)(void* usr);
static N_INLINE(void, rtladdzct_53401)(Cell47905* c);
N_NOINLINE(void, addzct_51817)(Cellseq47921* s, Cell47905* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc**, mget_173614)(Stringtableobj173209* t, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, getordefault_173814)(Stringtableobj173209* t, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NIM_BOOL, nsthasKey)(Stringtableobj173209* t, NimStringDesc* key);
N_NIMCALL(void, rawinsert_173825)(Stringtableobj173209* t, Keyvaluepairseq173207** data, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, enlarge_173835)(Stringtableobj173209* t);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP755)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, nstPut)(Stringtableobj173209* t, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(void, raiseformatexception_173913)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, getvalue_173927)(Stringtableobj173209* t, NU8 flags, NimStringDesc* key);
N_NIMCALL(NimStringDesc*, getenv_124825)(NimStringDesc* key);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(Stringtableobj173209*, nstnewStringTable)(NU8 mode);
N_NIMCALL(void, TMP766)(void* p, NI op);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void, clear_173987)(Stringtableobj173209* s, NU8 mode);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
static N_INLINE(Slice88482, HEX2EHEX2E_101424)(NI a, NI b);
N_NIMCALL(Stringtableobj173209*, nstnewStringTableWithPairs)(NimStringDesc** keyvaluepairs, NI keyvaluepairsLen0, NU8 mode);
N_NIMCALL(Stringtableobj173209*, nstnewStringTableWithTableConstr)(TY104488* keyvaluepairs, NI keyvaluepairsLen0, NU8 mode);
N_NIMCALL(NimStringDesc*, nstFormat)(NimStringDesc* f, Stringtableobj173209* t, NU8 flags);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_80210, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nstDollar)(Stringtableobj173209* t);
STRING_LITERAL(TMP744, "\012  counter < length ", 20);
STRING_LITERAL(TMP751, "key not found: ", 15);
STRING_LITERAL(TMP752, "", 0);
STRING_LITERAL(TMP758, "format string: key not found: ", 30);
NIM_CONST TY81010 Patternchars_174116 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03,
0xFE, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
STRING_LITERAL(TMP784, "{:}", 3);
STRING_LITERAL(TMP785, "{", 1);
STRING_LITERAL(TMP786, ", ", 2);
STRING_LITERAL(TMP787, ": ", 2);
STRING_LITERAL(TMP789, "}", 1);
extern TFrame* frameptr_19436;
extern TNimType NTI173604; /* ref KeyError */
extern TNimType NTI3648; /* KeyError */
extern Gcheap50218 gch_50259;
extern TNimType NTI104488; /* tuple[nonDST: string, DST: string] */
TNimType NTI173207; /* KeyValuePairSeq */
extern TNimType NTI24025; /* ref ValueError */
extern TNimType NTI3646; /* ValueError */
extern TNimType NTI3608; /* RootObj */
TNimType NTI173209; /* StringTableObj */
extern TNimType NTI104; /* int */
TNimType NTI173203; /* StringTableMode */
TNimType NTI173211; /* StringTableRef */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(NI, nstlen)(Stringtableobj173209* t) {
	NI result;
	nimfr("len", "strtabs.nim")
	result = 0;
	nimln(39, "strtabs.nim");
	result = (*t).counter;
	popFrame();
	return result;
}

N_NIMCALL(NI, myhash_173302)(Stringtableobj173209* t, NimStringDesc* key) {
	NI result;
	nimfr("myhash", "strtabs.nim")
	result = 0;
	nimln(78, "strtabs.nim");
	switch ((*t).mode) {
	case ((NU8) 0):
	{
		nimln(79, "strtabs.nim");
		result = hash_159827(key);
	}
	break;
	case ((NU8) 1):
	{
		nimln(80, "strtabs.nim");
		result = hashignorecase_160059(key);
	}
	break;
	case ((NU8) 2):
	{
		nimln(81, "strtabs.nim");
		result = hashignorestyle_159892(key);
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, mycmp_173309)(Stringtableobj173209* t, NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	nimfr("myCmp", "strtabs.nim")
	result = 0;
	nimln(84, "strtabs.nim");
	switch ((*t).mode) {
	case ((NU8) 0):
	{
		NI LOC2;
		nimln(85, "strtabs.nim");
		LOC2 = 0;
		LOC2 = cmp_5680(a, b);
		result = (LOC2 == ((NI) 0));
	}
	break;
	case ((NU8) 1):
	{
		NI LOC4;
		nimln(86, "strtabs.nim");
		LOC4 = 0;
		LOC4 = nsuCmpIgnoreCase(a, b);
		result = (LOC4 == ((NI) 0));
	}
	break;
	case ((NU8) 2):
	{
		NI LOC6;
		nimln(87, "strtabs.nim");
		LOC6 = 0;
		LOC6 = nsuCmpIgnoreStyle(a, b);
		result = (LOC6 == ((NI) 0));
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, mustrehash_173315)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP745;
	NI TMP746;
	NI TMP747;
	nimfr("mustRehash", "strtabs.nim")
	result = 0;
	nimln(90, "strtabs.nim");
	{
		if (!!((counter < length))) goto LA3;
		failedassertimpl_89116(((NimStringDesc*) &TMP744));
	}
	LA3: ;
	nimln(91, "strtabs.nim");
	LOC5 = 0;
	TMP745 = mulInt(length, ((NI) 2));
	TMP746 = mulInt(counter, ((NI) 3));
	LOC5 = ((NI)(TMP745) < (NI)(TMP746));
	if (LOC5) goto LA6;
	TMP747 = subInt(length, counter);
	LOC5 = ((NI)(TMP747) < ((NI) 4));
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_173401)(NI h, NI maxhash) {
	NI result;
	NI TMP748;
	NI TMP749;
	nimfr("nextTry", "strtabs.nim")
	result = 0;
	nimln(94, "strtabs.nim");
	TMP748 = mulInt(((NI) 5), h);
	TMP749 = addInt((NI)(TMP748), ((NI) 1));
	result = (NI)((NI)(TMP749) & maxhash);
	popFrame();
	return result;
}

N_NIMCALL(NI, rawget_173406)(Stringtableobj173209* t, NimStringDesc* key) {
	NI result;
	NI h;
	NI LOC1;
	nimfr("rawGet", "strtabs.nim")
{	result = 0;
	nimln(97, "strtabs.nim");
	LOC1 = 0;
	LOC1 = myhash_173302(t, key);
	h = (NI)(LOC1 & ((*t).data ? ((*t).data->Sup.len-1) : -1));
	{
		nimln(98, "strtabs.nim");
		while (1) {
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			if (!!((*t).data->data[h].Field0 == 0)) goto LA3;
			nimln(99, "strtabs.nim");
			{
				NIM_BOOL LOC6;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				LOC6 = 0;
				LOC6 = mycmp_173309(t, (*t).data->data[h].Field0, key);
				if (!LOC6) goto LA7;
				nimln(100, "strtabs.nim");
				result = h;
				goto BeforeRet;
			}
			LA7: ;
			nimln(101, "strtabs.nim");
			h = nexttry_173401(h, ((*t).data ? ((*t).data->Sup.len-1) : -1));
		} LA3: ;
	}
	nimln(102, "strtabs.nim");
	result = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(Cell47905*, usrtocell_51840)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53401)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_51817((&gch_50259.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell47905* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_51840(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell47905* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_51840((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_53401(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NimStringDesc**, nstTake)(Stringtableobj173209* t, NimStringDesc* key) {
	NimStringDesc** result;
	NI index_173432;
	nimfr("[]", "strtabs.nim")
	result = 0;
	nimln(105, "strtabs.nim");
	index_173432 = rawget_173406(t, key);
	nimln(106, "strtabs.nim");
	{
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index_173432)) goto LA3;
		nimln(106, "strtabs.nim");
		if ((NU)(index_173432) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (&(*t).data->data[index_173432].Field1);
	}
	goto LA1;
	LA3: ;
	{
		Keyerror3648* e_173603;
		NimStringDesc* LOC6;
		e_173603 = 0;
		nimln(2507, "system.nim");
		e_173603 = (Keyerror3648*) newObj((&NTI173604), sizeof(Keyerror3648));
		(*e_173603).Sup.Sup.Sup.m_type = (&NTI3648);
		nimln(2508, "system.nim");
		nimln(109, "strtabs.nim");
		LOC6 = 0;
		LOC6 = rawNewString(key->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP751));
appendString(LOC6, key);
		asgnRefNoCycle((void**) (&(*e_173603).Sup.Sup.message), LOC6);
		raiseException((Exception*)e_173603, "KeyError");
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc**, mget_173614)(Stringtableobj173209* t, NimStringDesc* key) {
	NimStringDesc** result;
	NI index_173621;
	nimfr("mget", "strtabs.nim")
	result = 0;
	nimln(105, "strtabs.nim");
	index_173621 = rawget_173406(t, key);
	nimln(106, "strtabs.nim");
	{
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index_173621)) goto LA3;
		nimln(106, "strtabs.nim");
		if ((NU)(index_173621) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (&(*t).data->data[index_173621].Field1);
	}
	goto LA1;
	LA3: ;
	{
		Keyerror3648* e_173803;
		NimStringDesc* LOC6;
		e_173803 = 0;
		nimln(2507, "system.nim");
		e_173803 = (Keyerror3648*) newObj((&NTI173604), sizeof(Keyerror3648));
		(*e_173803).Sup.Sup.Sup.m_type = (&NTI3648);
		nimln(2508, "system.nim");
		nimln(109, "strtabs.nim");
		LOC6 = 0;
		LOC6 = rawNewString(key->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP751));
appendString(LOC6, key);
		asgnRefNoCycle((void**) (&(*e_173803).Sup.Sup.message), LOC6);
		raiseException((Exception*)e_173803, "KeyError");
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getordefault_173814)(Stringtableobj173209* t, NimStringDesc* key) {
	NimStringDesc* result;
	NI index;
	nimfr("getOrDefault", "strtabs.nim")
	result = 0;
	nimln(126, "strtabs.nim");
	index = rawget_173406(t, key);
	nimln(127, "strtabs.nim");
	{
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index)) goto LA3;
		nimln(127, "strtabs.nim");
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = copyString((*t).data->data[index].Field1);
	}
	goto LA1;
	LA3: ;
	{
		nimln(128, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP752));
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, nsthasKey)(Stringtableobj173209* t, NimStringDesc* key) {
	NIM_BOOL result;
	NI LOC1;
	nimfr("hasKey", "strtabs.nim")
	result = 0;
	nimln(132, "strtabs.nim");
	nimln(353, "system.nim");
	nimln(132, "strtabs.nim");
	LOC1 = 0;
	LOC1 = rawget_173406(t, key);
	result = (((NI) 0) <= LOC1);
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47905* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_51840(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_53401(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, rawinsert_173825)(Stringtableobj173209* t, Keyvaluepairseq173207** data, NimStringDesc* key, NimStringDesc* val) {
	NI h;
	NI LOC1;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	nimfr("rawInsert", "strtabs.nim")
	nimln(135, "strtabs.nim");
	LOC1 = 0;
	LOC1 = myhash_173302(t, key);
	h = (NI)(LOC1 & ((*data) ? ((*data)->Sup.len-1) : -1));
	{
		nimln(136, "strtabs.nim");
		while (1) {
			if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
			if (!!((*data)->data[h].Field0 == 0)) goto LA3;
			nimln(137, "strtabs.nim");
			h = nexttry_173401(h, ((*data) ? ((*data)->Sup.len-1) : -1));
		} LA3: ;
	}
	nimln(138, "strtabs.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC4 = 0;
	LOC4 = (*data)->data[h].Field0; (*data)->data[h].Field0 = copyStringRC1(key);
	if (LOC4) nimGCunrefNoCycle(LOC4);
	nimln(139, "strtabs.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	LOC5 = 0;
	LOC5 = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(val);
	if (LOC5) nimGCunrefNoCycle(LOC5);
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP755)(void* p, NI op) {
	Keyvaluepairseq173207* a;
	NI LOC1;
	a = (Keyvaluepairseq173207*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0, op);
	nimGCvisit((void*)a->data[LOC1].Field1, op);
	}
}

N_NIMCALL(void, enlarge_173835)(Stringtableobj173209* t) {
	Keyvaluepairseq173207* n;
	NI TMP753;
	Keyvaluepairseq173207* LOC8;
	nimfr("enlarge", "strtabs.nim")
	n = 0;
	nimln(143, "strtabs.nim");
	TMP753 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq173207*) newSeq((&NTI173207), ((NI)chckRange((NI)(TMP753), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_173868;
		NI HEX3Atmp_173882;
		NI res_173885;
		i_173868 = 0;
		HEX3Atmp_173882 = 0;
		nimln(144, "strtabs.nim");
		HEX3Atmp_173882 = ((*t).data ? ((*t).data->Sup.len-1) : -1);
		nimln(1874, "system.nim");
		res_173885 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP756;
				if (!(res_173885 <= HEX3Atmp_173882)) goto LA3;
				nimln(1876, "system.nim");
				i_173868 = res_173885;
				nimln(145, "strtabs.nim");
				{
					if ((NU)(i_173868) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if (!!((*t).data->data[i_173868].Field0 == 0)) goto LA6;
					if ((NU)(i_173868) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if ((NU)(i_173868) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					rawinsert_173825(t, (&n), (*t).data->data[i_173868].Field0, (*t).data->data[i_173868].Field1);
				}
				LA6: ;
				nimln(1890, "system.nim");
				TMP756 = addInt(res_173885, ((NI) 1));
				res_173885 = (NI)(TMP756);
			} LA3: ;
		}
	}
	nimln(146, "strtabs.nim");
	LOC8 = 0;
	LOC8 = (*t).data;
	asgnRefNoCycle((void**) (&(*t).data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(void, nstPut)(Stringtableobj173209* t, NimStringDesc* key, NimStringDesc* val) {
	NI index;
	nimfr("[]=", "strtabs.nim")
	nimln(150, "strtabs.nim");
	index = rawget_173406(t, key);
	nimln(151, "strtabs.nim");
	{
		NimStringDesc* LOC5;
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index)) goto LA3;
		nimln(152, "strtabs.nim");
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		LOC5 = 0;
		LOC5 = (*t).data->data[index].Field1; (*t).data->data[index].Field1 = copyStringRC1(val);
		if (LOC5) nimGCunrefNoCycle(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP757;
		nimln(154, "strtabs.nim");
		{
			NIM_BOOL LOC9;
			LOC9 = 0;
			LOC9 = mustrehash_173315(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC9) goto LA10;
			enlarge_173835(t);
		}
		LA10: ;
		nimln(155, "strtabs.nim");
		rawinsert_173825(t, (&(*t).data), key, val);
		nimln(156, "strtabs.nim");
		TMP757 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP757);
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, raiseformatexception_173913)(NimStringDesc* s) {
	Valueerror3646* e;
	NimStringDesc* LOC1;
	nimfr("raiseFormatException", "strtabs.nim")
	e = 0;
	nimln(160, "strtabs.nim");
	e = (Valueerror3646*) newObj((&NTI24025), sizeof(Valueerror3646));
	(*e).Sup.Sup.m_type = (&NTI3646);
	nimln(161, "strtabs.nim");
	LOC1 = 0;
	LOC1 = rawNewString(s->Sup.len + 30);
appendString(LOC1, ((NimStringDesc*) &TMP758));
appendString(LOC1, s);
	asgnRefNoCycle((void**) (&(*e).Sup.message), LOC1);
	nimln(162, "strtabs.nim");
	raiseException((Exception*)e, "ValueError");
	popFrame();
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, getvalue_173927)(Stringtableobj173209* t, NU8 flags, NimStringDesc* key) {
	NimStringDesc* result;
	nimfr("getValue", "strtabs.nim")
{	result = 0;
	nimln(165, "strtabs.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = nsthasKey(t, key);
		if (!LOC3) goto LA4;
		result = getordefault_173814(t, key);
		goto BeforeRet;
	}
	LA4: ;
	nimln(167, "strtabs.nim");
	{
		nimln(1098, "system.nim");
		if (!((flags &(1U<<((NU)(((NU8) 0))&7U)))!=0)) goto LA8;
		nimln(167, "strtabs.nim");
		result = getenv_124825(key);
	}
	goto LA6;
	LA8: ;
	{
		nimln(168, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP752));
	}
	LA6: ;
	nimln(169, "strtabs.nim");
	{
		if (!((result ? result->Sup.len : 0) == ((NI) 0))) goto LA13;
		nimln(170, "strtabs.nim");
		{
			NimStringDesc* LOC19;
			nimln(1098, "system.nim");
			if (!((flags &(1U<<((NU)(((NU8) 2))&7U)))!=0)) goto LA17;
			nimln(170, "strtabs.nim");
			LOC19 = 0;
			LOC19 = rawNewString(key->Sup.len + 1);
appendChar(LOC19, 36);
appendString(LOC19, key);
			result = LOC19;
		}
		goto LA15;
		LA17: ;
		{
			nimln(1104, "system.nim");
			if (!!(((flags &(1U<<((NU)(((NU8) 1))&7U)))!=0))) goto LA21;
			nimln(171, "strtabs.nim");
			raiseformatexception_173913(key);
		}
		goto LA15;
		LA21: ;
		LA15: ;
	}
	LA13: ;
	}BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP766)(void* p, NI op) {
	Stringtableobj173209* a;
	a = (Stringtableobj173209*)p;
	nimGCvisit((void*)(*a).data, op);
}

N_NIMCALL(Stringtableobj173209*, nstnewStringTable)(NU8 mode) {
	Stringtableobj173209* result;
	nimfr("newStringTable", "strtabs.nim")
	result = 0;
	nimln(176, "strtabs.nim");
	result = (Stringtableobj173209*) newObj((&NTI173211), sizeof(Stringtableobj173209));
	(*result).Sup.m_type = (&NTI173209);
	nimln(177, "strtabs.nim");
	(*result).mode = mode;
	nimln(178, "strtabs.nim");
	(*result).counter = ((NI) 0);
	nimln(179, "strtabs.nim");
	if ((*result).data) nimGCunrefNoCycle((*result).data);
	(*result).data = (Keyvaluepairseq173207*) newSeqRC1((&NTI173207), ((NI) 64));
	popFrame();
	return result;
}

static N_INLINE(Slice88482, HEX2EHEX2E_101424)(NI a, NI b) {
	Slice88482 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(270, "system.nim");
	result.a = a;
	nimln(271, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_NIMCALL(void, clear_173987)(Stringtableobj173209* s, NU8 mode) {
	nimfr("clear", "strtabs.nim")
	nimln(183, "strtabs.nim");
	(*s).mode = mode;
	nimln(184, "strtabs.nim");
	(*s).counter = ((NI) 0);
	nimln(185, "strtabs.nim");
	(*s).data = (Keyvaluepairseq173207*) setLengthSeq(&((*s).data)->Sup, sizeof(TY104488), ((NI) 64));
	{
		NI i_174034;
		Slice88482 HEX3Atmp_174036;
		i_174034 = 0;
		memset((void*)(&HEX3Atmp_174036), 0, sizeof(HEX3Atmp_174036));
		nimln(3548, "system.nim");
		nimln(3550, "system.nim");
		nimln(186, "strtabs.nim");
		HEX3Atmp_174036 = HEX2EHEX2E_101424(((NI) 0), subInt(((*s).data ? (*s).data->Sup.len : 0), 1));
		{
			NI x_174040;
			NI HEX3Atmp_174042;
			NI HEX3Atmp_174044;
			NI res_174046;
			x_174040 = 0;
			HEX3Atmp_174042 = 0;
			HEX3Atmp_174044 = 0;
			nimln(2026, "system.nim");
			HEX3Atmp_174042 = HEX3Atmp_174036.a;
			HEX3Atmp_174044 = HEX3Atmp_174036.b;
			nimln(1874, "system.nim");
			res_174046 = HEX3Atmp_174042;
			{
				nimln(1875, "system.nim");
				while (1) {
					NI TMP767;
					if (!(res_174046 <= HEX3Atmp_174044)) goto LA4;
					nimln(1876, "system.nim");
					x_174040 = res_174046;
					nimln(2026, "system.nim");
					i_174034 = x_174040;
					nimln(187, "strtabs.nim");
					{
						NimStringDesc* LOC9;
						if ((NU)(i_174034) >= (NU)((*s).data->Sup.len)) raiseIndexError();
						if (!!((*s).data->data[i_174034].Field0 == 0)) goto LA7;
						nimln(188, "strtabs.nim");
						if ((NU)(i_174034) >= (NU)((*s).data->Sup.len)) raiseIndexError();
						LOC9 = 0;
						LOC9 = (*s).data->data[i_174034].Field0; (*s).data->data[i_174034].Field0 = copyStringRC1(NIM_NIL);
						if (LOC9) nimGCunrefNoCycle(LOC9);
					}
					LA7: ;
					nimln(1895, "system.nim");
					TMP767 = addInt(res_174046, ((NI) 1));
					res_174046 = (NI)(TMP767);
				} LA4: ;
			}
		}
	}
	popFrame();
}

N_NIMCALL(Stringtableobj173209*, nstnewStringTableWithPairs)(NimStringDesc** keyvaluepairs, NI keyvaluepairsLen0, NU8 mode) {
	Stringtableobj173209* result;
	NI i;
	nimfr("newStringTable", "strtabs.nim")
	result = 0;
	nimln(197, "strtabs.nim");
	result = nstnewStringTable(mode);
	nimln(198, "strtabs.nim");
	i = ((NI) 0);
	{
		nimln(199, "strtabs.nim");
		while (1) {
			NI TMP768;
			NI TMP769;
			if (!(i < (keyvaluepairsLen0-1))) goto LA2;
			nimln(200, "strtabs.nim");
			if ((NU)(i) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
			TMP768 = addInt(i, ((NI) 1));
			if ((NU)((NI)(TMP768)) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
			nstPut(result, keyvaluepairs[i], keyvaluepairs[(NI)(TMP768)]);
			nimln(201, "strtabs.nim");
			TMP769 = addInt(i, ((NI) 2));
			i = (NI)(TMP769);
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(Stringtableobj173209*, nstnewStringTableWithTableConstr)(TY104488* keyvaluepairs, NI keyvaluepairsLen0, NU8 mode) {
	Stringtableobj173209* result;
	nimfr("newStringTable", "strtabs.nim")
	result = 0;
	nimln(210, "strtabs.nim");
	result = nstnewStringTable(mode);
	{
		NimStringDesc* key_174101;
		NimStringDesc* val_174102;
		NI i_174106;
		key_174101 = 0;
		val_174102 = 0;
		nimln(1965, "system.nim");
		i_174106 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				NI TMP770;
				if (!(i_174106 < keyvaluepairsLen0)) goto LA3;
				nimln(1967, "system.nim");
				if ((NU)(i_174106) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
				key_174101 = keyvaluepairs[i_174106].Field0;
				if ((NU)(i_174106) >= (NU)(keyvaluepairsLen0)) raiseIndexError();
				val_174102 = keyvaluepairs[i_174106].Field1;
				nimln(211, "strtabs.nim");
				nstPut(result, key_174101, val_174102);
				nimln(1968, "system.nim");
				TMP770 = addInt(i_174106, ((NI) 1));
				i_174106 = (NI)(TMP770);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nstFormat)(NimStringDesc* f, Stringtableobj173209* t, NU8 flags) {
	NimStringDesc* result;
	NI i;
	nimfr("%", "strtabs.nim")
	result = 0;
	nimln(218, "strtabs.nim");
	result = copyString(((NimStringDesc*) &TMP752));
	nimln(219, "strtabs.nim");
	i = ((NI) 0);
	{
		nimln(220, "strtabs.nim");
		while (1) {
			if (!(i < (f ? f->Sup.len : 0))) goto LA2;
			nimln(221, "strtabs.nim");
			{
				NI TMP771;
				if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
				if (!((NU8)(f->data[i]) == (NU8)(36))) goto LA5;
				nimln(222, "strtabs.nim");
				TMP771 = addInt(i, ((NI) 1));
				if ((NU)((NI)(TMP771)) > (NU)(f->Sup.len)) raiseIndexError();
				switch (((NU8)(f->data[(NI)(TMP771)]))) {
				case 36:
				{
					NI TMP772;
					nimln(224, "strtabs.nim");
					result = addChar(result, 36);
					nimln(225, "strtabs.nim");
					TMP772 = addInt(i, ((NI) 2));
					i = (NI)(TMP772);
				}
				break;
				case 123:
				{
					NI j;
					NI TMP773;
					NI TMP775;
					NI TMP776;
					NimStringDesc* LOC13;
					NimStringDesc* LOC14;
					NI TMP777;
					nimln(227, "strtabs.nim");
					TMP773 = addInt(i, ((NI) 1));
					j = (NI)(TMP773);
					{
						nimln(228, "strtabs.nim");
						while (1) {
							NIM_BOOL LOC11;
							NI TMP774;
							LOC11 = 0;
							LOC11 = (j < (f ? f->Sup.len : 0));
							if (!(LOC11)) goto LA12;
							nimln(349, "system.nim");
							if ((NU)(j) > (NU)(f->Sup.len)) raiseIndexError();
							LOC11 = !(((NU8)(f->data[j]) == (NU8)(125)));
							LA12: ;
							if (!LOC11) goto LA10;
							nimln(228, "strtabs.nim");
							TMP774 = addInt(j, ((NI) 1));
							j = (NI)(TMP774);
						} LA10: ;
					}
					nimln(229, "strtabs.nim");
					TMP775 = addInt(i, ((NI) 2));
					TMP776 = subInt(j, ((NI) 1));
					LOC13 = 0;
					LOC13 = copyStrLast(f, (NI)(TMP775), (NI)(TMP776));
					LOC14 = 0;
					LOC14 = getvalue_173927(t, flags, LOC13);
					result = resizeString(result, LOC14->Sup.len + 0);
appendString(result, LOC14);
					nimln(230, "strtabs.nim");
					TMP777 = addInt(j, ((NI) 1));
					i = (NI)(TMP777);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NI j;
					NI TMP778;
					NI TMP780;
					NI TMP781;
					NimStringDesc* LOC20;
					NimStringDesc* LOC21;
					nimln(232, "strtabs.nim");
					TMP778 = addInt(i, ((NI) 1));
					j = (NI)(TMP778);
					{
						nimln(233, "strtabs.nim");
						while (1) {
							NIM_BOOL LOC18;
							NI TMP779;
							LOC18 = 0;
							LOC18 = (j < (f ? f->Sup.len : 0));
							if (!(LOC18)) goto LA19;
							nimln(1098, "system.nim");
							if ((NU)(j) > (NU)(f->Sup.len)) raiseIndexError();
							LOC18 = (((NU8)(f->data[j])) >= ((NU8)(97)) && ((NU8)(f->data[j])) <= ((NU8)(122)) || ((NU8)(f->data[j])) >= ((NU8)(65)) && ((NU8)(f->data[j])) <= ((NU8)(90)) || ((NU8)(f->data[j])) >= ((NU8)(48)) && ((NU8)(f->data[j])) <= ((NU8)(57)) || ((NU8)(f->data[j])) == ((NU8)(95)) || ((NU8)(f->data[j])) >= ((NU8)(128)) && ((NU8)(f->data[j])) <= ((NU8)(255)));
							LA19: ;
							if (!LOC18) goto LA17;
							nimln(233, "strtabs.nim");
							TMP779 = addInt(j, ((NI) 1));
							j = (NI)(TMP779);
						} LA17: ;
					}
					nimln(234, "strtabs.nim");
					TMP780 = addInt(i, ((NI) 1));
					TMP781 = subInt(j, ((NI) 1));
					LOC20 = 0;
					LOC20 = copyStrLast(f, (NI)(TMP780), (NI)(TMP781));
					LOC21 = 0;
					LOC21 = getvalue_173927(t, flags, LOC20);
					result = resizeString(result, LOC21->Sup.len + 0);
appendString(result, LOC21);
					nimln(235, "strtabs.nim");
					i = j;
				}
				break;
				default:
				{
					NI TMP782;
					nimln(237, "strtabs.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					result = addChar(result, f->data[i]);
					nimln(238, "strtabs.nim");
					TMP782 = addInt(i, ((NI) 1));
					i = (NI)(TMP782);
				}
				break;
				}
			}
			goto LA3;
			LA5: ;
			{
				NI TMP783;
				nimln(240, "strtabs.nim");
				if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
				result = addChar(result, f->data[i]);
				nimln(241, "strtabs.nim");
				TMP783 = addInt(i, ((NI) 1));
				i = (NI)(TMP783);
			}
			LA3: ;
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nstDollar)(Stringtableobj173209* t) {
	NimStringDesc* result;
	nimfr("$", "strtabs.nim")
	result = 0;
	nimln(245, "strtabs.nim");
	{
		NI LOC3;
		LOC3 = 0;
		LOC3 = nstlen(t);
		if (!(LOC3 == ((NI) 0))) goto LA4;
		nimln(246, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP784));
	}
	goto LA1;
	LA4: ;
	{
		nimln(248, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TMP785));
		{
			NimStringDesc* key_174183;
			NimStringDesc* val_174184;
			key_174183 = 0;
			val_174184 = 0;
			{
				NI h_174189;
				NI HEX3Atmp_174191;
				NI res_174193;
				h_174189 = 0;
				HEX3Atmp_174191 = 0;
				nimln(43, "strtabs.nim");
				HEX3Atmp_174191 = ((*t).data ? ((*t).data->Sup.len-1) : -1);
				nimln(1874, "system.nim");
				res_174193 = ((NI) 0);
				{
					nimln(1875, "system.nim");
					while (1) {
						NI TMP788;
						if (!(res_174193 <= HEX3Atmp_174191)) goto LA10;
						nimln(1876, "system.nim");
						h_174189 = res_174193;
						nimln(44, "strtabs.nim");
						{
							if ((NU)(h_174189) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							if (!!((*t).data->data[h_174189].Field0 == 0)) goto LA13;
							nimln(45, "strtabs.nim");
							if ((NU)(h_174189) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							key_174183 = (*t).data->data[h_174189].Field0;
							if ((NU)(h_174189) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							val_174184 = (*t).data->data[h_174189].Field1;
							nimln(250, "strtabs.nim");
							{
								nimln(357, "system.nim");
								nimln(250, "strtabs.nim");
								if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA17;
								result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP786));
							}
							LA17: ;
							nimln(251, "strtabs.nim");
							result = resizeString(result, key_174183->Sup.len + 0);
appendString(result, key_174183);
							nimln(252, "strtabs.nim");
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP787));
							nimln(253, "strtabs.nim");
							result = resizeString(result, val_174184->Sup.len + 0);
appendString(result, val_174184);
						}
						LA13: ;
						nimln(1895, "system.nim");
						TMP788 = addInt(res_174193, ((NI) 1));
						res_174193 = (NI)(TMP788);
					} LA10: ;
				}
			}
		}
		nimln(254, "strtabs.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP789));
	}
	LA1: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit000)(void) {
	nimfr("strtabs", "strtabs.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit000)(void) {
static TNimNode* TMP762[3];
static TNimNode* TMP763[3];
NI TMP765;
static char* NIM_CONST TMP764[3] = {
"modeCaseSensitive", 
"modeCaseInsensitive", 
"modeStyleInsensitive"};
static TNimNode TMP742[8];
NTI173207.size = sizeof(Keyvaluepairseq173207*);
NTI173207.kind = 24;
NTI173207.base = (&NTI104488);
NTI173207.flags = 2;
NTI173207.marker = TMP755;
NTI173209.size = sizeof(Stringtableobj173209);
NTI173209.kind = 17;
NTI173209.base = (&NTI3608);
TMP762[0] = &TMP742[1];
TMP742[1].kind = 1;
TMP742[1].offset = offsetof(Stringtableobj173209, counter);
TMP742[1].typ = (&NTI104);
TMP742[1].name = "counter";
TMP762[1] = &TMP742[2];
TMP742[2].kind = 1;
TMP742[2].offset = offsetof(Stringtableobj173209, data);
TMP742[2].typ = (&NTI173207);
TMP742[2].name = "data";
TMP762[2] = &TMP742[3];
NTI173203.size = sizeof(NU8);
NTI173203.kind = 14;
NTI173203.base = 0;
NTI173203.flags = 3;
for (TMP765 = 0; TMP765 < 3; TMP765++) {
TMP742[TMP765+4].kind = 1;
TMP742[TMP765+4].offset = TMP765;
TMP742[TMP765+4].name = TMP764[TMP765];
TMP763[TMP765] = &TMP742[TMP765+4];
}
TMP742[7].len = 3; TMP742[7].kind = 2; TMP742[7].sons = &TMP763[0];
NTI173203.node = &TMP742[7];
TMP742[3].kind = 1;
TMP742[3].offset = offsetof(Stringtableobj173209, mode);
TMP742[3].typ = (&NTI173203);
TMP742[3].name = "mode";
TMP742[0].len = 3; TMP742[0].kind = 2; TMP742[0].sons = &TMP762[0];
NTI173209.node = &TMP742[0];
NTI173211.size = sizeof(Stringtableobj173209*);
NTI173211.kind = 22;
NTI173211.base = (&NTI173209);
NTI173211.marker = TMP766;
}

