/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/stdlib_osproc.o /home/cyril/Projects/provider/nimcache/stdlib_osproc.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
#include <unistd.h>
#include <setjmp.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <signal.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <sys/select.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Processobj192404 Processobj192404;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Streamobj149218 Streamobj149218;
typedef struct TY193001 TY193001;
typedef struct Cell47905 Cell47905;
typedef struct Cellset47917 Cellset47917;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Stringtableobj173209 Stringtableobj173209;
typedef struct Keyvaluepairseq173207 Keyvaluepairseq173207;
typedef struct TY104488 TY104488;
typedef struct TY15805 TY15805;
typedef struct Startprocessdata193703 Startprocessdata193703;
typedef struct Exception Exception;
typedef struct TSafePoint TSafePoint;
typedef struct Filestreamobj150048 Filestreamobj150048;
typedef struct TY196007 TY196007;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TY81010[32];
typedef NimStringDesc* TY192625[1];
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Processobj192404  {
  TNimObject Sup;
int inhandle;
int outhandle;
int errhandle;
Streamobj149218* instream;
Streamobj149218* outstream;
Streamobj149218* errstream;
pid_t id;
int exitcode;
NU8 options;
};
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI idx, void* ClEnv);
void* ClEnv;
} TY192711;
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (NI idx, Processobj192404* p, void* ClEnv);
void* ClEnv;
} TY192715;
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CLOSURE_PTR(void, TMP919) (NI idx);
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50214 stat;
};
typedef N_CLOSURE_PTR(void, TMP927) (NI idx, Processobj192404* p);
typedef N_CLOSURE_PTR(void, TMP928) (NI idx);
typedef N_CLOSURE_PTR(void, TMP932) (NI idx, Processobj192404* p);
typedef N_CLOSURE_PTR(void, TMP934) (NI idx);
typedef N_CLOSURE_PTR(void, TMP935) (NI idx, Processobj192404* p);
struct  Stringtableobj173209  {
  TNimObject Sup;
NI counter;
Keyvaluepairseq173207* data;
NU8 mode;
};
struct TY104488 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef int TY193709[2];
struct  Startprocessdata193703  {
NCSTRING syscommand;
NCSTRING* sysargs;
NCSTRING* sysenv;
NCSTRING workingdir;
TY193709 pstdin;
TY193709 pstdout;
TY193709 pstderr;
TY193709 perrorpipe;
NIM_BOOL optionpousepath;
NIM_BOOL optionpoparentstreams;
NIM_BOOL optionpostderrtostdout;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY17811;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY17811 raiseAction;
};
typedef NimStringDesc* TY194612[2];
typedef NimStringDesc* TY193860[3];
typedef NimStringDesc* TY194001[1];
struct TY196007 {
NimStringDesc* Field0;
NI Field1;
};
typedef N_NIMCALL_PTR(void, TY149219) (Streamobj149218* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY149223) (Streamobj149218* s);
typedef N_NIMCALL_PTR(void, TY149227) (Streamobj149218* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY149232) (Streamobj149218* s);
typedef N_NIMCALL_PTR(NI, TY149236) (Streamobj149218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY149242) (Streamobj149218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY149248) (Streamobj149218* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY149254) (Streamobj149218* s);
struct  Streamobj149218  {
  TNimObject Sup;
TY149219 closeimpl;
TY149223 atendimpl;
TY149227 setpositionimpl;
TY149232 getpositionimpl;
TY149236 readdataimpl;
TY149242 peekdataimpl;
TY149248 writedataimpl;
TY149254 flushimpl;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY30019[8];
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  Filestreamobj150048  {
  Streamobj149218 Sup;
FILE* f;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
struct TY193001 {
  TGenericSeq Sup;
  Processobj192404* data[SEQ_DECL_SIZE];
};
struct TY15805 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq173207 {
  TGenericSeq Sup;
  TY104488 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, nospquoteShellWindows)(NimStringDesc* s);
N_NIMCALL(NIM_BOOL, contains_100033)(NimStringDesc* s, TY81010 chars);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, nospquoteShellPosix)(NimStringDesc* s);
N_NIMCALL(NIM_BOOL, allcharsinset_99325)(NimStringDesc* s, TY81010 theset);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, nospquoteShell)(NimStringDesc* s);
N_NIMCALL(Processobj192404*, startcmd_192631)(NimStringDesc* command, NU8 options);
N_NIMCALL(NI, nospprocessID)(Processobj192404* p);
N_NIMCALL(int, nospinputHandle)(Processobj192404* p);
N_NIMCALL(int, nospoutputHandle)(Processobj192404* p);
N_NIMCALL(int, nosperrorHandle)(Processobj192404* p);
N_NIMCALL(NI, nospcountProcessors)(void);
N_NIMCALL(NI, ncpicountProcessors)(void);
N_NIMCALL(NI, nospexecProcesses)(NimStringDesc** cmds, NI cmdsLen0, NU8 options_192709, NI n, TY192711 beforerunevent, TY192715 afterrunevent);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP915)(void* p, NI op);
N_NIMCALL(void, TMP916)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_54219)(Cell47905* c);
static N_INLINE(NIM_BOOL, canbecycleroot_51858)(Cell47905* c);
static N_INLINE(void, rtladdcycleroot_52620)(Cell47905* c);
N_NOINLINE(void, incl_48647)(Cellset47917* s, Cell47905* cell);
static N_INLINE(Cell47905*, usrtocell_51840)(void* usr);
static N_INLINE(void, decref_53801)(Cell47905* c);
static N_INLINE(void, rtladdzct_53401)(Cell47905* c);
N_NOINLINE(void, addzct_51817)(Cellseq47921* s, Cell47905* c);
N_NIMCALL(void, nossleep)(NI milsecs);
N_NIMCALL(NimStringDesc*, nospexecProcess)(NimStringDesc* command, NimStringDesc** args, NI argsLen0, Stringtableobj173209* env, NU8 options);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NIM_BOOL, readline_149916)(Streamobj149218* s, NimStringDesc** line);
N_NIMCALL(NCSTRING*, envtocstringarray_193603)(Stringtableobj173209* t);
N_NOCONV(void*, alloc0_7417)(NI size);
N_NIMCALL(NI, nstlen)(Stringtableobj173209* t);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NOCONV(void*, alloc_7401)(NI size);
N_NIMCALL(NCSTRING*, envtocstringarray_193636)(void);
N_NIMCALL(void, getenvvarsc_124402)(void);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_80210, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(pid_t, startprocessauxfork_193801)(Startprocessdata193703* data);
N_NOINLINE(void, raiseoserror_119803)(NI32 errorcode, NimStringDesc* additionalinfo);
N_NIMCALL(NI32, oslasterror_119819)(void);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_CDECL(void, startprocessafterfork_193804)(Startprocessdata193703* data);
N_NIMCALL(void, startprocessfail_194616)(Startprocessdata193703* data);
N_NOINLINE(void, nosraiseOSError)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(Processobj192404*, nospstartProcess)(NimStringDesc* command, NimStringDesc* workingdir, NimStringDesc** args, NI argsLen0, Stringtableobj173209* env, NU8 options);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(NCSTRING*, alloccstringarray_16201)(NimStringDesc** a, NI aLen0);
N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen0, NimStringDesc* sep);
N_NIMCALL(void, dealloccstringarray_16429)(NCSTRING* a);
N_NIMCALL(void, nospclose)(Processobj192404* p);
N_NIMCALL(void, close_149270)(Streamobj149218* s);
N_NIMCALL(void, nospsuspend)(Processobj192404* p);
N_NIMCALL(void, nospresume)(Processobj192404* p);
N_NIMCALL(NIM_BOOL, nosprunning)(Processobj192404* p);
N_NIMCALL(void, nospterminate)(Processobj192404* p);
N_NIMCALL(void, nospkill)(Processobj192404* p);
N_NIMCALL(NI, nospwaitForExit)(Processobj192404* p, NI timeout);
N_NIMCALL(NI, peekexitcode_192677)(Processobj192404* p);
N_NIMCALL(void, createstream_195426)(Streamobj149218** stream, int* handle, NU8 filemode);
N_NIMCALL(NIM_BOOL, open_15411)(FILE** f, int filehandle, NU8 mode);
N_NIMCALL(Filestreamobj150048*, newfilestream_150101)(FILE* f);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(Streamobj149218*, nospinputStream)(Processobj192404* p);
N_NIMCALL(Streamobj149218*, nospoutputStream)(Processobj192404* p);
N_NIMCALL(Streamobj149218*, nosperrorStream)(Processobj192404* p);
N_NIMCALL(NI, nospexecCmd)(NimStringDesc* command);
N_NIMCALL(void, createfdset_195601)(fd_set* fd, TY193001* s, NI* m);
N_NIMCALL(void, pruneprocessset_195823)(TY193001** s, fd_set* fd);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_NIMCALL(NI, select_193384)(TY193001** readfds, NI timeout);
N_NIMCALL(NIM_BOOL, hasdata_195931)(Processobj192404* p);
N_NIMCALL(void, execcmdex_196001)(NimStringDesc* command, NU8 options, TY196007* Result);
static NIM_CONST TY81010 TMP897 = {
0x00, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP898, "", 0);
STRING_LITERAL(TMP899, "\"", 1);
STRING_LITERAL(TMP900, "\\\"", 2);
STRING_LITERAL(TMP902, "len(a) == L string modified while iterating over it", 51);
NIM_CONST TY81010 safeunixchars_192448 = {
0x00, 0x00, 0x00, 0x00, 0x20, 0xE8, 0xFF, 0x27,
0xFF, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP903, "\'\'", 2);
static NIM_CONST TY81010 TMP905 = {
0x00, 0x00, 0x00, 0x00, 0x20, 0xE8, 0xFF, 0x27,
0xFF, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TMP906, "\'", 1);
STRING_LITERAL(TMP908, "\'\"\'\"\'", 5);
STRING_LITERAL(TMP909, "\012  0 < n ", 9);
static NIM_CONST TY192711 TMP918 = {NIM_NIL,NIM_NIL};
static NIM_CONST TY192715 TMP926 = {NIM_NIL,NIM_NIL};
STRING_LITERAL(TMP937, "", 0);
STRING_LITERAL(TMP938, "\012", 1);
STRING_LITERAL(TMP941, "=", 1);
STRING_LITERAL(TMP960, "Could not find command: \'$1\'. OS error: $2", 42);
STRING_LITERAL(TMP961, "/bin/sh", 7);
STRING_LITERAL(TMP962, "-c", 2);
STRING_LITERAL(TMP963, "len(args) == 0 `args` has to be empty when using poEvalCommand.", 63);
STRING_LITERAL(TMP967, " ", 1);
STRING_LITERAL(TMP969, "len(a) == L seq modified while iterating over it", 48);
NIM_CONST TY196007 TMP977 = {((NimStringDesc*) &TMP937),
((NI) -1)}
;
extern TFrame* frameptr_19436;
extern TNimType NTI3608; /* RootObj */
TNimType NTI192404; /* ProcessObj */
extern TNimType NTI15008; /* FileHandle */
extern TNimType NTI149216; /* Stream */
extern TNimType NTI109274; /* Pid */
extern TNimType NTI7208; /* cint */
TNimType NTI192402; /* ProcessOption */
TNimType NTI192634; /* set[ProcessOption] */
TNimType NTI192406; /* Process */
TNimType NTI193001; /* seq[Process] */
extern Gcheap50218 gch_50259;
extern TY15805* environment_124203;
extern TSafePoint* exchandler_19437;
extern TNimType NTI15805; /* seq[string] */

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(NimStringDesc*, nospquoteShellWindows)(NimStringDesc* s) {
	NimStringDesc* result;
	NIM_BOOL needquote;
	NIM_BOOL LOC1;
	NimStringDesc* backslashbuff;
	nimfr("quoteShellWindows", "osproc.nim")
	result = 0;
	nimln(67, "osproc.nim");
	LOC1 = 0;
	nimln(1098, "system.nim");
	LOC1 = contains_100033(s, TMP897);
	if (LOC1) goto LA2;
	nimln(67, "osproc.nim");
	LOC1 = ((s ? s->Sup.len : 0) == ((NI) 0));
	LA2: ;
	needquote = LOC1;
	nimln(69, "osproc.nim");
	result = copyString(((NimStringDesc*) &TMP898));
	nimln(70, "osproc.nim");
	backslashbuff = copyString(((NimStringDesc*) &TMP898));
	nimln(71, "osproc.nim");
	{
		if (!needquote) goto LA5;
		nimln(72, "osproc.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP899));
	}
	LA5: ;
	{
		NIM_CHAR c_192437;
		NI i_192441;
		NI L_192443;
		c_192437 = 0;
		nimln(3379, "system.nim");
		i_192441 = ((NI) 0);
		nimln(3380, "system.nim");
		L_192443 = (s ? s->Sup.len : 0);
		{
			nimln(3381, "system.nim");
			while (1) {
				NI TMP901;
				if (!(i_192441 < L_192443)) goto LA9;
				nimln(3382, "system.nim");
				if ((NU)(i_192441) > (NU)(s->Sup.len)) raiseIndexError();
				c_192437 = s->data[i_192441];
				nimln(75, "osproc.nim");
				{
					if (!((NU8)(c_192437) == (NU8)(92))) goto LA12;
					nimln(76, "osproc.nim");
					backslashbuff = addChar(backslashbuff, c_192437);
				}
				goto LA10;
				LA12: ;
				{
					nimln(77, "osproc.nim");
					if (!((NU8)(c_192437) == (NU8)(34))) goto LA15;
					nimln(78, "osproc.nim");
					result = resizeString(result, backslashbuff->Sup.len + 0);
appendString(result, backslashbuff);
					nimln(79, "osproc.nim");
					result = resizeString(result, backslashbuff->Sup.len + 0);
appendString(result, backslashbuff);
					nimln(80, "osproc.nim");
					backslashbuff = setLengthStr(backslashbuff, ((NI) 0));
					nimln(81, "osproc.nim");
					result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP900));
				}
				goto LA10;
				LA15: ;
				{
					nimln(83, "osproc.nim");
					{
						nimln(349, "system.nim");
						nimln(83, "osproc.nim");
						if (!!(((backslashbuff ? backslashbuff->Sup.len : 0) == ((NI) 0)))) goto LA20;
						nimln(84, "osproc.nim");
						result = resizeString(result, backslashbuff->Sup.len + 0);
appendString(result, backslashbuff);
						nimln(85, "osproc.nim");
						backslashbuff = setLengthStr(backslashbuff, ((NI) 0));
					}
					LA20: ;
					nimln(86, "osproc.nim");
					result = addChar(result, c_192437);
				}
				LA10: ;
				nimln(3383, "system.nim");
				TMP901 = addInt(i_192441, ((NI) 1));
				i_192441 = (NI)(TMP901);
				nimln(3384, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L_192443))) goto LA24;
					failedassertimpl_89116(((NimStringDesc*) &TMP902));
				}
				LA24: ;
			} LA9: ;
		}
	}
	nimln(88, "osproc.nim");
	{
		if (!needquote) goto LA28;
		nimln(89, "osproc.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP899));
	}
	LA28: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nospquoteShellPosix)(NimStringDesc* s) {
	NimStringDesc* result;
	NIM_BOOL safe;
	nimfr("quoteShellPosix", "osproc.nim")
{	result = 0;
	nimln(96, "osproc.nim");
	{
		if (!((s ? s->Sup.len : 0) == ((NI) 0))) goto LA3;
		nimln(97, "osproc.nim");
		result = copyString(((NimStringDesc*) &TMP903));
		goto BeforeRet;
	}
	LA3: ;
	nimln(99, "osproc.nim");
	safe = allcharsinset_99325(s, TMP905);
	nimln(101, "osproc.nim");
	{
		if (!safe) goto LA7;
		nimln(102, "osproc.nim");
		result = copyString(s);
		goto BeforeRet;
	}
	goto LA5;
	LA7: ;
	{
		NimStringDesc* LOC10;
		NimStringDesc* LOC11;
		nimln(104, "osproc.nim");
		LOC10 = 0;
		LOC11 = 0;
		LOC11 = nsuReplaceStr(s, ((NimStringDesc*) &TMP906), ((NimStringDesc*) &TMP908));
		LOC10 = rawNewString(LOC11->Sup.len + 2);
appendString(LOC10, ((NimStringDesc*) &TMP906));
appendString(LOC10, LOC11);
appendString(LOC10, ((NimStringDesc*) &TMP906));
		result = LOC10;
		goto BeforeRet;
	}
	LA5: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nospquoteShell)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr("quoteShell", "osproc.nim")
{	result = 0;
	nimln(111, "osproc.nim");
	result = nospquoteShellPosix(s);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Processobj192404*, startcmd_192631)(NimStringDesc* command, NU8 options) {
	Processobj192404* result;
	TY192625 LOC1;
	nimfr("startCmd", "osproc.nim")
	result = 0;
	nimln(175, "osproc.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	result = nospstartProcess(command, ((NimStringDesc*) &TMP898), LOC1, 0, NIM_NIL, (options | 4));
	popFrame();
	return result;
}

N_NIMCALL(NI, nospprocessID)(Processobj192404* p) {
	NI result;
	nimfr("processID", "osproc.nim")
{	result = 0;
	nimln(200, "osproc.nim");
	result = (*p).id;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(int, nospinputHandle)(Processobj192404* p) {
	int result;
	nimfr("inputHandle", "osproc.nim")
	result = 0;
	nimln(236, "osproc.nim");
	result = (*p).inhandle;
	popFrame();
	return result;
}

N_NIMCALL(int, nospoutputHandle)(Processobj192404* p) {
	int result;
	nimfr("outputHandle", "osproc.nim")
	result = 0;
	nimln(244, "osproc.nim");
	result = (*p).outhandle;
	popFrame();
	return result;
}

N_NIMCALL(int, nosperrorHandle)(Processobj192404* p) {
	int result;
	nimfr("errorHandle", "osproc.nim")
	result = 0;
	nimln(252, "osproc.nim");
	result = (*p).errhandle;
	popFrame();
	return result;
}

N_NIMCALL(NI, nospcountProcessors)(void) {
	NI result;
	nimfr("countProcessors", "osproc.nim")
	result = 0;
	nimln(257, "osproc.nim");
	result = ncpicountProcessors();
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP915)(void* p, NI op) {
	Processobj192404* a;
	a = (Processobj192404*)p;
	nimGCvisit((void*)(*a).instream, op);
	nimGCvisit((void*)(*a).outstream, op);
	nimGCvisit((void*)(*a).errstream, op);
}
N_NIMCALL(void, TMP916)(void* p, NI op) {
	TY193001* a;
	NI LOC1;
	a = (TY193001*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_51858)(Cell47905* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1U<<((NU)(((NU8) 1))&7U)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_52620)(Cell47905* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_48647((&gch_50259.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_54219)(Cell47905* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_51858(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_52620(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(Cell47905*, usrtocell_51840)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53401)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_51817((&gch_50259.zct), c);
	popFrame();
}

static N_INLINE(void, decref_53801)(Cell47905* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_53401(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_51858(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_52620(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell47905* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_51840(src);
		incref_54219(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell47905* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_51840((*dest));
		decref_53801(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NI, nospexecProcesses)(NimStringDesc** cmds, NI cmdsLen0, NU8 options_192709, NI n, TY192711 beforerunevent, TY192715 afterrunevent) {
	NI result;
	NU8 options;
	nimfr("execProcesses", "osproc.nim")
	result = 0;
	nimln(271, "osproc.nim");
	options = (options_192709 & ~ 16);
	nimln(273, "osproc.nim");
	{
		if (!!((((NI) 0) < n))) goto LA3;
		failedassertimpl_89116(((NimStringDesc*) &TMP909));
	}
	LA3: ;
	nimln(274, "osproc.nim");
	{
		TY193001* q;
		NI m;
		NI i;
		nimln(357, "system.nim");
		if (!(((NI) 1) < n)) goto LA7;
		q = 0;
		nimln(276, "osproc.nim");
		q = (TY193001*) newSeq((&NTI193001), ((NI)chckRange(n, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(277, "osproc.nim");
		m = ((n <= cmdsLen0) ? n : cmdsLen0);
		{
			NI i_193034;
			NI HEX3Atmp_193352;
			NI TMP917;
			NI res_193355;
			i_193034 = 0;
			HEX3Atmp_193352 = 0;
			nimln(278, "osproc.nim");
			TMP917 = subInt(m, ((NI) 1));
			HEX3Atmp_193352 = (NI)(TMP917);
			nimln(1874, "system.nim");
			res_193355 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					TY192625 LOC16;
					NI TMP920;
					if (!(res_193355 <= HEX3Atmp_193352)) goto LA11;
					nimln(1876, "system.nim");
					i_193034 = res_193355;
					nimln(279, "osproc.nim");
					{
						nimln(349, "system.nim");
						if (!!((beforerunevent.ClPrc == TMP918.ClPrc && beforerunevent.ClEnv == TMP918.ClEnv))) goto LA14;
						nimln(280, "osproc.nim");
						beforerunevent.ClEnv? beforerunevent.ClPrc(i_193034, beforerunevent.ClEnv):((TMP919)(beforerunevent.ClPrc))(i_193034);
					}
					LA14: ;
					nimln(281, "osproc.nim");
					if ((NU)(i_193034) >= (NU)(q->Sup.len)) raiseIndexError();
					if ((NU)(i_193034) >= (NU)(cmdsLen0)) raiseIndexError();
					memset((void*)LOC16, 0, sizeof(LOC16));
					asgnRef((void**) (&q->data[i_193034]), nospstartProcess(cmds[i_193034], ((NimStringDesc*) &TMP898), LOC16, 0, NIM_NIL, (options | 4)));
					nimln(1895, "system.nim");
					TMP920 = addInt(res_193355, ((NI) 1));
					res_193355 = (NI)(TMP920);
				} LA11: ;
			}
		}
		nimln(300, "osproc.nim");
		i = m;
		{
			nimln(301, "osproc.nim");
			while (1) {
				if (!(i <= (cmdsLen0-1))) goto LA18;
				nimln(302, "osproc.nim");
				nossleep(((NI) 50));
				{
					NI r_193212;
					NI HEX3Atmp_193361;
					NI TMP925;
					NI res_193364;
					r_193212 = 0;
					HEX3Atmp_193361 = 0;
					nimln(303, "osproc.nim");
					TMP925 = subInt(n, ((NI) 1));
					HEX3Atmp_193361 = (NI)(TMP925);
					nimln(1874, "system.nim");
					res_193364 = ((NI) 0);
					{
						nimln(1875, "system.nim");
						while (1) {
							NI TMP930;
							if (!(res_193364 <= HEX3Atmp_193361)) goto LA21;
							nimln(1876, "system.nim");
							r_193212 = res_193364;
							nimln(304, "osproc.nim");
							{
								NIM_BOOL LOC24;
								NI LOC27;
								TY192625 LOC40;
								NI TMP929;
								if ((NU)(r_193212) >= (NU)(q->Sup.len)) raiseIndexError();
								LOC24 = 0;
								LOC24 = nosprunning(q->data[r_193212]);
								if (!!(LOC24)) goto LA25;
								nimln(306, "osproc.nim");
								if ((NU)(r_193212) >= (NU)(q->Sup.len)) raiseIndexError();
								LOC27 = 0;
								LOC27 = nospwaitForExit(q->data[r_193212], ((NI) -1));
								result = ((LOC27 >= result) ? LOC27 : result);
								nimln(307, "osproc.nim");
								{
									nimln(349, "system.nim");
									if (!!((afterrunevent.ClPrc == TMP926.ClPrc && afterrunevent.ClEnv == TMP926.ClEnv))) goto LA30;
									nimln(307, "osproc.nim");
									if ((NU)(r_193212) >= (NU)(q->Sup.len)) raiseIndexError();
									afterrunevent.ClEnv? afterrunevent.ClPrc(r_193212, q->data[r_193212], afterrunevent.ClEnv):((TMP927)(afterrunevent.ClPrc))(r_193212, q->data[r_193212]);
								}
								LA30: ;
								nimln(308, "osproc.nim");
								{
									nimln(349, "system.nim");
									if ((NU)(r_193212) >= (NU)(q->Sup.len)) raiseIndexError();
									if (!!((q->data[r_193212] == NIM_NIL))) goto LA34;
									nimln(308, "osproc.nim");
									if ((NU)(r_193212) >= (NU)(q->Sup.len)) raiseIndexError();
									nospclose(q->data[r_193212]);
								}
								LA34: ;
								nimln(309, "osproc.nim");
								{
									nimln(349, "system.nim");
									if (!!((beforerunevent.ClPrc == TMP918.ClPrc && beforerunevent.ClEnv == TMP918.ClEnv))) goto LA38;
									nimln(310, "osproc.nim");
									beforerunevent.ClEnv? beforerunevent.ClPrc(i, beforerunevent.ClEnv):((TMP928)(beforerunevent.ClPrc))(i);
								}
								LA38: ;
								nimln(311, "osproc.nim");
								if ((NU)(r_193212) >= (NU)(q->Sup.len)) raiseIndexError();
								if ((NU)(i) >= (NU)(cmdsLen0)) raiseIndexError();
								memset((void*)LOC40, 0, sizeof(LOC40));
								asgnRef((void**) (&q->data[r_193212]), nospstartProcess(cmds[i], ((NimStringDesc*) &TMP898), LOC40, 0, NIM_NIL, (options | 4)));
								nimln(312, "osproc.nim");
								TMP929 = addInt(i, ((NI) 1));
								i = (NI)(TMP929);
								nimln(313, "osproc.nim");
								{
									nimln(357, "system.nim");
									nimln(313, "osproc.nim");
									if (!((cmdsLen0-1) < i)) goto LA43;
									goto LA19;
								}
								LA43: ;
							}
							LA25: ;
							nimln(1895, "system.nim");
							TMP930 = addInt(res_193364, ((NI) 1));
							res_193364 = (NI)(TMP930);
						} LA21: ;
					}
				} LA19: ;
			} LA18: ;
		}
		{
			NI j_193278;
			NI HEX3Atmp_193369;
			NI TMP931;
			NI res_193372;
			j_193278 = 0;
			HEX3Atmp_193369 = 0;
			nimln(314, "osproc.nim");
			TMP931 = subInt(m, ((NI) 1));
			HEX3Atmp_193369 = (NI)(TMP931);
			nimln(1874, "system.nim");
			res_193372 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					NI LOC48;
					NI TMP933;
					if (!(res_193372 <= HEX3Atmp_193369)) goto LA47;
					nimln(1876, "system.nim");
					j_193278 = res_193372;
					nimln(315, "osproc.nim");
					if ((NU)(j_193278) >= (NU)(q->Sup.len)) raiseIndexError();
					LOC48 = 0;
					LOC48 = nospwaitForExit(q->data[j_193278], ((NI) -1));
					result = ((LOC48 >= result) ? LOC48 : result);
					nimln(316, "osproc.nim");
					{
						nimln(349, "system.nim");
						if (!!((afterrunevent.ClPrc == TMP926.ClPrc && afterrunevent.ClEnv == TMP926.ClEnv))) goto LA51;
						nimln(316, "osproc.nim");
						if ((NU)(j_193278) >= (NU)(q->Sup.len)) raiseIndexError();
						afterrunevent.ClEnv? afterrunevent.ClPrc(j_193278, q->data[j_193278], afterrunevent.ClEnv):((TMP932)(afterrunevent.ClPrc))(j_193278, q->data[j_193278]);
					}
					LA51: ;
					nimln(317, "osproc.nim");
					{
						nimln(349, "system.nim");
						if ((NU)(j_193278) >= (NU)(q->Sup.len)) raiseIndexError();
						if (!!((q->data[j_193278] == NIM_NIL))) goto LA55;
						nimln(317, "osproc.nim");
						if ((NU)(j_193278) >= (NU)(q->Sup.len)) raiseIndexError();
						nospclose(q->data[j_193278]);
					}
					LA55: ;
					nimln(1895, "system.nim");
					TMP933 = addInt(res_193372, ((NI) 1));
					res_193372 = (NI)(TMP933);
				} LA47: ;
			}
		}
	}
	goto LA5;
	LA7: ;
	{
		{
			NI i_193313;
			NI HEX3Atmp_193377;
			NI res_193380;
			i_193313 = 0;
			HEX3Atmp_193377 = 0;
			nimln(319, "osproc.nim");
			HEX3Atmp_193377 = (cmdsLen0-1);
			nimln(1874, "system.nim");
			res_193380 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					Processobj192404* p;
					TY192625 LOC65;
					NI LOC66;
					NI TMP936;
					if (!(res_193380 <= HEX3Atmp_193377)) goto LA60;
					nimln(1876, "system.nim");
					i_193313 = res_193380;
					nimln(320, "osproc.nim");
					{
						nimln(349, "system.nim");
						if (!!((beforerunevent.ClPrc == TMP918.ClPrc && beforerunevent.ClEnv == TMP918.ClEnv))) goto LA63;
						nimln(321, "osproc.nim");
						beforerunevent.ClEnv? beforerunevent.ClPrc(i_193313, beforerunevent.ClEnv):((TMP934)(beforerunevent.ClPrc))(i_193313);
					}
					LA63: ;
					nimln(322, "osproc.nim");
					if ((NU)(i_193313) >= (NU)(cmdsLen0)) raiseIndexError();
					memset((void*)LOC65, 0, sizeof(LOC65));
					p = nospstartProcess(cmds[i_193313], ((NimStringDesc*) &TMP898), LOC65, 0, NIM_NIL, (options | 4));
					nimln(323, "osproc.nim");
					LOC66 = 0;
					LOC66 = nospwaitForExit(p, ((NI) -1));
					result = ((LOC66 >= result) ? LOC66 : result);
					nimln(324, "osproc.nim");
					{
						nimln(349, "system.nim");
						if (!!((afterrunevent.ClPrc == TMP926.ClPrc && afterrunevent.ClEnv == TMP926.ClEnv))) goto LA69;
						nimln(324, "osproc.nim");
						afterrunevent.ClEnv? afterrunevent.ClPrc(i_193313, p, afterrunevent.ClEnv):((TMP935)(afterrunevent.ClPrc))(i_193313, p);
					}
					LA69: ;
					nimln(325, "osproc.nim");
					nospclose(p);
					nimln(1895, "system.nim");
					TMP936 = addInt(res_193380, ((NI) 1));
					res_193380 = (NI)(TMP936);
				} LA60: ;
			}
		}
	}
	LA5: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, nospexecProcess)(NimStringDesc* command, NimStringDesc** args, NI argsLen0, Stringtableobj173209* env, NU8 options) {
	NimStringDesc* result;
	Processobj192404* p;
	Streamobj149218* outp;
	NimStringDesc* line;
	nimfr("execProcess", "osproc.nim")
	result = 0;
	nimln(343, "osproc.nim");
	p = nospstartProcess(command, ((NimStringDesc*) &TMP898), args, argsLen0, env, options);
	nimln(344, "osproc.nim");
	outp = nospoutputStream(p);
	nimln(345, "osproc.nim");
	result = copyString(((NimStringDesc*) &TMP937));
	nimln(346, "osproc.nim");
	line = rawNewString(((NI) 120));
	{
		nimln(347, "osproc.nim");
		while (1) {
			nimln(349, "osproc.nim");
			{
				NIM_BOOL LOC5;
				LOC5 = 0;
				LOC5 = readline_149916(outp, (&line));
				if (!LOC5) goto LA6;
				nimln(350, "osproc.nim");
				result = resizeString(result, line->Sup.len + 0);
appendString(result, line);
				nimln(351, "osproc.nim");
				result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP938));
			}
			goto LA3;
			LA6: ;
			{
				NIM_BOOL LOC9;
				nimln(352, "osproc.nim");
				LOC9 = 0;
				LOC9 = nosprunning(p);
				if (!!(LOC9)) goto LA10;
				goto LA1;
			}
			goto LA3;
			LA10: ;
			LA3: ;
		}
	} LA1: ;
	nimln(353, "osproc.nim");
	nospclose(p);
	popFrame();
	return result;
}

N_NIMCALL(NCSTRING*, envtocstringarray_193603)(Stringtableobj173209* t) {
	NCSTRING* result;
	NI LOC1;
	NI TMP939;
	NI TMP940;
	void* LOC2;
	NI i;
	nimfr("envToCStringArray", "osproc.nim")
	result = 0;
	nimln(675, "osproc.nim");
	LOC1 = 0;
	LOC1 = nstlen(t);
	TMP939 = addInt(LOC1, ((NI) 1));
	TMP940 = mulInt((NI)(TMP939), ((NI) 8));
	LOC2 = 0;
	LOC2 = alloc0_7417(((NI)chckRange((NI)(TMP940), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	result = ((NCSTRING*) (LOC2));
	nimln(676, "osproc.nim");
	i = ((NI) 0);
	{
		NimStringDesc* key_193609;
		NimStringDesc* val_193610;
		key_193609 = 0;
		val_193610 = 0;
		{
			NI h_193629;
			NI HEX3Atmp_193631;
			NI res_193633;
			h_193629 = 0;
			HEX3Atmp_193631 = 0;
			nimln(43, "strtabs.nim");
			HEX3Atmp_193631 = ((*t).data ? ((*t).data->Sup.len-1) : -1);
			nimln(1874, "system.nim");
			res_193633 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					NI TMP945;
					if (!(res_193633 <= HEX3Atmp_193631)) goto LA6;
					nimln(1876, "system.nim");
					h_193629 = res_193633;
					nimln(44, "strtabs.nim");
					{
						NimStringDesc* x;
						NimStringDesc* LOC11;
						NI TMP942;
						void* LOC12;
						NI TMP943;
						NI TMP944;
						if ((NU)(h_193629) >= (NU)((*t).data->Sup.len)) raiseIndexError();
						if (!!((*t).data->data[h_193629].Field0 == 0)) goto LA9;
						nimln(45, "strtabs.nim");
						if ((NU)(h_193629) >= (NU)((*t).data->Sup.len)) raiseIndexError();
						key_193609 = (*t).data->data[h_193629].Field0;
						if ((NU)(h_193629) >= (NU)((*t).data->Sup.len)) raiseIndexError();
						val_193610 = (*t).data->data[h_193629].Field1;
						nimln(678, "osproc.nim");
						LOC11 = 0;
						LOC11 = rawNewString(key_193609->Sup.len + val_193610->Sup.len + 1);
appendString(LOC11, key_193609);
appendString(LOC11, ((NimStringDesc*) &TMP941));
appendString(LOC11, val_193610);
						x = LOC11;
						nimln(679, "osproc.nim");
						if ((NU)(i) > (NU)(100000000)) raiseIndexError();
						TMP942 = addInt((x ? x->Sup.len : 0), ((NI) 1));
						LOC12 = 0;
						LOC12 = alloc_7401(((NI)chckRange((NI)(TMP942), ((NI) 0), ((NI) IL64(9223372036854775807)))));
						result[(i)- 0] = ((NCSTRING) (LOC12));
						nimln(680, "osproc.nim");
						if ((NU)(i) > (NU)(100000000)) raiseIndexError();
						if ((NU)(((NI) 0)) > (NU)(x->Sup.len)) raiseIndexError();
						TMP943 = addInt((x ? x->Sup.len : 0), ((NI) 1));
						memcpy(((void*) (result[(i)- 0])), ((void*) ((&x->data[((NI) 0)]))), ((NI)chckRange((NI)(TMP943), ((NI) 0), ((NI) IL64(9223372036854775807)))));
						nimln(681, "osproc.nim");
						TMP944 = addInt(i, ((NI) 1));
						i = (NI)(TMP944);
					}
					LA9: ;
					nimln(1895, "system.nim");
					TMP945 = addInt(res_193633, ((NI) 1));
					res_193633 = (NI)(TMP945);
				} LA6: ;
			}
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NCSTRING*, envtocstringarray_193636)(void) {
	NCSTRING* result;
	NI counter;
	NI TMP950;
	NI TMP951;
	void* LOC5;
	NI i;
	nimfr("envToCStringArray", "osproc.nim")
	result = 0;
	nimln(684, "osproc.nim");
	counter = ((NI) 0);
	{
		NimStringDesc* key_193640;
		NimStringDesc* val_193641;
		key_193640 = 0;
		val_193641 = 0;
		nimln(759, "os.nim");
		getenvvarsc_124402();
		{
			NI i_193670;
			NI HEX3Atmp_193672;
			NI res_193674;
			i_193670 = 0;
			HEX3Atmp_193672 = 0;
			nimln(760, "os.nim");
			HEX3Atmp_193672 = (environment_124203 ? (environment_124203->Sup.len-1) : -1);
			nimln(1874, "system.nim");
			res_193674 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					NI p_193678;
					NI TMP946;
					NI TMP947;
					NI TMP948;
					NI TMP949;
					if (!(res_193674 <= HEX3Atmp_193672)) goto LA4;
					nimln(1876, "system.nim");
					i_193670 = res_193674;
					nimln(761, "os.nim");
					if ((NU)(i_193670) >= (NU)(environment_124203->Sup.len)) raiseIndexError();
					p_193678 = nsuFindChar(environment_124203->data[i_193670], 61, ((NI) 0));
					nimln(762, "os.nim");
					if ((NU)(i_193670) >= (NU)(environment_124203->Sup.len)) raiseIndexError();
					TMP946 = subInt(p_193678, ((NI) 1));
					key_193640 = copyStrLast(environment_124203->data[i_193670], ((NI) 0), (NI)(TMP946));
					nimln(763, "os.nim");
					if ((NU)(i_193670) >= (NU)(environment_124203->Sup.len)) raiseIndexError();
					TMP947 = addInt(p_193678, ((NI) 1));
					val_193641 = copyStr(environment_124203->data[i_193670], (NI)(TMP947));
					nimln(685, "osproc.nim");
					TMP948 = addInt(counter, ((NI) 1));
					counter = (NI)(TMP948);
					nimln(1895, "system.nim");
					TMP949 = addInt(res_193674, ((NI) 1));
					res_193674 = (NI)(TMP949);
				} LA4: ;
			}
		}
	}
	nimln(686, "osproc.nim");
	TMP950 = addInt(counter, ((NI) 1));
	TMP951 = mulInt((NI)(TMP950), ((NI) 8));
	LOC5 = 0;
	LOC5 = alloc0_7417(((NI)chckRange((NI)(TMP951), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	result = ((NCSTRING*) (LOC5));
	nimln(687, "osproc.nim");
	i = ((NI) 0);
	{
		NimStringDesc* key_193653;
		NimStringDesc* val_193654;
		key_193653 = 0;
		val_193654 = 0;
		nimln(759, "os.nim");
		getenvvarsc_124402();
		{
			NI i_193691;
			NI HEX3Atmp_193693;
			NI res_193695;
			i_193691 = 0;
			HEX3Atmp_193693 = 0;
			nimln(760, "os.nim");
			HEX3Atmp_193693 = (environment_124203 ? (environment_124203->Sup.len-1) : -1);
			nimln(1874, "system.nim");
			res_193695 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					NI p_193699;
					NI TMP952;
					NI TMP953;
					NimStringDesc* x;
					NimStringDesc* LOC10;
					NI TMP954;
					void* LOC11;
					NI TMP955;
					NI TMP956;
					NI TMP957;
					if (!(res_193695 <= HEX3Atmp_193693)) goto LA9;
					nimln(1876, "system.nim");
					i_193691 = res_193695;
					nimln(761, "os.nim");
					if ((NU)(i_193691) >= (NU)(environment_124203->Sup.len)) raiseIndexError();
					p_193699 = nsuFindChar(environment_124203->data[i_193691], 61, ((NI) 0));
					nimln(762, "os.nim");
					if ((NU)(i_193691) >= (NU)(environment_124203->Sup.len)) raiseIndexError();
					TMP952 = subInt(p_193699, ((NI) 1));
					key_193653 = copyStrLast(environment_124203->data[i_193691], ((NI) 0), (NI)(TMP952));
					nimln(763, "os.nim");
					if ((NU)(i_193691) >= (NU)(environment_124203->Sup.len)) raiseIndexError();
					TMP953 = addInt(p_193699, ((NI) 1));
					val_193654 = copyStr(environment_124203->data[i_193691], (NI)(TMP953));
					nimln(689, "osproc.nim");
					LOC10 = 0;
					LOC10 = rawNewString(key_193653->Sup.len + val_193654->Sup.len + 1);
appendString(LOC10, key_193653);
appendString(LOC10, ((NimStringDesc*) &TMP941));
appendString(LOC10, val_193654);
					x = LOC10;
					nimln(690, "osproc.nim");
					if ((NU)(i) > (NU)(100000000)) raiseIndexError();
					TMP954 = addInt((x ? x->Sup.len : 0), ((NI) 1));
					LOC11 = 0;
					LOC11 = alloc_7401(((NI)chckRange((NI)(TMP954), ((NI) 0), ((NI) IL64(9223372036854775807)))));
					result[(i)- 0] = ((NCSTRING) (LOC11));
					nimln(691, "osproc.nim");
					if ((NU)(i) > (NU)(100000000)) raiseIndexError();
					if ((NU)(((NI) 0)) > (NU)(x->Sup.len)) raiseIndexError();
					TMP955 = addInt((x ? x->Sup.len : 0), ((NI) 1));
					memcpy(((void*) (result[(i)- 0])), ((void*) ((&x->data[((NI) 0)]))), ((NI)chckRange((NI)(TMP955), ((NI) 0), ((NI) IL64(9223372036854775807)))));
					nimln(692, "osproc.nim");
					TMP956 = addInt(i, ((NI) 1));
					i = (NI)(TMP956);
					nimln(1895, "system.nim");
					TMP957 = addInt(res_193695, ((NI) 1));
					res_193695 = (NI)(TMP957);
				} LA9: ;
			}
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_19437;
	exchandler_19437 = s;
}

N_NIMCALL(void, startprocessfail_194616)(Startprocessdata193703* data) {
	int error;
	NI LOC1;
	error = errno;
	LOC1 = 0;
	LOC1 = write((*data).perrorpipe[(((NI) 1))- 0], ((void*) ((&error))), ((NI) 4));
	_exit(((NI) 1));
}

N_CDECL(void, startprocessafterfork_193804)(Startprocessdata193703* data) {
	int LOC42;
	int LOC43;
	{
		int LOC5;
		int LOC11;
		int LOC17;
		if (!!((*data).optionpoparentstreams)) goto LA3;
		LOC5 = 0;
		LOC5 = close((*data).pstdin[(((NI) 1))- 0]);
		{
			int LOC8;
			LOC8 = 0;
			LOC8 = dup2((*data).pstdin[(((NI) 0))- 0], ((int) 0));
			if (!(LOC8 < ((NI32) 0))) goto LA9;
			startprocessfail_194616(data);
		}
		LA9: ;
		LOC11 = 0;
		LOC11 = close((*data).pstdout[(((NI) 0))- 0]);
		{
			int LOC14;
			LOC14 = 0;
			LOC14 = dup2((*data).pstdout[(((NI) 1))- 0], ((int) 1));
			if (!(LOC14 < ((NI32) 0))) goto LA15;
			startprocessfail_194616(data);
		}
		LA15: ;
		LOC17 = 0;
		LOC17 = close((*data).pstderr[(((NI) 0))- 0]);
		{
			if (!(*data).optionpostderrtostdout) goto LA20;
			{
				int LOC24;
				LOC24 = 0;
				LOC24 = dup2((*data).pstdout[(((NI) 1))- 0], ((int) 2));
				if (!(LOC24 < ((NI32) 0))) goto LA25;
				startprocessfail_194616(data);
			}
			LA25: ;
		}
		goto LA18;
		LA20: ;
		{
			{
				int LOC30;
				LOC30 = 0;
				LOC30 = dup2((*data).pstderr[(((NI) 1))- 0], ((int) 2));
				if (!(LOC30 < ((NI32) 0))) goto LA31;
				startprocessfail_194616(data);
			}
			LA31: ;
		}
		LA18: ;
	}
	LA3: ;
	{
		if (!(((NI) 0) < ((*data).workingdir ? strlen((*data).workingdir) : 0))) goto LA35;
		{
			int LOC39;
			LOC39 = 0;
			LOC39 = chdir((*data).workingdir);
			if (!(LOC39 < ((NI32) 0))) goto LA40;
			startprocessfail_194616(data);
		}
		LA40: ;
	}
	LA35: ;
	LOC42 = 0;
	LOC42 = close((*data).perrorpipe[(((NI) 0))- 0]);
	LOC43 = 0;
	LOC43 = fcntl((*data).perrorpipe[(((NI) 1))- 0], F_SETFD, FD_CLOEXEC);
	{
		int LOC48;
		if (!(*data).optionpousepath) goto LA46;
		LOC48 = 0;
		LOC48 = execvpe((*data).syscommand, (*data).sysargs, (*data).sysenv);
	}
	goto LA44;
	LA46: ;
	{
		int LOC50;
		LOC50 = 0;
		LOC50 = execve((*data).syscommand, (*data).sysargs, (*data).sysenv);
	}
	LA44: ;
	startprocessfail_194616(data);
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_19437 = (*exchandler_19437).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_19436 = s;
}

N_NIMCALL(pid_t, startprocessauxfork_193801)(Startprocessdata193703* data) {
	pid_t volatile result;
	TSafePoint TMP958;
	nimfr("startProcessAuxFork", "osproc.nim")
{	result = 0;
	nimln(847, "osproc.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(847, "osproc.nim");
		LOC3 = 0;
		LOC3 = pipe((*data).perrorpipe);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		nimln(848, "osproc.nim");
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP898));
	}
	LA4: ;
	nimln(850, "osproc.nim");
	pushSafePoint(&TMP958);
	TMP958.status = setjmp(TMP958.context);
	if (TMP958.status == 0) {
		pid_t volatile pid;
		Startprocessdata193703 datacopy;
		int LOC12;
		int error;
		NI sizeread;
		int LOC25;
		pid = 0;
		nimln(854, "osproc.nim");
		datacopy = (*data);
		nimln(867, "osproc.nim");
		pid = fork();
		nimln(868, "osproc.nim");
		{
			if (!(pid == ((NI) 0))) goto LA10;
			nimln(869, "osproc.nim");
			startprocessafterfork_193804((&datacopy));
			nimln(870, "osproc.nim");
			_exit(((NI) 1));
		}
		LA10: ;
		nimln(872, "osproc.nim");
		LOC12 = 0;
		LOC12 = close((*data).perrorpipe[(((NI) 1))- 0]);
		nimln(873, "osproc.nim");
		{
			NI32 LOC17;
			if (!(pid < ((NI) 0))) goto LA15;
			LOC17 = 0;
			LOC17 = oslasterror_119819();
			raiseoserror_119803(LOC17, ((NimStringDesc*) &TMP898));
		}
		LA15: ;
		error = 0;
		nimln(876, "osproc.nim");
		sizeread = read((*data).perrorpipe[(((NI) 0))- 0], ((void*) ((&error))), ((NI) 4));
		nimln(877, "osproc.nim");
		{
			TY194612 LOC22;
			NCSTRING LOC23;
			NimStringDesc* LOC24;
			if (!(sizeread == ((NI) 4))) goto LA20;
			nimln(878, "osproc.nim");
			memset((void*)LOC22, 0, sizeof(LOC22));
			nimln(879, "osproc.nim");
			LOC22[0] = cstrToNimstr((*data).syscommand);
			LOC23 = 0;
			LOC23 = strerror(error);
			LOC22[1] = cstrToNimstr(LOC23);
			LOC24 = 0;
			LOC24 = nsuFormatOpenArray(((NimStringDesc*) &TMP960), LOC22, 2);
			nosraiseOSError(LOC24);
		}
		LA20: ;
		nimln(881, "osproc.nim");
		result = pid;
		popSafePoint();
		nimln(851, "osproc.nim");
		LOC25 = 0;
		LOC25 = close((*data).perrorpipe[(((NI) 0))- 0]);
		goto BeforeRet;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		int LOC28;
		LOC28 = 0;
		LOC28 = close((*data).perrorpipe[(((NI) 0))- 0]);
	}
	if (TMP958.status != 0) reraiseException();
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47905* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_51840(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_53401(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Processobj192404*, nospstartProcess)(NimStringDesc* command, NimStringDesc* workingdir, NimStringDesc** args, NI argsLen0, Stringtableobj173209* env, NU8 options) {
	Processobj192404* result;
	TY193709 pstdin;
	TY193709 pstdout;
	TY193709 pstderr;
	NimStringDesc* syscommand;
	TY15805* sysargsraw;
	pid_t volatile pid;
	NCSTRING* sysargs;
	TSafePoint TMP965;
	nimfr("startProcess", "osproc.nim")
	result = 0;
	memset((void*)pstdin, 0, sizeof(pstdin));
	memset((void*)pstdout, 0, sizeof(pstdout));
	memset((void*)pstderr, 0, sizeof(pstderr));
	nimln(725, "osproc.nim");
	result = (Processobj192404*) newObj((&NTI192406), sizeof(Processobj192404));
	(*result).Sup.m_type = (&NTI192404);
	nimln(726, "osproc.nim");
	(*result).options = options;
	nimln(727, "osproc.nim");
	(*result).exitcode = ((int) -3);
	nimln(728, "osproc.nim");
	{
		nimln(1104, "system.nim");
		if (!!(((options &(1U<<((NU)(((NU8) 4))&7U)))!=0))) goto LA3;
		nimln(729, "osproc.nim");
		{
			NIM_BOOL LOC7;
			NIM_BOOL LOC8;
			int LOC9;
			int LOC11;
			int LOC13;
			NI32 LOC16;
			LOC7 = 0;
			LOC8 = 0;
			nimln(349, "system.nim");
			nimln(729, "osproc.nim");
			LOC9 = 0;
			LOC9 = pipe(pstdin);
			LOC8 = !((LOC9 == ((NI32) 0)));
			if (LOC8) goto LA10;
			nimln(349, "system.nim");
			nimln(729, "osproc.nim");
			LOC11 = 0;
			LOC11 = pipe(pstdout);
			LOC8 = !((LOC11 == ((NI32) 0)));
			LA10: ;
			LOC7 = LOC8;
			if (LOC7) goto LA12;
			nimln(349, "system.nim");
			nimln(730, "osproc.nim");
			LOC13 = 0;
			LOC13 = pipe(pstderr);
			LOC7 = !((LOC13 == ((NI32) 0)));
			LA12: ;
			if (!LOC7) goto LA14;
			nimln(731, "osproc.nim");
			LOC16 = 0;
			LOC16 = oslasterror_119819();
			raiseoserror_119803(LOC16, ((NimStringDesc*) &TMP898));
		}
		LA14: ;
	}
	LA3: ;
	syscommand = 0;
	sysargsraw = 0;
	nimln(735, "osproc.nim");
	{
		TY193860 LOC21;
		NimStringDesc* LOC22;
		NimStringDesc* LOC23;
		NimStringDesc* LOC24;
		nimln(1098, "system.nim");
		if (!((options &(1U<<((NU)(((NU8) 2))&7U)))!=0)) goto LA19;
		nimln(736, "osproc.nim");
		syscommand = copyString(((NimStringDesc*) &TMP961));
		nimln(737, "osproc.nim");
		sysargsraw = (TY15805*) newSeq((&NTI15805), 3);
		memset((void*)LOC21, 0, sizeof(LOC21));
		LOC21[0] = copyString(syscommand);
		LOC21[1] = copyString(((NimStringDesc*) &TMP962));
		LOC21[2] = copyString(command);
		LOC22 = 0;
		LOC22 = sysargsraw->data[0]; sysargsraw->data[0] = copyStringRC1(LOC21[0]);
		if (LOC22) nimGCunrefNoCycle(LOC22);
		LOC23 = 0;
		LOC23 = sysargsraw->data[1]; sysargsraw->data[1] = copyStringRC1(LOC21[1]);
		if (LOC23) nimGCunrefNoCycle(LOC23);
		LOC24 = 0;
		LOC24 = sysargsraw->data[2]; sysargsraw->data[2] = copyStringRC1(LOC21[2]);
		if (LOC24) nimGCunrefNoCycle(LOC24);
		nimln(738, "osproc.nim");
		{
			if (!!((argsLen0 == ((NI) 0)))) goto LA27;
			failedassertimpl_89116(((NimStringDesc*) &TMP963));
		}
		LA27: ;
	}
	goto LA17;
	LA19: ;
	{
		TY194001 LOC30;
		NimStringDesc* LOC31;
		nimln(740, "osproc.nim");
		syscommand = copyString(command);
		nimln(741, "osproc.nim");
		sysargsraw = (TY15805*) newSeq((&NTI15805), 1);
		memset((void*)LOC30, 0, sizeof(LOC30));
		LOC30[0] = copyString(command);
		LOC31 = 0;
		LOC31 = sysargsraw->data[0]; sysargsraw->data[0] = copyStringRC1(LOC30[0]);
		if (LOC31) nimGCunrefNoCycle(LOC31);
		{
			NimStringDesc* arg_194021;
			NI i_194279;
			arg_194021 = 0;
			nimln(1965, "system.nim");
			i_194279 = ((NI) 0);
			{
				nimln(1966, "system.nim");
				while (1) {
					NimStringDesc* LOC35;
					NI TMP964;
					if (!(i_194279 < argsLen0)) goto LA34;
					nimln(1967, "system.nim");
					if ((NU)(i_194279) >= (NU)(argsLen0)) raiseIndexError();
					arg_194021 = args[i_194279];
					nimln(743, "osproc.nim");
					sysargsraw = (TY15805*) incrSeqV2(&(sysargsraw)->Sup, sizeof(NimStringDesc*));
					LOC35 = 0;
					LOC35 = sysargsraw->data[sysargsraw->Sup.len]; sysargsraw->data[sysargsraw->Sup.len] = copyStringRC1(arg_194021);
					if (LOC35) nimGCunrefNoCycle(LOC35);
					++sysargsraw->Sup.len;
					nimln(1968, "system.nim");
					TMP964 = addInt(i_194279, ((NI) 1));
					i_194279 = (NI)(TMP964);
				} LA34: ;
			}
		}
	}
	LA17: ;
	pid = 0;
	nimln(747, "osproc.nim");
	sysargs = alloccstringarray_16201(sysargsraw->data, sysargsraw->Sup.len);
	nimln(748, "osproc.nim");
	pushSafePoint(&TMP965);
	TMP965.status = setjmp(TMP965.context);
	if (TMP965.status == 0) {
		NCSTRING* sysenv;
		TSafePoint TMP966;
		nimln(750, "osproc.nim");
		{
			if (!(env == NIM_NIL)) goto LA39;
			nimln(751, "osproc.nim");
			sysenv = envtocstringarray_193636();
		}
		goto LA37;
		LA39: ;
		{
			nimln(753, "osproc.nim");
			sysenv = envtocstringarray_193603(env);
		}
		LA37: ;
		nimln(755, "osproc.nim");
		pushSafePoint(&TMP966);
		TMP966.status = setjmp(TMP966.context);
		if (TMP966.status == 0) {
			Startprocessdata193703 data;
			memset((void*)(&data), 0, sizeof(data));
			nimln(758, "osproc.nim");
			data.syscommand = syscommand->data;
			nimln(759, "osproc.nim");
			data.sysargs = sysargs;
			nimln(760, "osproc.nim");
			data.sysenv = sysenv;
			nimln(761, "osproc.nim");
			memcpy((void*)data.pstdin, (NIM_CONST void*)pstdin, sizeof(TY193709));
			nimln(762, "osproc.nim");
			memcpy((void*)data.pstdout, (NIM_CONST void*)pstdout, sizeof(TY193709));
			nimln(763, "osproc.nim");
			memcpy((void*)data.pstderr, (NIM_CONST void*)pstderr, sizeof(TY193709));
			nimln(764, "osproc.nim");
			nimln(1098, "system.nim");
			data.optionpoparentstreams = ((options &(1U<<((NU)(((NU8) 4))&7U)))!=0);
			nimln(765, "osproc.nim");
			nimln(1098, "system.nim");
			data.optionpousepath = ((options &(1U<<((NU)(((NU8) 1))&7U)))!=0);
			nimln(766, "osproc.nim");
			nimln(1098, "system.nim");
			data.optionpostderrtostdout = ((options &(1U<<((NU)(((NU8) 3))&7U)))!=0);
			nimln(767, "osproc.nim");
			data.workingdir = workingdir->data;
			nimln(772, "osproc.nim");
			pid = startprocessauxfork_193801((&data));
			nimln(775, "osproc.nim");
			{
				NimStringDesc* LOC47;
				nimln(1098, "system.nim");
				if (!((options &(1U<<((NU)(((NU8) 0))&7U)))!=0)) goto LA45;
				nimln(776, "osproc.nim");
				LOC47 = 0;
				LOC47 = nsuJoinSep(args, argsLen0, ((NimStringDesc*) &TMP967));
				printf("%s%s%s\012", command? (command)->data:"nil", ((NimStringDesc*) &TMP967)? (((NimStringDesc*) &TMP967))->data:"nil", LOC47? (LOC47)->data:"nil");
				fflush(stdout);
			}
			LA45: ;
			nimln(777, "osproc.nim");
			(*result).id = pid;
			nimln(779, "osproc.nim");
			{
				nimln(1098, "system.nim");
				if (!((options &(1U<<((NU)(((NU8) 4))&7U)))!=0)) goto LA50;
				nimln(781, "osproc.nim");
				(*result).inhandle = ((int) 0);
				nimln(782, "osproc.nim");
				(*result).outhandle = ((int) 1);
				nimln(783, "osproc.nim");
				{
					nimln(1098, "system.nim");
					if (!((options &(1U<<((NU)(((NU8) 3))&7U)))!=0)) goto LA54;
					nimln(784, "osproc.nim");
					(*result).errhandle = (*result).outhandle;
				}
				goto LA52;
				LA54: ;
				{
					nimln(786, "osproc.nim");
					(*result).errhandle = ((int) 2);
				}
				LA52: ;
			}
			goto LA48;
			LA50: ;
			{
				int LOC64;
				int LOC65;
				int LOC66;
				nimln(788, "osproc.nim");
				(*result).inhandle = pstdin[(((NI) 1))- 0];
				nimln(789, "osproc.nim");
				(*result).outhandle = pstdout[(((NI) 0))- 0];
				nimln(790, "osproc.nim");
				{
					int LOC62;
					nimln(1098, "system.nim");
					if (!((options &(1U<<((NU)(((NU8) 3))&7U)))!=0)) goto LA60;
					nimln(791, "osproc.nim");
					(*result).errhandle = (*result).outhandle;
					nimln(792, "osproc.nim");
					LOC62 = 0;
					LOC62 = close(pstderr[(((NI) 0))- 0]);
				}
				goto LA58;
				LA60: ;
				{
					nimln(794, "osproc.nim");
					(*result).errhandle = pstderr[(((NI) 0))- 0];
				}
				LA58: ;
				nimln(795, "osproc.nim");
				LOC64 = 0;
				LOC64 = close(pstderr[(((NI) 1))- 0]);
				nimln(796, "osproc.nim");
				LOC65 = 0;
				LOC65 = close(pstdin[(((NI) 0))- 0]);
				nimln(797, "osproc.nim");
				LOC66 = 0;
				LOC66 = close(pstdout[(((NI) 1))- 0]);
			}
			LA48: ;
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR);
		}
		{
			nimln(755, "osproc.nim");
			dealloccstringarray_16429(sysenv);
		}
		if (TMP966.status != 0) reraiseException();
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(748, "osproc.nim");
		dealloccstringarray_16429(sysargs);
	}
	if (TMP965.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(void, nospclose)(Processobj192404* p) {
	nimfr("close", "osproc.nim")
	nimln(937, "osproc.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*p).instream == NIM_NIL))) goto LA3;
		nimln(937, "osproc.nim");
		close_149270((*p).instream);
	}
	LA3: ;
	nimln(938, "osproc.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*p).outstream == NIM_NIL))) goto LA7;
		nimln(938, "osproc.nim");
		close_149270((*p).outstream);
	}
	LA7: ;
	nimln(939, "osproc.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*p).errstream == NIM_NIL))) goto LA11;
		nimln(939, "osproc.nim");
		close_149270((*p).errstream);
	}
	LA11: ;
	nimln(940, "osproc.nim");
	{
		int LOC17;
		int LOC18;
		int LOC19;
		nimln(1104, "system.nim");
		if (!!((((*p).options &(1U<<((NU)(((NU8) 4))&7U)))!=0))) goto LA15;
		nimln(941, "osproc.nim");
		LOC17 = 0;
		LOC17 = close((*p).inhandle);
		nimln(942, "osproc.nim");
		LOC18 = 0;
		LOC18 = close((*p).outhandle);
		nimln(943, "osproc.nim");
		LOC19 = 0;
		LOC19 = close((*p).errhandle);
	}
	LA15: ;
	popFrame();
}

N_NIMCALL(void, nospsuspend)(Processobj192404* p) {
	nimfr("suspend", "osproc.nim")
	nimln(946, "osproc.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(946, "osproc.nim");
		LOC3 = 0;
		LOC3 = kill((*p).id, SIGSTOP);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP898));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, nospresume)(Processobj192404* p) {
	nimfr("resume", "osproc.nim")
	nimln(949, "osproc.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(949, "osproc.nim");
		LOC3 = 0;
		LOC3 = kill((*p).id, SIGCONT);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP898));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, nosprunning)(Processobj192404* p) {
	NIM_BOOL result;
	NI ret;
	nimfr("running", "osproc.nim")
{	result = 0;
	ret = 0;
	nimln(954, "osproc.nim");
	ret = waitpid((*p).id, (&(*p).exitcode), WNOHANG);
	nimln(960, "osproc.nim");
	{
		if (!(ret == ((NI) 0))) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	nimln(961, "osproc.nim");
	result = (ret == (*p).id);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nospterminate)(Processobj192404* p) {
	nimfr("terminate", "osproc.nim")
	nimln(964, "osproc.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(964, "osproc.nim");
		LOC3 = 0;
		LOC3 = kill((*p).id, SIGTERM);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		nimln(965, "osproc.nim");
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP898));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, nospkill)(Processobj192404* p) {
	nimfr("kill", "osproc.nim")
	nimln(968, "osproc.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(968, "osproc.nim");
		LOC3 = 0;
		LOC3 = kill((*p).id, SIGKILL);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		nimln(969, "osproc.nim");
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP898));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI, nospwaitForExit)(Processobj192404* p, NI timeout) {
	NI result;
	nimfr("waitForExit", "osproc.nim")
{	result = 0;
	nimln(976, "osproc.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*p).exitcode == ((NI32) -3)))) goto LA3;
		nimln(976, "osproc.nim");
		result = ((NI) ((*p).exitcode));
		goto BeforeRet;
	}
	LA3: ;
	nimln(977, "osproc.nim");
	{
		pid_t LOC7;
		NI32 LOC10;
		LOC7 = 0;
		LOC7 = waitpid((*p).id, (&(*p).exitcode), ((int) 0));
		if (!(LOC7 < ((NI) 0))) goto LA8;
		nimln(978, "osproc.nim");
		(*p).exitcode = ((int) -3);
		nimln(979, "osproc.nim");
		LOC10 = 0;
		LOC10 = oslasterror_119819();
		raiseoserror_119803(LOC10, ((NimStringDesc*) &TMP898));
	}
	LA8: ;
	nimln(980, "osproc.nim");
	result = (NI)((NU64)(((NI) ((*p).exitcode))) >> (NU64)(((NI) 8)));
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, peekexitcode_192677)(Processobj192404* p) {
	NI result;
	pid_t ret;
	NIM_BOOL b;
	nimfr("peekExitCode", "osproc.nim")
{	result = 0;
	nimln(983, "osproc.nim");
	{
		nimln(349, "system.nim");
		if (!!(((*p).exitcode == ((NI32) -3)))) goto LA3;
		nimln(983, "osproc.nim");
		result = ((NI) ((*p).exitcode));
		goto BeforeRet;
	}
	LA3: ;
	nimln(984, "osproc.nim");
	ret = waitpid((*p).id, (&(*p).exitcode), WNOHANG);
	nimln(985, "osproc.nim");
	b = (ret == (*p).id);
	nimln(986, "osproc.nim");
	{
		if (!b) goto LA7;
		result = ((NI) -1);
	}
	LA7: ;
	nimln(987, "osproc.nim");
	{
		NIM_BOOL LOC11;
		LOC11 = 0;
		LOC11 = WIFEXITED((*p).exitcode);
		if (!!(LOC11)) goto LA12;
		result = ((NI) -1);
	}
	goto LA9;
	LA12: ;
	{
		nimln(988, "osproc.nim");
		result = (NI)((NU64)(((NI) ((*p).exitcode))) >> (NU64)(((NI) 8)));
	}
	LA9: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, createstream_195426)(Streamobj149218** stream, int* handle, NU8 filemode) {
	FILE* f;
	Filestreamobj150048* LOC7;
	nimfr("createStream", "osproc.nim")
	f = 0;
	nimln(993, "osproc.nim");
	{
		NIM_BOOL LOC3;
		NI32 LOC6;
		LOC3 = 0;
		LOC3 = open_15411(&f, (*handle), filemode);
		if (!!(LOC3)) goto LA4;
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP898));
	}
	LA4: ;
	nimln(994, "osproc.nim");
	LOC7 = 0;
	LOC7 = newfilestream_150101(f);
	unsureAsgnRef((void**) (&(*stream)), &LOC7->Sup);
	popFrame();
}

N_NIMCALL(Streamobj149218*, nospinputStream)(Processobj192404* p) {
	Streamobj149218* result;
	nimfr("inputStream", "osproc.nim")
{	result = 0;
	nimln(997, "osproc.nim");
	{
		if (!((*p).instream == NIM_NIL)) goto LA3;
		nimln(998, "osproc.nim");
		createstream_195426(&(*p).instream, (&(*p).inhandle), ((NU8) 1));
	}
	LA3: ;
	nimln(999, "osproc.nim");
	result = (*p).instream;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Streamobj149218*, nospoutputStream)(Processobj192404* p) {
	Streamobj149218* result;
	nimfr("outputStream", "osproc.nim")
{	result = 0;
	nimln(1002, "osproc.nim");
	{
		if (!((*p).outstream == NIM_NIL)) goto LA3;
		nimln(1003, "osproc.nim");
		createstream_195426(&(*p).outstream, (&(*p).outhandle), ((NU8) 0));
	}
	LA3: ;
	nimln(1004, "osproc.nim");
	result = (*p).outstream;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(Streamobj149218*, nosperrorStream)(Processobj192404* p) {
	Streamobj149218* result;
	nimfr("errorStream", "osproc.nim")
{	result = 0;
	nimln(1007, "osproc.nim");
	{
		if (!((*p).errstream == NIM_NIL)) goto LA3;
		nimln(1008, "osproc.nim");
		createstream_195426(&(*p).errstream, (&(*p).errhandle), ((NU8) 0));
	}
	LA3: ;
	nimln(1009, "osproc.nim");
	result = (*p).errstream;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, nospexecCmd)(NimStringDesc* command) {
	NI result;
	int LOC1;
	nimfr("execCmd", "osproc.nim")
	result = 0;
	nimln(1016, "osproc.nim");
	LOC1 = 0;
	LOC1 = system(command->data);
	result = ((NI) ((NI32)((NU32)(LOC1) >> (NU32)(((NI32) 8)))));
	popFrame();
	return result;
}

N_NIMCALL(void, createfdset_195601)(fd_set* fd, TY193001* s, NI* m) {
	nimfr("createFdSet", "osproc.nim")
	nimln(1021, "osproc.nim");
	FD_ZERO(fd);
	{
		Processobj192404* i_195802;
		NI i_195820;
		NI L_195822;
		i_195802 = 0;
		nimln(3361, "system.nim");
		i_195820 = ((NI) 0);
		nimln(3362, "system.nim");
		L_195822 = (s ? s->Sup.len : 0);
		{
			nimln(3363, "system.nim");
			while (1) {
				NI TMP968;
				if (!(i_195820 < L_195822)) goto LA3;
				nimln(3364, "system.nim");
				if ((NU)(i_195820) >= (NU)(s->Sup.len)) raiseIndexError();
				i_195802 = s->data[i_195820];
				nimln(1023, "osproc.nim");
				(*m) = (((*m) >= ((NI) ((*i_195802).outhandle))) ? (*m) : ((NI) ((*i_195802).outhandle)));
				nimln(1024, "osproc.nim");
				FD_SET((*i_195802).outhandle, fd);
				nimln(3365, "system.nim");
				TMP968 = addInt(i_195820, ((NI) 1));
				i_195820 = (NI)(TMP968);
				nimln(3366, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L_195822))) goto LA6;
					failedassertimpl_89116(((NimStringDesc*) &TMP969));
				}
				LA6: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, pruneprocessset_195823)(TY193001** s, fd_set* fd) {
	NI i;
	NI L;
	nimfr("pruneProcessSet", "osproc.nim")
	nimln(1027, "osproc.nim");
	i = ((NI) 0);
	nimln(1028, "osproc.nim");
	L = ((*s) ? (*s)->Sup.len : 0);
	{
		nimln(1029, "osproc.nim");
		while (1) {
			if (!(i < L)) goto LA2;
			nimln(1030, "osproc.nim");
			{
				int LOC5;
				NI TMP970;
				NI TMP971;
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				LOC5 = 0;
				LOC5 = FD_ISSET((*(*s)->data[i]).outhandle, fd);
				if (!(LOC5 == ((NI32) 0))) goto LA6;
				nimln(1031, "osproc.nim");
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				TMP970 = subInt(L, ((NI) 1));
				if ((NU)((NI)(TMP970)) >= (NU)((*s)->Sup.len)) raiseIndexError();
				asgnRef((void**) (&(*s)->data[i]), (*s)->data[(NI)(TMP970)]);
				nimln(1032, "osproc.nim");
				TMP971 = subInt(L, ((NI) 1));
				L = (NI)(TMP971);
			}
			goto LA3;
			LA6: ;
			{
				NI TMP972;
				nimln(1034, "osproc.nim");
				TMP972 = addInt(i, ((NI) 1));
				i = (NI)(TMP972);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(1035, "osproc.nim");
	(*s) = (TY193001*) setLengthSeq(&((*s))->Sup, sizeof(Processobj192404*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}

N_NIMCALL(NI, select_193384)(TY193001** readfds, NI timeout) {
	NI result;
	struct timeval tv;
	NI TMP973;
	fd_set rd;
	NI m;
	nimfr("select", "osproc.nim")
	result = 0;
	memset((void*)(&tv), 0, sizeof(tv));
	nimln(1039, "osproc.nim");
	tv.tv_sec = ((NI) 0);
	nimln(1040, "osproc.nim");
	TMP973 = mulInt(timeout, ((NI) 1000));
	tv.tv_usec = (NI)(TMP973);
	memset((void*)(&rd), 0, sizeof(rd));
	nimln(1043, "osproc.nim");
	m = ((NI) 0);
	nimln(1044, "osproc.nim");
	createfdset_195601((&rd), (*readfds), (&m));
	nimln(1046, "osproc.nim");
	{
		NI TMP974;
		int LOC5;
		nimln(349, "system.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3;
		nimln(1047, "osproc.nim");
		TMP974 = addInt(m, ((NI) 1));
		LOC5 = 0;
		LOC5 = select(((int)chckRange((NI)(TMP974), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, (&tv));
		result = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI TMP975;
		int LOC7;
		nimln(1049, "osproc.nim");
		TMP975 = addInt(m, ((NI) 1));
		LOC7 = 0;
		LOC7 = select(((int)chckRange((NI)(TMP975), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
		result = ((NI) (LOC7));
	}
	LA1: ;
	nimln(1051, "osproc.nim");
	pruneprocessset_195823(readfds, (&rd));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, hasdata_195931)(Processobj192404* p) {
	NIM_BOOL result;
	fd_set rd;
	NI m;
	NI TMP976;
	int LOC1;
	nimfr("hasData", "osproc.nim")
	result = 0;
	memset((void*)(&rd), 0, sizeof(rd));
	nimln(1056, "osproc.nim");
	FD_ZERO((&rd));
	nimln(1057, "osproc.nim");
	m = ((((NI) 0) >= ((NI) ((*p).outhandle))) ? ((NI) 0) : ((NI) ((*p).outhandle)));
	nimln(1058, "osproc.nim");
	FD_SET((*p).outhandle, (&rd));
	nimln(1060, "osproc.nim");
	TMP976 = addInt(m, ((NI) 1));
	LOC1 = 0;
	LOC1 = select(((int)chckRange((NI)(TMP976), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
	result = (((NI) (LOC1)) == ((NI) 1));
	popFrame();
	return result;
}

N_NIMCALL(void, execcmdex_196001)(NimStringDesc* command, NU8 options, TY196007* Result) {
	Processobj192404* p;
	TY192625 LOC1;
	Streamobj149218* outp;
	NimStringDesc* line;
	nimfr("execCmdEx", "osproc.nim")
	nimln(1073, "osproc.nim");
	memset((void*)LOC1, 0, sizeof(LOC1));
	p = nospstartProcess(command, ((NimStringDesc*) &TMP898), LOC1, 0, NIM_NIL, (options | 4));
	nimln(1074, "osproc.nim");
	outp = nospoutputStream(p);
	nimln(1075, "osproc.nim");
	unsureAsgnRef((void**) (&(*Result).Field0), copyString(TMP977.Field0));
	(*Result).Field1 = TMP977.Field1;
	nimln(1076, "osproc.nim");
	line = rawNewString(((NI) 120));
	{
		nimln(1077, "osproc.nim");
		while (1) {
			nimln(1078, "osproc.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				LOC6 = readline_149916(outp, (&line));
				if (!LOC6) goto LA7;
				nimln(1079, "osproc.nim");
				(*Result).Field0 = resizeString((*Result).Field0, line->Sup.len + 0);
appendString((*Result).Field0, line);
				nimln(1080, "osproc.nim");
				(*Result).Field0 = resizeString((*Result).Field0, 1);
appendString((*Result).Field0, ((NimStringDesc*) &TMP938));
			}
			goto LA4;
			LA7: ;
			{
				nimln(1082, "osproc.nim");
				(*Result).Field1 = peekexitcode_192677(p);
				nimln(1083, "osproc.nim");
				{
					nimln(349, "system.nim");
					if (!!(((*Result).Field1 == ((NI) -1)))) goto LA12;
					nimln(1083, "osproc.nim");
					goto LA2;
				}
				LA12: ;
			}
			LA4: ;
		}
	} LA2: ;
	nimln(1084, "osproc.nim");
	nospclose(p);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocInit000)(void) {
	nimfr("osproc", "osproc.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osprocDatInit000)(void) {
static TNimNode* TMP910[9];
static TNimNode* TMP912[7];
NI TMP914;
static char* NIM_CONST TMP913[7] = {
"poEchoCmd", 
"poUsePath", 
"poEvalCommand", 
"poStdErrToStdOut", 
"poParentStreams", 
"poInteractive", 
"poDemon"};
static TNimNode TMP891[19];
NTI192404.size = sizeof(Processobj192404);
NTI192404.kind = 17;
NTI192404.base = (&NTI3608);
TMP910[0] = &TMP891[1];
TMP891[1].kind = 1;
TMP891[1].offset = offsetof(Processobj192404, inhandle);
TMP891[1].typ = (&NTI15008);
TMP891[1].name = "inHandle";
TMP910[1] = &TMP891[2];
TMP891[2].kind = 1;
TMP891[2].offset = offsetof(Processobj192404, outhandle);
TMP891[2].typ = (&NTI15008);
TMP891[2].name = "outHandle";
TMP910[2] = &TMP891[3];
TMP891[3].kind = 1;
TMP891[3].offset = offsetof(Processobj192404, errhandle);
TMP891[3].typ = (&NTI15008);
TMP891[3].name = "errHandle";
TMP910[3] = &TMP891[4];
TMP891[4].kind = 1;
TMP891[4].offset = offsetof(Processobj192404, instream);
TMP891[4].typ = (&NTI149216);
TMP891[4].name = "inStream";
TMP910[4] = &TMP891[5];
TMP891[5].kind = 1;
TMP891[5].offset = offsetof(Processobj192404, outstream);
TMP891[5].typ = (&NTI149216);
TMP891[5].name = "outStream";
TMP910[5] = &TMP891[6];
TMP891[6].kind = 1;
TMP891[6].offset = offsetof(Processobj192404, errstream);
TMP891[6].typ = (&NTI149216);
TMP891[6].name = "errStream";
TMP910[6] = &TMP891[7];
TMP891[7].kind = 1;
TMP891[7].offset = offsetof(Processobj192404, id);
TMP891[7].typ = (&NTI109274);
TMP891[7].name = "id";
TMP910[7] = &TMP891[8];
TMP891[8].kind = 1;
TMP891[8].offset = offsetof(Processobj192404, exitcode);
TMP891[8].typ = (&NTI7208);
TMP891[8].name = "exitCode";
TMP910[8] = &TMP891[9];
NTI192402.size = sizeof(NU8);
NTI192402.kind = 14;
NTI192402.base = 0;
NTI192402.flags = 3;
for (TMP914 = 0; TMP914 < 7; TMP914++) {
TMP891[TMP914+10].kind = 1;
TMP891[TMP914+10].offset = TMP914;
TMP891[TMP914+10].name = TMP913[TMP914];
TMP912[TMP914] = &TMP891[TMP914+10];
}
TMP891[17].len = 7; TMP891[17].kind = 2; TMP891[17].sons = &TMP912[0];
NTI192402.node = &TMP891[17];
NTI192634.size = sizeof(NU8);
NTI192634.kind = 19;
NTI192634.base = (&NTI192402);
NTI192634.flags = 3;
TMP891[18].len = 0; TMP891[18].kind = 0;
NTI192634.node = &TMP891[18];
TMP891[9].kind = 1;
TMP891[9].offset = offsetof(Processobj192404, options);
TMP891[9].typ = (&NTI192634);
TMP891[9].name = "options";
TMP891[0].len = 9; TMP891[0].kind = 2; TMP891[0].sons = &TMP910[0];
NTI192404.node = &TMP891[0];
NTI192406.size = sizeof(Processobj192404*);
NTI192406.kind = 22;
NTI192406.base = (&NTI192404);
NTI192406.marker = TMP915;
NTI193001.size = sizeof(TY193001*);
NTI193001.kind = 24;
NTI193001.base = (&NTI192406);
NTI193001.marker = TMP916;
}

