/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/stdlib_nativesockets.o /home/cyril/Projects/provider/nimcache/stdlib_nativesockets.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <netdb.h>
#include <string.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <sys/select.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Servent134610 Servent134610;
typedef struct TY15805 TY15805;
typedef struct Hostent134612 Hostent134612;
typedef struct TY137811 TY137811;
typedef struct TY138835 TY138835;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Servent134610  {
NimStringDesc* name;
TY15805* aliases;
NU16 port;
NimStringDesc* proto;
};
struct  Hostent134612  {
NimStringDesc* name;
TY15805* aliases;
NU8 addrtype;
NI length;
TY15805* addrlist;
};
typedef NIM_CHAR TY109852[256];
typedef NIM_CHAR TY109877[16];
struct TY137811 {
NimStringDesc* Field0;
NU16 Field1;
};
typedef NIM_CHAR TY138206[64];
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY15805 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY138835 {
  TGenericSeq Sup;
  int data[SEQ_DECL_SIZE];
};
N_NIMCALL(int, toint_134820)(NU8 domain);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(int, toint_134823)(NU8 typ);
N_NIMCALL(int, toint_134826)(NU8 p);
N_NIMCALL(int, newnativesocket_135001)(NU8 domain, NU8 socktype, NU8 protocol);
N_NIMCALL(int, newnativesocket_135007)(int domain, int socktype, int protocol);
N_NIMCALL(void, close_135013)(int socket);
N_NIMCALL(int, bindaddr_135208)(int socket, struct sockaddr* name, socklen_t namelen);
N_NIMCALL(int, listen_135215)(int socket, int backlog);
N_NIMCALL(struct addrinfo*, getaddrinfo_135402)(NimStringDesc* address, NU16 port, NU8 domain, NU8 socktype, NU8 protocol);
N_NIMCALL(NimStringDesc*, HEX24_7801)(NU64 x);
N_NOINLINE(void, raiseoserror_119803)(NI32 errorcode, NimStringDesc* additionalinfo);
N_NIMCALL(NI32, oslasterror_119819)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, dealloc_135802)(struct addrinfo* ai);
N_NIMCALL(NI32, ntohl_135806)(NI32 x);
N_NIMCALL(NI16, ntohs_136001)(NI16 x);
N_NIMCALL(void, getservbyname_136207)(NimStringDesc* name, NimStringDesc* proto, Servent134610* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(TY15805*, cstringarraytoseq_16022)(NCSTRING* a);
N_NIMCALL(void, getservbyport_136414)(NU16 port, NimStringDesc* proto, Servent134610* Result);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, gethostbyaddr_136614)(NimStringDesc* ip, Hostent134612* Result);
N_NIMCALL(void, gethostbyname_137004)(NimStringDesc* name, Hostent134612* Result);
N_NIMCALL(NU8, getsockdomain_137402)(int socket);
N_NIMCALL(NimStringDesc*, getaddrstring_137413)(struct sockaddr* sockaddr);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NU16, getsockname_137606)(int socket);
N_NIMCALL(void, getlocaladdr_137807)(int socket, NU8 domain, TY137811* Result);
N_NIMCALL(void, getpeeraddr_138217)(int socket, NU8 domain, TY137811* Result);
N_NIMCALL(NI, getsockoptint_138617)(int socket, NI level, NI optname);
N_NIMCALL(void, setsockoptint_138629)(int socket, NI level, NI optname, NI optval);
N_NIMCALL(void, setblocking_138637)(int s, NIM_BOOL blocking);
N_NIMCALL(struct timeval, timevalfrommilliseconds_138822)(NI timeout);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, createfdset_138831)(fd_set* fd, TY138835* s, NI* m);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
N_NIMCALL(void, prunesocketset_139022)(TY138835** s, fd_set* fd);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_NIMCALL(NI, select_139077)(TY138835** readfds, NI timeout);
N_NIMCALL(NI, selectwrite_139128)(TY138835** writefds, NI timeout);
STRING_LITERAL(TMP601, "Service not found.", 18);
STRING_LITERAL(TMP602, "unknown h_addrtype", 18);
STRING_LITERAL(TMP603, "", 0);
STRING_LITERAL(TMP604, "unknown socket family in getSockFamily", 38);
STRING_LITERAL(TMP605, "unknown socket family in getAddrString", 38);
STRING_LITERAL(TMP606, "invalid socket family in getLocalAddr", 37);
STRING_LITERAL(TMP612, "len(a) == L seq modified while iterating over it", 48);
int osinvalidsocket_134645;
int nativeafinet_134646;
int nativeafinet6_134647;
extern TFrame* frameptr_19436;
TNimType NTI134604; /* Domain */
TNimType NTI134606; /* SockType */
TNimType NTI134608; /* Protocol */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(int, toint_134820)(NU8 domain) {
	int result;
	nimfr("toInt", "nativesockets.nim")
	result = 0;
	nimln(125, "nativesockets.nim");
	switch (domain) {
	case ((NU8) 0):
	{
		nimln(126, "nativesockets.nim");
		result = AF_UNIX;
	}
	break;
	case ((NU8) 2):
	{
		nimln(127, "nativesockets.nim");
		result = AF_INET;
	}
	break;
	case ((NU8) 23):
	{
		nimln(128, "nativesockets.nim");
		result = AF_INET6;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(int, toint_134823)(NU8 typ) {
	int result;
	nimfr("toInt", "nativesockets.nim")
	result = 0;
	nimln(132, "nativesockets.nim");
	switch (typ) {
	case ((NU8) 1):
	{
		nimln(133, "nativesockets.nim");
		result = SOCK_STREAM;
	}
	break;
	case ((NU8) 2):
	{
		nimln(134, "nativesockets.nim");
		result = SOCK_DGRAM;
	}
	break;
	case ((NU8) 5):
	{
		nimln(135, "nativesockets.nim");
		result = SOCK_SEQPACKET;
	}
	break;
	case ((NU8) 3):
	{
		nimln(136, "nativesockets.nim");
		result = SOCK_RAW;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(int, toint_134826)(NU8 p) {
	int result;
	nimfr("toInt", "nativesockets.nim")
	result = 0;
	nimln(140, "nativesockets.nim");
	switch (p) {
	case ((NU8) 6):
	{
		nimln(141, "nativesockets.nim");
		result = IPPROTO_TCP;
	}
	break;
	case ((NU8) 17):
	{
		nimln(142, "nativesockets.nim");
		result = IPPROTO_UDP;
	}
	break;
	case ((NU8) 18):
	{
		nimln(143, "nativesockets.nim");
		result = IPPROTO_IP;
	}
	break;
	case ((NU8) 19):
	{
		nimln(144, "nativesockets.nim");
		result = IPPROTO_IPV6;
	}
	break;
	case ((NU8) 20):
	{
		nimln(145, "nativesockets.nim");
		result = IPPROTO_RAW;
	}
	break;
	case ((NU8) 21):
	{
		nimln(146, "nativesockets.nim");
		result = IPPROTO_ICMP;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(int, newnativesocket_135001)(NU8 domain, NU8 socktype, NU8 protocol) {
	int result;
	int LOC1;
	int LOC2;
	int LOC3;
	nimfr("newNativeSocket", "nativesockets.nim")
	result = 0;
	nimln(163, "nativesockets.nim");
	nimln(164, "nativesockets.nim");
	LOC1 = 0;
	LOC1 = toint_134820(domain);
	LOC2 = 0;
	LOC2 = toint_134823(socktype);
	LOC3 = 0;
	LOC3 = toint_134826(protocol);
	result = socket(LOC1, LOC2, LOC3);
	popFrame();
	return result;
}

N_NIMCALL(int, newnativesocket_135007)(int domain, int socktype, int protocol) {
	int result;
	nimfr("newNativeSocket", "nativesockets.nim")
	result = 0;
	nimln(168, "nativesockets.nim");
	nimln(172, "nativesockets.nim");
	result = socket(domain, socktype, protocol);
	popFrame();
	return result;
}

N_NIMCALL(void, close_135013)(int socket) {
	int LOC1;
	nimfr("close", "nativesockets.nim")
	nimln(179, "nativesockets.nim");
	LOC1 = 0;
	LOC1 = close(socket);
	popFrame();
}

N_NIMCALL(int, bindaddr_135208)(int socket, struct sockaddr* name, socklen_t namelen) {
	int result;
	nimfr("bindAddr", "nativesockets.nim")
	result = 0;
	nimln(184, "nativesockets.nim");
	result = bind(socket, name, namelen);
	popFrame();
	return result;
}

N_NIMCALL(int, listen_135215)(int socket, int backlog) {
	int result;
	nimfr("listen", "nativesockets.nim")
	result = 0;
	nimln(193, "nativesockets.nim");
	result = listen(socket, backlog);
	popFrame();
	return result;
}

N_NIMCALL(struct addrinfo*, getaddrinfo_135402)(NimStringDesc* address, NU16 port, NU8 domain, NU8 socktype, NU8 protocol) {
	struct addrinfo* result;
	struct addrinfo hints;
	int gairesult;
	NimStringDesc* LOC5;
	nimfr("getAddrInfo", "nativesockets.nim")
	result = 0;
	memset((void*)(&hints), 0, sizeof(hints));
	nimln(202, "nativesockets.nim");
	result = NIM_NIL;
	nimln(203, "nativesockets.nim");
	hints.ai_family = toint_134820(domain);
	nimln(204, "nativesockets.nim");
	hints.ai_socktype = toint_134823(socktype);
	nimln(205, "nativesockets.nim");
	hints.ai_protocol = toint_134826(protocol);
	nimln(210, "nativesockets.nim");
	{
		if (!(domain == ((NU8) 23))) goto LA3;
		nimln(211, "nativesockets.nim");
		hints.ai_flags = AI_V4MAPPED;
	}
	LA3: ;
	nimln(212, "nativesockets.nim");
	LOC5 = 0;
	LOC5 = HEX24_7801(port);
	gairesult = getaddrinfo(address->data, LOC5->data, (&hints), &result);
	nimln(213, "nativesockets.nim");
	{
		NI32 LOC10;
		NCSTRING LOC11;
		NimStringDesc* LOC12;
		nimln(349, "system.nim");
		if (!!((gairesult == ((NI32) 0)))) goto LA8;
		nimln(217, "nativesockets.nim");
		LOC10 = 0;
		LOC10 = oslasterror_119819();
		LOC11 = 0;
		LOC11 = (char *)gai_strerror(gairesult);
		LOC12 = 0;
		LOC12 = cstrToNimstr(LOC11);
		raiseoserror_119803(LOC10, LOC12);
	}
	LA8: ;
	popFrame();
	return result;
}

N_NIMCALL(void, dealloc_135802)(struct addrinfo* ai) {
	nimfr("dealloc", "nativesockets.nim")
	nimln(220, "nativesockets.nim");
	freeaddrinfo(ai);
	popFrame();
}

N_NIMCALL(NI32, ntohl_135806)(NI32 x) {
	NI32 result;
	nimfr("ntohl", "nativesockets.nim")
	result = 0;
	nimln(227, "nativesockets.nim");
	nimln(229, "nativesockets.nim");
	nimln(228, "nativesockets.nim");
	nimln(227, "nativesockets.nim");
	nimln(228, "nativesockets.nim");
	nimln(229, "nativesockets.nim");
	nimln(230, "nativesockets.nim");
	result = (NI32)((NI32)((NI32)((NI32)((NU32)(x) >> (NU32)(((NI32) 24))) | (NI32)((NI32)((NU32)(x) >> (NU32)(((NI32) 8))) & ((NI32) 65280))) | (NI32)((NI32)((NU32)(x) << (NU32)(((NI32) 8))) & ((NI32) 16711680))) | (NI32)((NU32)(x) << (NU32)(((NI32) 24))));
	popFrame();
	return result;
}

N_NIMCALL(NI16, ntohs_136001)(NI16 x) {
	NI16 result;
	nimfr("ntohs", "nativesockets.nim")
	result = 0;
	nimln(237, "nativesockets.nim");
	result = (NI16)((NI16)((NU16)(x) >> (NU16)(((NI16) 8))) | (NI16)((NU16)(x) << (NU16)(((NI16) 8))));
	popFrame();
	return result;
}

N_NIMCALL(void, getservbyname_136207)(NimStringDesc* name, NimStringDesc* proto, Servent134610* Result) {
	struct servent* s;
	nimfr("getServByName", "nativesockets.nim")
	nimln(260, "nativesockets.nim");
	s = getservbyname(name->data, proto->data);
	nimln(261, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = oslasterror_119819();
		raiseoserror_119803(LOC5, ((NimStringDesc*) &TMP601));
	}
	LA3: ;
	nimln(262, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).s_name));
	nimln(263, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_16022((*s).s_aliases));
	nimln(264, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s).s_port));
	nimln(265, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s).s_proto));
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, getservbyport_136414)(NU16 port, NimStringDesc* proto, Servent134610* Result) {
	struct servent* s;
	nimfr("getServByPort", "nativesockets.nim")
	nimln(276, "nativesockets.nim");
	s = getservbyport(((int)chckRange(((NI)(NU)(NU16)(((NI16)chckRange(port, ((NI16) -32768), ((NI16) 32767))))), ((int) (-2147483647 -1)), ((int) 2147483647))), proto->data);
	nimln(277, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = oslasterror_119819();
		raiseoserror_119803(LOC5, ((NimStringDesc*) &TMP601));
	}
	LA3: ;
	nimln(278, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).s_name));
	nimln(279, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_16022((*s).s_aliases));
	nimln(280, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s).s_port));
	nimln(281, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s).s_proto));
	popFrame();
}

N_NIMCALL(void, gethostbyaddr_136614)(NimStringDesc* ip, Hostent134612* Result) {
	struct in_addr myaddr;
	struct hostent* s;
	nimfr("getHostByAddr", "nativesockets.nim")
	memset((void*)(&myaddr), 0, sizeof(myaddr));
	nimln(286, "nativesockets.nim");
	myaddr.s_addr = inet_addr(ip->data);
	nimln(293, "nativesockets.nim");
	s = gethostbyaddr(((void*) ((&myaddr))), ((socklen_t) (((NI)sizeof(struct in_addr)))), AF_INET);
	nimln(295, "nativesockets.nim");
	{
		NI32 LOC5;
		NCSTRING LOC6;
		NimStringDesc* LOC7;
		if (!(s == NIM_NIL)) goto LA3;
		nimln(296, "nativesockets.nim");
		LOC5 = 0;
		LOC5 = oslasterror_119819();
		LOC6 = 0;
		LOC6 = (char *)hstrerror(h_errno);
		LOC7 = 0;
		LOC7 = cstrToNimstr(LOC6);
		raiseoserror_119803(LOC5, LOC7);
	}
	LA3: ;
	nimln(298, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).h_name));
	nimln(299, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_16022((*s).h_aliases));
	nimln(303, "nativesockets.nim");
	{
		if (!((*s).h_addrtype == AF_INET)) goto LA10;
		nimln(304, "nativesockets.nim");
		(*Result).addrtype = ((NU8) 2);
	}
	goto LA8;
	LA10: ;
	{
		nimln(305, "nativesockets.nim");
		if (!((*s).h_addrtype == AF_INET6)) goto LA13;
		nimln(306, "nativesockets.nim");
		(*Result).addrtype = ((NU8) 23);
	}
	goto LA8;
	LA13: ;
	{
		NI32 LOC16;
		nimln(308, "nativesockets.nim");
		LOC16 = 0;
		LOC16 = oslasterror_119819();
		raiseoserror_119803(LOC16, ((NimStringDesc*) &TMP602));
	}
	LA8: ;
	nimln(309, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrlist), cstringarraytoseq_16022((*s).h_addr_list));
	nimln(310, "nativesockets.nim");
	(*Result).length = ((NI) ((*s).h_length));
	popFrame();
}

N_NIMCALL(void, gethostbyname_137004)(NimStringDesc* name, Hostent134612* Result) {
	struct hostent* s;
	nimfr("getHostByName", "nativesockets.nim")
	nimln(317, "nativesockets.nim");
	s = gethostbyname(name->data);
	nimln(318, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = oslasterror_119819();
		raiseoserror_119803(LOC5, ((NimStringDesc*) &TMP603));
	}
	LA3: ;
	nimln(319, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).h_name));
	nimln(320, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_16022((*s).h_aliases));
	nimln(324, "nativesockets.nim");
	{
		if (!((*s).h_addrtype == AF_INET)) goto LA8;
		nimln(325, "nativesockets.nim");
		(*Result).addrtype = ((NU8) 2);
	}
	goto LA6;
	LA8: ;
	{
		nimln(326, "nativesockets.nim");
		if (!((*s).h_addrtype == AF_INET6)) goto LA11;
		nimln(327, "nativesockets.nim");
		(*Result).addrtype = ((NU8) 23);
	}
	goto LA6;
	LA11: ;
	{
		NI32 LOC14;
		nimln(329, "nativesockets.nim");
		LOC14 = 0;
		LOC14 = oslasterror_119819();
		raiseoserror_119803(LOC14, ((NimStringDesc*) &TMP602));
	}
	LA6: ;
	nimln(330, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrlist), cstringarraytoseq_16022((*s).h_addr_list));
	nimln(331, "nativesockets.nim");
	(*Result).length = ((NI) ((*s).h_length));
	popFrame();
}

N_NIMCALL(NU8, getsockdomain_137402)(int socket) {
	NU8 result;
	struct sockaddr name;
	socklen_t namelen;
	nimfr("getSockDomain", "nativesockets.nim")
	result = 0;
	memset((void*)(&name), 0, sizeof(name));
	nimln(336, "nativesockets.nim");
	namelen = ((socklen_t) (((NI)sizeof(struct sockaddr))));
	nimln(337, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(338, "nativesockets.nim");
		nimln(337, "nativesockets.nim");
		LOC3 = 0;
		LOC3 = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
		if (!(LOC3 == ((NI32) -1))) goto LA4;
		nimln(339, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP603));
	}
	LA4: ;
	nimln(340, "nativesockets.nim");
	{
		if (!(name.sa_family == nativeafinet_134646)) goto LA9;
		nimln(341, "nativesockets.nim");
		result = ((NU8) 2);
	}
	goto LA7;
	LA9: ;
	{
		nimln(342, "nativesockets.nim");
		if (!(name.sa_family == nativeafinet6_134647)) goto LA12;
		nimln(343, "nativesockets.nim");
		result = ((NU8) 23);
	}
	goto LA7;
	LA12: ;
	{
		NI32 LOC15;
		nimln(345, "nativesockets.nim");
		LOC15 = 0;
		LOC15 = oslasterror_119819();
		raiseoserror_119803(LOC15, ((NimStringDesc*) &TMP604));
	}
	LA7: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getaddrstring_137413)(struct sockaddr* sockaddr) {
	NimStringDesc* result;
	nimfr("getAddrString", "nativesockets.nim")
	result = 0;
	nimln(350, "nativesockets.nim");
	{
		NCSTRING LOC5;
		if (!((*sockaddr).sa_family == nativeafinet_134646)) goto LA3;
		nimln(351, "nativesockets.nim");
		LOC5 = 0;
		LOC5 = inet_ntoa((*((struct sockaddr_in*) (sockaddr))).sin_addr);
		result = cstrToNimstr(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		struct in6_addr* addr6;
		NCSTRING LOC9;
		nimln(352, "nativesockets.nim");
		if (!((*sockaddr).sa_family == nativeafinet6_134647)) goto LA7;
		nimln(355, "nativesockets.nim");
		result = mnewString(((NI)chckRange(INET6_ADDRSTRLEN, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(356, "nativesockets.nim");
		addr6 = (&(*((struct sockaddr_in6*) (sockaddr))).sin6_addr);
		nimln(357, "nativesockets.nim");
		nimln(358, "nativesockets.nim");
		LOC9 = 0;
		LOC9 = (char *)inet_ntop(AF_INET6, ((void*) (addr6)), result->data, ((NI32)chckRange((result ? result->Sup.len : 0), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
		nimln(359, "nativesockets.nim");
		{
			int LOC12;
			nimln(349, "system.nim");
			nimln(359, "nativesockets.nim");
			LOC12 = 0;
			LOC12 = IN6_IS_ADDR_V4MAPPED(addr6);
			if (!!((LOC12 == ((NI32) 0)))) goto LA13;
			nimln(360, "nativesockets.nim");
			result = copyStr(result, ((NI) 7));
		}
		LA13: ;
	}
	goto LA1;
	LA7: ;
	{
		NI32 LOC16;
		nimln(362, "nativesockets.nim");
		LOC16 = 0;
		LOC16 = oslasterror_119819();
		raiseoserror_119803(LOC16, ((NimStringDesc*) &TMP605));
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NU16, getsockname_137606)(int socket) {
	NU16 result;
	struct sockaddr_in name;
	socklen_t namelen;
	NI16 LOC7;
	nimfr("getSockName", "nativesockets.nim")
	result = 0;
	memset((void*)(&name), 0, sizeof(name));
	nimln(371, "nativesockets.nim");
	name.sin_family = AF_INET;
	nimln(374, "nativesockets.nim");
	namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
	nimln(375, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(376, "nativesockets.nim");
		nimln(375, "nativesockets.nim");
		LOC3 = 0;
		LOC3 = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
		if (!(LOC3 == ((NI32) -1))) goto LA4;
		nimln(377, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP603));
	}
	LA4: ;
	nimln(378, "nativesockets.nim");
	LOC7 = 0;
	LOC7 = ntohs_136001(name.sin_port);
	result = ((NU16) (LOC7));
	popFrame();
	return result;
}

N_NIMCALL(void, getlocaladdr_137807)(int socket, NU8 domain, TY137811* Result) {
	nimfr("getLocalAddr", "nativesockets.nim")
	nimln(384, "nativesockets.nim");
	switch (domain) {
	case ((NU8) 2):
	{
		struct sockaddr_in name;
		socklen_t namelen;
		NCSTRING LOC8;
		NI16 LOC9;
		memset((void*)(&name), 0, sizeof(name));
		nimln(390, "nativesockets.nim");
		name.sin_family = AF_INET;
		nimln(391, "nativesockets.nim");
		namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
		nimln(392, "nativesockets.nim");
		{
			int LOC4;
			NI32 LOC7;
			nimln(393, "nativesockets.nim");
			nimln(392, "nativesockets.nim");
			LOC4 = 0;
			LOC4 = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
			if (!(LOC4 == ((NI32) -1))) goto LA5;
			nimln(394, "nativesockets.nim");
			LOC7 = 0;
			LOC7 = oslasterror_119819();
			raiseoserror_119803(LOC7, ((NimStringDesc*) &TMP603));
		}
		LA5: ;
		nimln(395, "nativesockets.nim");
		LOC8 = 0;
		LOC8 = inet_ntoa(name.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(LOC8));
		nimln(396, "nativesockets.nim");
		LOC9 = 0;
		LOC9 = ntohs_136001(name.sin_port);
		(*Result).Field1 = ((NU16) (LOC9));
	}
	break;
	case ((NU8) 23):
	{
		struct sockaddr_in6 name;
		socklen_t namelen;
		TY138206 buf;
		NI16 LOC23;
		memset((void*)(&name), 0, sizeof(name));
		nimln(402, "nativesockets.nim");
		name.sin6_family = AF_INET6;
		nimln(403, "nativesockets.nim");
		namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in6))));
		nimln(404, "nativesockets.nim");
		{
			int LOC13;
			NI32 LOC16;
			nimln(405, "nativesockets.nim");
			nimln(404, "nativesockets.nim");
			LOC13 = 0;
			LOC13 = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
			if (!(LOC13 == ((NI32) -1))) goto LA14;
			nimln(406, "nativesockets.nim");
			LOC16 = 0;
			LOC16 = oslasterror_119819();
			raiseoserror_119803(LOC16, ((NimStringDesc*) &TMP603));
		}
		LA14: ;
		memset((void*)buf, 0, sizeof(buf));
		nimln(409, "nativesockets.nim");
		{
			NCSTRING LOC19;
			NI32 LOC22;
			nimln(410, "nativesockets.nim");
			nimln(409, "nativesockets.nim");
			nimln(410, "nativesockets.nim");
			LOC19 = 0;
			LOC19 = (char *)inet_ntop(name.sin6_family, ((void*) ((&name))), ((NCSTRING) (buf)), ((NI32)chckRange(((NI)sizeof(TY138206)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!LOC19 == 0) goto LA20;
			nimln(411, "nativesockets.nim");
			LOC22 = 0;
			LOC22 = oslasterror_119819();
			raiseoserror_119803(LOC22, ((NimStringDesc*) &TMP603));
		}
		LA20: ;
		nimln(412, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(((NCSTRING) (buf))));
		LOC23 = 0;
		LOC23 = ntohs_136001(name.sin6_port);
		(*Result).Field1 = ((NU16) (LOC23));
	}
	break;
	default:
	{
		nimln(414, "nativesockets.nim");
		raiseoserror_119803(((NI32) -1), ((NimStringDesc*) &TMP606));
	}
	break;
	}
	popFrame();
}

N_NIMCALL(void, getpeeraddr_138217)(int socket, NU8 domain, TY137811* Result) {
	nimfr("getPeerAddr", "nativesockets.nim")
	nimln(420, "nativesockets.nim");
	switch (domain) {
	case ((NU8) 2):
	{
		struct sockaddr_in name;
		socklen_t namelen;
		NCSTRING LOC8;
		NI16 LOC9;
		memset((void*)(&name), 0, sizeof(name));
		nimln(426, "nativesockets.nim");
		name.sin_family = AF_INET;
		nimln(427, "nativesockets.nim");
		namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
		nimln(428, "nativesockets.nim");
		{
			int LOC4;
			NI32 LOC7;
			nimln(429, "nativesockets.nim");
			nimln(428, "nativesockets.nim");
			LOC4 = 0;
			LOC4 = getpeername(socket, ((struct sockaddr*) ((&name))), (&namelen));
			if (!(LOC4 == ((NI32) -1))) goto LA5;
			nimln(430, "nativesockets.nim");
			LOC7 = 0;
			LOC7 = oslasterror_119819();
			raiseoserror_119803(LOC7, ((NimStringDesc*) &TMP603));
		}
		LA5: ;
		nimln(431, "nativesockets.nim");
		LOC8 = 0;
		LOC8 = inet_ntoa(name.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(LOC8));
		nimln(432, "nativesockets.nim");
		LOC9 = 0;
		LOC9 = ntohs_136001(name.sin_port);
		(*Result).Field1 = ((NU16) (LOC9));
	}
	break;
	case ((NU8) 23):
	{
		struct sockaddr_in6 name;
		socklen_t namelen;
		TY138206 buf;
		NI16 LOC23;
		memset((void*)(&name), 0, sizeof(name));
		nimln(438, "nativesockets.nim");
		name.sin6_family = AF_INET6;
		nimln(439, "nativesockets.nim");
		namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in6))));
		nimln(440, "nativesockets.nim");
		{
			int LOC13;
			NI32 LOC16;
			nimln(441, "nativesockets.nim");
			nimln(440, "nativesockets.nim");
			LOC13 = 0;
			LOC13 = getpeername(socket, ((struct sockaddr*) ((&name))), (&namelen));
			if (!(LOC13 == ((NI32) -1))) goto LA14;
			nimln(442, "nativesockets.nim");
			LOC16 = 0;
			LOC16 = oslasterror_119819();
			raiseoserror_119803(LOC16, ((NimStringDesc*) &TMP603));
		}
		LA14: ;
		memset((void*)buf, 0, sizeof(buf));
		nimln(445, "nativesockets.nim");
		{
			NCSTRING LOC19;
			NI32 LOC22;
			nimln(446, "nativesockets.nim");
			nimln(445, "nativesockets.nim");
			nimln(446, "nativesockets.nim");
			LOC19 = 0;
			LOC19 = (char *)inet_ntop(name.sin6_family, ((void*) ((&name))), ((NCSTRING) (buf)), ((NI32)chckRange(((NI)sizeof(TY138206)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!LOC19 == 0) goto LA20;
			nimln(447, "nativesockets.nim");
			LOC22 = 0;
			LOC22 = oslasterror_119819();
			raiseoserror_119803(LOC22, ((NimStringDesc*) &TMP603));
		}
		LA20: ;
		nimln(448, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(((NCSTRING) (buf))));
		LOC23 = 0;
		LOC23 = ntohs_136001(name.sin6_port);
		(*Result).Field1 = ((NU16) (LOC23));
	}
	break;
	default:
	{
		nimln(450, "nativesockets.nim");
		raiseoserror_119803(((NI32) -1), ((NimStringDesc*) &TMP606));
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NI, getsockoptint_138617)(int socket, NI level, NI optname) {
	NI result;
	int res;
	socklen_t size;
	nimfr("getSockOptInt", "nativesockets.nim")
	result = 0;
	res = 0;
	nimln(456, "nativesockets.nim");
	size = ((socklen_t) 4);
	nimln(457, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(458, "nativesockets.nim");
		nimln(457, "nativesockets.nim");
		LOC3 = 0;
		LOC3 = getsockopt(socket, ((int)chckRange(level, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&res))), (&size));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(459, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP603));
	}
	LA4: ;
	nimln(460, "nativesockets.nim");
	result = ((NI) (res));
	popFrame();
	return result;
}

N_NIMCALL(void, setsockoptint_138629)(int socket, NI level, NI optname, NI optval) {
	int value;
	nimfr("setSockOptInt", "nativesockets.nim")
	nimln(465, "nativesockets.nim");
	value = ((int)chckRange(optval, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln(466, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(467, "nativesockets.nim");
		nimln(466, "nativesockets.nim");
		LOC3 = 0;
		LOC3 = setsockopt(socket, ((int)chckRange(level, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&value))), ((socklen_t) 4));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(468, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP603));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, setblocking_138637)(int s, NIM_BOOL blocking) {
	NI x;
	int LOC1;
	nimfr("setBlocking", "nativesockets.nim")
	nimln(479, "nativesockets.nim");
	LOC1 = 0;
	LOC1 = fcntl(s, F_GETFL, ((NI) 0));
	x = ((NI) (LOC1));
	nimln(480, "nativesockets.nim");
	{
		NI32 LOC6;
		if (!(x == ((NI) -1))) goto LA4;
		nimln(481, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_119819();
		raiseoserror_119803(LOC6, ((NimStringDesc*) &TMP603));
	}
	goto LA2;
	LA4: ;
	{
		NI mode;
		nimln(483, "nativesockets.nim");
		{
			if (!blocking) goto LA10;
			mode = (NI)(x & ((NI) ((NI32)((NU32) ~(O_NONBLOCK)))));
		}
		goto LA8;
		LA10: ;
		{
			mode = (NI)(x | ((NI) (O_NONBLOCK)));
		}
		LA8: ;
		nimln(484, "nativesockets.nim");
		{
			int LOC15;
			NI32 LOC18;
			LOC15 = 0;
			LOC15 = fcntl(s, F_SETFL, mode);
			if (!(LOC15 == ((NI32) -1))) goto LA16;
			nimln(485, "nativesockets.nim");
			LOC18 = 0;
			LOC18 = oslasterror_119819();
			raiseoserror_119803(LOC18, ((NimStringDesc*) &TMP603));
		}
		LA16: ;
	}
	LA2: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(struct timeval, timevalfrommilliseconds_138822)(NI timeout) {
	struct timeval result;
	nimfr("timeValFromMilliseconds", "nativesockets.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(488, "nativesockets.nim");
	{
		NI seconds;
		NI TMP607;
		NI TMP608;
		NI TMP609;
		NI TMP610;
		nimln(349, "system.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3;
		nimln(489, "nativesockets.nim");
		TMP607 = divInt(timeout, ((NI) 1000));
		seconds = (NI)(TMP607);
		nimln(490, "nativesockets.nim");
		result.tv_sec = ((NI) (((NI32)chckRange(seconds, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
		nimln(491, "nativesockets.nim");
		TMP608 = mulInt(seconds, ((NI) 1000));
		TMP609 = subInt(timeout, (NI)(TMP608));
		TMP610 = mulInt((NI)(TMP609), ((NI) 1000));
		result.tv_usec = ((NI) (((NI32)chckRange((NI)(TMP610), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, createfdset_138831)(fd_set* fd, TY138835* s, NI* m) {
	nimfr("createFdSet", "nativesockets.nim")
	nimln(494, "nativesockets.nim");
	FD_ZERO(fd);
	{
		int i_139002;
		NI i_139019;
		NI L_139021;
		i_139002 = 0;
		nimln(3361, "system.nim");
		i_139019 = ((NI) 0);
		nimln(3362, "system.nim");
		L_139021 = (s ? s->Sup.len : 0);
		{
			nimln(3363, "system.nim");
			while (1) {
				NI TMP611;
				if (!(i_139019 < L_139021)) goto LA3;
				nimln(3364, "system.nim");
				if ((NU)(i_139019) >= (NU)(s->Sup.len)) raiseIndexError();
				i_139002 = s->data[i_139019];
				nimln(496, "nativesockets.nim");
				(*m) = (((*m) >= ((NI) (i_139002))) ? (*m) : ((NI) (i_139002)));
				nimln(497, "nativesockets.nim");
				FD_SET(i_139002, fd);
				nimln(3365, "system.nim");
				TMP611 = addInt(i_139019, ((NI) 1));
				i_139019 = (NI)(TMP611);
				nimln(3366, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L_139021))) goto LA6;
					failedassertimpl_89116(((NimStringDesc*) &TMP612));
				}
				LA6: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, prunesocketset_139022)(TY138835** s, fd_set* fd) {
	NI i;
	NI L;
	nimfr("pruneSocketSet", "nativesockets.nim")
	nimln(500, "nativesockets.nim");
	i = ((NI) 0);
	nimln(501, "nativesockets.nim");
	L = ((*s) ? (*s)->Sup.len : 0);
	{
		nimln(502, "nativesockets.nim");
		while (1) {
			if (!(i < L)) goto LA2;
			nimln(503, "nativesockets.nim");
			{
				int LOC5;
				NI TMP613;
				NI TMP614;
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				LOC5 = 0;
				LOC5 = FD_ISSET((*s)->data[i], fd);
				if (!(LOC5 == ((NI32) 0))) goto LA6;
				nimln(504, "nativesockets.nim");
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				TMP613 = subInt(L, ((NI) 1));
				if ((NU)((NI)(TMP613)) >= (NU)((*s)->Sup.len)) raiseIndexError();
				(*s)->data[i] = (*s)->data[(NI)(TMP613)];
				nimln(505, "nativesockets.nim");
				TMP614 = subInt(L, ((NI) 1));
				L = (NI)(TMP614);
			}
			goto LA3;
			LA6: ;
			{
				NI TMP615;
				nimln(507, "nativesockets.nim");
				TMP615 = addInt(i, ((NI) 1));
				i = (NI)(TMP615);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(508, "nativesockets.nim");
	(*s) = (TY138835*) setLengthSeq(&((*s))->Sup, sizeof(int), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}

N_NIMCALL(NI, select_139077)(TY138835** readfds, NI timeout) {
	NI result;
	struct timeval tv;
	fd_set rd;
	NI m;
	nimfr("select", "nativesockets.nim")
	result = 0;
	nimln(518, "nativesockets.nim");
	tv = timevalfrommilliseconds_138822(timeout);
	memset((void*)(&rd), 0, sizeof(rd));
	nimln(521, "nativesockets.nim");
	m = ((NI) 0);
	nimln(522, "nativesockets.nim");
	createfdset_138831((&rd), (*readfds), (&m));
	nimln(524, "nativesockets.nim");
	{
		NI TMP616;
		int LOC5;
		nimln(349, "system.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3;
		nimln(525, "nativesockets.nim");
		TMP616 = addInt(m, ((NI) 1));
		LOC5 = 0;
		LOC5 = select(((int)chckRange((NI)(TMP616), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, (&tv));
		result = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI TMP617;
		int LOC7;
		nimln(527, "nativesockets.nim");
		TMP617 = addInt(m, ((NI) 1));
		LOC7 = 0;
		LOC7 = select(((int)chckRange((NI)(TMP617), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
		result = ((NI) (LOC7));
	}
	LA1: ;
	nimln(529, "nativesockets.nim");
	prunesocketset_139022(readfds, (&rd));
	popFrame();
	return result;
}

N_NIMCALL(NI, selectwrite_139128)(TY138835** writefds, NI timeout) {
	NI result;
	struct timeval tv;
	fd_set wr;
	NI m;
	nimfr("selectWrite", "nativesockets.nim")
	result = 0;
	nimln(540, "nativesockets.nim");
	tv = timevalfrommilliseconds_138822(timeout);
	memset((void*)(&wr), 0, sizeof(wr));
	nimln(543, "nativesockets.nim");
	m = ((NI) 0);
	nimln(544, "nativesockets.nim");
	createfdset_138831((&wr), (*writefds), (&m));
	nimln(546, "nativesockets.nim");
	{
		NI TMP618;
		int LOC5;
		nimln(349, "system.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3;
		nimln(547, "nativesockets.nim");
		TMP618 = addInt(m, ((NI) 1));
		LOC5 = 0;
		LOC5 = select(((int)chckRange((NI)(TMP618), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr), NIM_NIL, (&tv));
		result = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI TMP619;
		int LOC7;
		nimln(549, "nativesockets.nim");
		TMP619 = addInt(m, ((NI) 1));
		LOC7 = 0;
		LOC7 = select(((int)chckRange((NI)(TMP619), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr), NIM_NIL, NIM_NIL);
		result = ((NI) (LOC7));
	}
	LA1: ;
	nimln(551, "nativesockets.nim");
	prunesocketset_139022(writefds, (&wr));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void) {
	nimfr("nativesockets", "nativesockets.nim")
	nimln(104, "nativesockets.nim");
	osinvalidsocket_134645 = ((int) -1);
	nimln(105, "nativesockets.nim");
	nativeafinet_134646 = AF_INET;
	nimln(106, "nativesockets.nim");
	nativeafinet6_134647 = AF_INET6;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void) {
static TNimNode* TMP981[3];
NI TMP983;
static char* NIM_CONST TMP982[3] = {
"AF_UNIX", 
"AF_INET", 
"AF_INET6"};
static TNimNode* TMP984[4];
NI TMP986;
static char* NIM_CONST TMP985[4] = {
"SOCK_STREAM", 
"SOCK_DGRAM", 
"SOCK_RAW", 
"SOCK_SEQPACKET"};
static TNimNode* TMP987[6];
NI TMP989;
static char* NIM_CONST TMP988[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode TMP142[16];
NTI134604.size = sizeof(NU8);
NTI134604.kind = 14;
NTI134604.base = 0;
NTI134604.flags = 3;
for (TMP983 = 0; TMP983 < 3; TMP983++) {
TMP142[TMP983+0].kind = 1;
TMP142[TMP983+0].offset = TMP983;
TMP142[TMP983+0].name = TMP982[TMP983];
TMP981[TMP983] = &TMP142[TMP983+0];
}
TMP142[0].offset = 0;
TMP142[1].offset = 2;
TMP142[2].offset = 23;
TMP142[3].len = 3; TMP142[3].kind = 2; TMP142[3].sons = &TMP981[0];
NTI134604.node = &TMP142[3];
NTI134604.flags = 1<<2;
NTI134606.size = sizeof(NU8);
NTI134606.kind = 14;
NTI134606.base = 0;
NTI134606.flags = 3;
for (TMP986 = 0; TMP986 < 4; TMP986++) {
TMP142[TMP986+4].kind = 1;
TMP142[TMP986+4].offset = TMP986;
TMP142[TMP986+4].name = TMP985[TMP986];
TMP984[TMP986] = &TMP142[TMP986+4];
}
TMP142[4].offset = 1;
TMP142[5].offset = 2;
TMP142[6].offset = 3;
TMP142[7].offset = 5;
TMP142[8].len = 4; TMP142[8].kind = 2; TMP142[8].sons = &TMP984[0];
NTI134606.node = &TMP142[8];
NTI134606.flags = 1<<2;
NTI134608.size = sizeof(NU8);
NTI134608.kind = 14;
NTI134608.base = 0;
NTI134608.flags = 3;
for (TMP989 = 0; TMP989 < 6; TMP989++) {
TMP142[TMP989+9].kind = 1;
TMP142[TMP989+9].offset = TMP989;
TMP142[TMP989+9].name = TMP988[TMP989];
TMP987[TMP989] = &TMP142[TMP989+9];
}
TMP142[9].offset = 6;
TMP142[10].offset = 17;
TMP142[11].offset = 18;
TMP142[12].offset = 19;
TMP142[13].offset = 20;
TMP142[14].offset = 21;
TMP142[15].len = 6; TMP142[15].kind = 2; TMP142[15].sons = &TMP987[0];
NTI134608.node = &TMP142[15];
NTI134608.flags = 1<<2;
}

