/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/stdlib_intsets.o /home/cyril/Projects/provider/nimcache/stdlib_intsets.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Trunk166027 Trunk166027;
typedef struct Intset166031 Intset166031;
typedef struct Trunkseq166029 Trunkseq166029;
typedef struct Cell47905 Cell47905;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cellset47917 Cellset47917;
typedef struct Gcheap50218 Gcheap50218;
typedef struct Gcstack50216 Gcstack50216;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Memregion30088 Memregion30088;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30082 Llchunk30082;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Avlnode30086 Avlnode30086;
typedef struct Gcstat50214 Gcstat50214;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Intset166031  {
NI counter;
NI max;
Trunk166027* head;
Trunkseq166029* data;
};
typedef NI TY30019[8];
struct  Trunk166027  {
Trunk166027* next;
NI key;
TY30019 bits;
};
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
typedef Smallchunk30040* TY30103[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30088  {
NI minlargeobj;
NI maxlargeobj;
TY30103 freesmallchunks;
Llchunk30082* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30086* root;
Avlnode30086* deleted;
Avlnode30086* last;
Avlnode30086* freeavlnodes;
};
struct  Gcstat50214  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap50218  {
Gcstack50216* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellset47917 cycleroots;
Cellseq47921 tempstack;
NI recgclock;
Memregion30088 region;
Gcstat50214 stat;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Gcstack50216  {
Gcstack50216* prev;
Gcstack50216* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30082  {
NI size;
NI acc;
Llchunk30082* next;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
typedef Avlnode30086* TY30093[2];
struct  Avlnode30086  {
TY30093 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
struct Trunkseq166029 {
  TGenericSeq Sup;
  Trunk166027* data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, mustrehash_166044)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_89116)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, nexttry_166201)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(Trunk166027*, intsetget_166206)(Intset166031* t, NI key);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, intsetrawinsert_166225)(Intset166031* t, Trunkseq166029** data, Trunk166027* desc);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_54219)(Cell47905* c);
static N_INLINE(NIM_BOOL, canbecycleroot_51858)(Cell47905* c);
static N_INLINE(void, rtladdcycleroot_52620)(Cell47905* c);
N_NOINLINE(void, incl_48647)(Cellset47917* s, Cell47905* cell);
static N_INLINE(Cell47905*, usrtocell_51840)(void* usr);
static N_INLINE(void, decref_53801)(Cell47905* c);
static N_INLINE(void, rtladdzct_53401)(Cell47905* c);
N_NOINLINE(void, addzct_51817)(Cellseq47921* s, Cell47905* c);
N_NIMCALL(void, intsetenlarge_166602)(Intset166031* t);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP716)(void* p, NI op);
N_NIMCALL(void, TMP717)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(Trunk166027*, intsetput_166661)(Intset166031* t, NI key);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NIM_BOOL, contains_166811)(Intset166031* s, NI key);
N_NIMCALL(void, incl_166832)(Intset166031* s, NI key);
N_NIMCALL(void, excl_166841)(Intset166031* s, NI key);
N_NIMCALL(NIM_BOOL, containsorincl_166862)(Intset166031* s, NI key);
N_NIMCALL(void, initintset_166885)(Intset166031* Result);
static N_INLINE(NIM_BOOL, isnil_166898)(Intset166031* x);
N_NIMCALL(void, assign_166910)(Intset166031* dest, Intset166031* src);
N_NIMCALL(NimStringDesc*, HEX24_167072)(Intset166031* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NIM_BOOL, empty_167090)(Intset166031* s);
STRING_LITERAL(TMP703, "\012  counter < length ", 20);
STRING_LITERAL(TMP709, "\012  not (data[h] == desc) ", 25);
STRING_LITERAL(TMP710, "data[h] == nil ", 15);
STRING_LITERAL(TMP721, "t.data[h] == nil ", 17);
STRING_LITERAL(TMP722, "dest.data[h] == nil ", 20);
STRING_LITERAL(TMP723, "{", 1);
STRING_LITERAL(TMP724, ", ", 2);
STRING_LITERAL(TMP727, "}", 1);
extern TFrame* frameptr_19436;
extern Gcheap50218 gch_50259;
TNimType NTI166027; /* Trunk */
extern TNimType NTI104; /* int */
extern TNimType NTI30019; /* array[0..7, int] */
TNimType NTI166025; /* PTrunk */
TNimType NTI166029; /* TrunkSeq */

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

static N_INLINE(NIM_BOOL, mustrehash_166044)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP704;
	NI TMP705;
	NI TMP706;
	nimfr("mustRehash", "intsets.nim")
	result = 0;
	nimln(48, "intsets.nim");
	{
		if (!!((counter < length))) goto LA3;
		failedassertimpl_89116(((NimStringDesc*) &TMP703));
	}
	LA3: ;
	nimln(49, "intsets.nim");
	LOC5 = 0;
	TMP704 = mulInt(length, ((NI) 2));
	TMP705 = mulInt(counter, ((NI) 3));
	LOC5 = ((NI)(TMP704) < (NI)(TMP705));
	if (LOC5) goto LA6;
	TMP706 = subInt(length, counter);
	LOC5 = ((NI)(TMP706) < ((NI) 4));
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_166201)(NI h, NI maxhash) {
	NI result;
	NI TMP707;
	NI TMP708;
	nimfr("nextTry", "intsets.nim")
	result = 0;
	nimln(52, "intsets.nim");
	TMP707 = mulInt(((NI) 5), h);
	TMP708 = addInt((NI)(TMP707), ((NI) 1));
	result = (NI)((NI)(TMP708) & maxhash);
	popFrame();
	return result;
}

N_NIMCALL(Trunk166027*, intsetget_166206)(Intset166031* t, NI key) {
	Trunk166027* result;
	NI h;
	nimfr("intSetGet", "intsets.nim")
{	result = 0;
	nimln(55, "intsets.nim");
	h = (NI)(key & (*t).max);
	{
		nimln(56, "intsets.nim");
		while (1) {
			nimln(349, "system.nim");
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			if (!!(((*t).data->data[h] == NIM_NIL))) goto LA2;
			nimln(57, "intsets.nim");
			{
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				if (!((*(*t).data->data[h]).key == key)) goto LA5;
				nimln(58, "intsets.nim");
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				result = (*t).data->data[h];
				goto BeforeRet;
			}
			LA5: ;
			nimln(59, "intsets.nim");
			h = nexttry_166201(h, (*t).max);
		} LA2: ;
	}
	nimln(60, "intsets.nim");
	result = NIM_NIL;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_51858)(Cell47905* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1U<<((NU)(((NU8) 1))&7U)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_52620)(Cell47905* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_48647((&gch_50259.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_54219)(Cell47905* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_51858(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_52620(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(Cell47905*, usrtocell_51840)(void* usr) {
	Cell47905* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell47905*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47905))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_53401)(Cell47905* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_51817((&gch_50259.zct), c);
	popFrame();
}

static N_INLINE(void, decref_53801)(Cell47905* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_53401(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_51858(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_52620(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell47905* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_51840(src);
		incref_54219(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell47905* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_51840((*dest));
		decref_53801(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, intsetrawinsert_166225)(Intset166031* t, Trunkseq166029** data, Trunk166027* desc) {
	NI h;
	nimfr("intSetRawInsert", "intsets.nim")
	nimln(63, "intsets.nim");
	h = (NI)((*desc).key & (*t).max);
	{
		nimln(64, "intsets.nim");
		while (1) {
			nimln(349, "system.nim");
			if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
			if (!!(((*data)->data[h] == NIM_NIL))) goto LA2;
			nimln(65, "intsets.nim");
			{
				if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
				if (!!(!(((*data)->data[h] == desc)))) goto LA5;
				failedassertimpl_89116(((NimStringDesc*) &TMP709));
			}
			LA5: ;
			nimln(66, "intsets.nim");
			h = nexttry_166201(h, (*t).max);
		} LA2: ;
	}
	nimln(67, "intsets.nim");
	{
		if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
		if (!!(((*data)->data[h] == NIM_NIL))) goto LA9;
		failedassertimpl_89116(((NimStringDesc*) &TMP710));
	}
	LA9: ;
	nimln(68, "intsets.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	asgnRef((void**) (&(*data)->data[h]), desc);
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP716)(void* p, NI op) {
	Trunk166027* a;
	NI LOC1;
	a = (Trunk166027*)p;
	nimGCvisit((void*)(*a).next, op);
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < 8; LOC1++) {
	}
}
N_NIMCALL(void, TMP717)(void* p, NI op) {
	Trunkseq166029* a;
	NI LOC1;
	a = (Trunkseq166029*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

N_NIMCALL(void, intsetenlarge_166602)(Intset166031* t) {
	Trunkseq166029* n;
	NI oldmax;
	NI TMP711;
	NI TMP712;
	NI TMP713;
	NI TMP714;
	Trunkseq166029* LOC8;
	nimfr("intSetEnlarge", "intsets.nim")
	n = 0;
	nimln(72, "intsets.nim");
	oldmax = (*t).max;
	nimln(73, "intsets.nim");
	TMP711 = addInt((*t).max, ((NI) 1));
	TMP712 = mulInt((NI)(TMP711), ((NI) 2));
	TMP713 = subInt((NI)(TMP712), ((NI) 1));
	(*t).max = (NI)(TMP713);
	nimln(74, "intsets.nim");
	TMP714 = addInt((*t).max, ((NI) 1));
	n = (Trunkseq166029*) newSeq((&NTI166029), ((NI)chckRange((NI)(TMP714), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_166629;
		NI res_166657;
		i_166629 = 0;
		nimln(1874, "system.nim");
		res_166657 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP718;
				if (!(res_166657 <= oldmax)) goto LA3;
				nimln(1876, "system.nim");
				i_166629 = res_166657;
				nimln(76, "intsets.nim");
				{
					nimln(349, "system.nim");
					if ((NU)(i_166629) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if (!!(((*t).data->data[i_166629] == NIM_NIL))) goto LA6;
					nimln(76, "intsets.nim");
					if ((NU)(i_166629) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					intsetrawinsert_166225((&(*t)), (&n), (*t).data->data[i_166629]);
				}
				LA6: ;
				nimln(1890, "system.nim");
				TMP718 = addInt(res_166657, ((NI) 1));
				res_166657 = (NI)(TMP718);
			} LA3: ;
		}
	}
	nimln(77, "intsets.nim");
	LOC8 = 0;
	LOC8 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC8;
	popFrame();
}

N_NIMCALL(Trunk166027*, intsetput_166661)(Intset166031* t, NI key) {
	Trunk166027* result;
	NI h;
	NI TMP720;
	nimfr("intSetPut", "intsets.nim")
{	result = 0;
	nimln(80, "intsets.nim");
	h = (NI)(key & (*t).max);
	{
		nimln(81, "intsets.nim");
		while (1) {
			nimln(349, "system.nim");
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			if (!!(((*t).data->data[h] == NIM_NIL))) goto LA2;
			nimln(82, "intsets.nim");
			{
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				if (!((*(*t).data->data[h]).key == key)) goto LA5;
				nimln(83, "intsets.nim");
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				result = (*t).data->data[h];
				goto BeforeRet;
			}
			LA5: ;
			nimln(84, "intsets.nim");
			h = nexttry_166201(h, (*t).max);
		} LA2: ;
	}
	nimln(85, "intsets.nim");
	{
		NI TMP719;
		NIM_BOOL LOC9;
		TMP719 = addInt((*t).max, ((NI) 1));
		LOC9 = 0;
		LOC9 = mustrehash_166044((NI)(TMP719), (*t).counter);
		if (!LOC9) goto LA10;
		intsetenlarge_166602(t);
	}
	LA10: ;
	nimln(86, "intsets.nim");
	TMP720 = addInt((*t).counter, ((NI) 1));
	(*t).counter = (NI)(TMP720);
	nimln(87, "intsets.nim");
	h = (NI)(key & (*t).max);
	{
		nimln(88, "intsets.nim");
		while (1) {
			nimln(349, "system.nim");
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			if (!!(((*t).data->data[h] == NIM_NIL))) goto LA13;
			nimln(88, "intsets.nim");
			h = nexttry_166201(h, (*t).max);
		} LA13: ;
	}
	nimln(89, "intsets.nim");
	{
		if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		if (!!(((*t).data->data[h] == NIM_NIL))) goto LA16;
		failedassertimpl_89116(((NimStringDesc*) &TMP721));
	}
	LA16: ;
	nimln(90, "intsets.nim");
	result = (Trunk166027*) newObj((&NTI166025), sizeof(Trunk166027));
	nimln(91, "intsets.nim");
	asgnRef((void**) (&(*result).next), (*t).head);
	nimln(92, "intsets.nim");
	(*result).key = key;
	nimln(93, "intsets.nim");
	unsureAsgnRef((void**) (&(*t).head), result);
	nimln(94, "intsets.nim");
	if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
	asgnRef((void**) (&(*t).data->data[h]), result);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, contains_166811)(Intset166031* s, NI key) {
	NIM_BOOL result;
	Trunk166027* t;
	nimfr("contains", "intsets.nim")
	result = 0;
	nimln(98, "intsets.nim");
	t = intsetget_166206(s, (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	nimln(99, "intsets.nim");
	{
		NI u;
		nimln(349, "system.nim");
		if (!!((t == NIM_NIL))) goto LA3;
		nimln(100, "intsets.nim");
		u = (NI)(key & ((NI) 511));
		nimln(101, "intsets.nim");
		nimln(349, "system.nim");
		nimln(101, "intsets.nim");
		if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
		result = !(((NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63))))))) == ((NI) 0)));
	}
	goto LA1;
	LA3: ;
	{
		nimln(103, "intsets.nim");
		result = NIM_FALSE;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, incl_166832)(Intset166031* s, NI key) {
	Trunk166027* t;
	NI u;
	nimfr("incl", "intsets.nim")
	nimln(107, "intsets.nim");
	t = intsetput_166661(s, (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	nimln(108, "intsets.nim");
	u = (NI)(key & ((NI) 511));
	nimln(109, "intsets.nim");
	if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
	if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
	nimln(110, "intsets.nim");
	(*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63)))))));
	popFrame();
}

N_NIMCALL(void, excl_166841)(Intset166031* s, NI key) {
	Trunk166027* t;
	nimfr("excl", "intsets.nim")
	nimln(114, "intsets.nim");
	t = intsetget_166206((&(*s)), (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	nimln(115, "intsets.nim");
	{
		NI u;
		nimln(349, "system.nim");
		if (!!((t == NIM_NIL))) goto LA3;
		nimln(116, "intsets.nim");
		u = (NI)(key & ((NI) 511));
		nimln(117, "intsets.nim");
		if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
		if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
		nimln(118, "intsets.nim");
		(*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64) ~((NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63)))))))));
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, containsorincl_166862)(Intset166031* s, NI key) {
	NIM_BOOL result;
	Trunk166027* t;
	nimfr("containsOrIncl", "intsets.nim")
	result = 0;
	nimln(123, "intsets.nim");
	t = intsetget_166206((&(*s)), (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	nimln(124, "intsets.nim");
	{
		NI u;
		nimln(349, "system.nim");
		if (!!((t == NIM_NIL))) goto LA3;
		nimln(125, "intsets.nim");
		u = (NI)(key & ((NI) 511));
		nimln(126, "intsets.nim");
		nimln(349, "system.nim");
		nimln(126, "intsets.nim");
		if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
		result = !(((NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63))))))) == ((NI) 0)));
		nimln(127, "intsets.nim");
		{
			if (!!(result)) goto LA7;
			nimln(128, "intsets.nim");
			if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
			if ((NU)((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6)))) > (NU)(7)) raiseIndexError();
			nimln(129, "intsets.nim");
			(*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63)))))));
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		nimln(131, "intsets.nim");
		incl_166832(s, key);
		nimln(132, "intsets.nim");
		result = NIM_FALSE;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, initintset_166885)(Intset166031* Result) {
	nimfr("initIntSet", "intsets.nim")
	nimln(136, "intsets.nim");
	unsureAsgnRef((void**) (&(*Result).data), (Trunkseq166029*) newSeq((&NTI166029), ((NI) 8)));
	nimln(137, "intsets.nim");
	(*Result).max = ((NI) 7);
	nimln(138, "intsets.nim");
	(*Result).counter = ((NI) 0);
	nimln(139, "intsets.nim");
	unsureAsgnRef((void**) (&(*Result).head), NIM_NIL);
	popFrame();
}

static N_INLINE(NIM_BOOL, isnil_166898)(Intset166031* x) {
	NIM_BOOL result;
	nimfr("isNil", "intsets.nim")
	result = 0;
	nimln(141, "intsets.nim");
	result = (*x).head == 0;
	popFrame();
	return result;
}

N_NIMCALL(void, assign_166910)(Intset166031* dest, Intset166031* src) {
	Trunk166027* it;
	nimfr("assign", "intsets.nim")
	nimln(146, "intsets.nim");
	(*dest).counter = (*src).counter;
	nimln(147, "intsets.nim");
	(*dest).max = (*src).max;
	nimln(148, "intsets.nim");
	unsureAsgnRef((void**) (&(*dest).data), (Trunkseq166029*) newSeq((&NTI166029), ((NI)chckRange(((*src).data ? (*src).data->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807))))));
	nimln(150, "intsets.nim");
	it = (*src).head;
	{
		nimln(151, "intsets.nim");
		while (1) {
			NI h;
			Trunk166027* n;
			nimln(349, "system.nim");
			if (!!((it == NIM_NIL))) goto LA2;
			nimln(153, "intsets.nim");
			h = (NI)((*it).key & (*dest).max);
			{
				nimln(154, "intsets.nim");
				while (1) {
					nimln(349, "system.nim");
					if ((NU)(h) >= (NU)((*dest).data->Sup.len)) raiseIndexError();
					if (!!(((*dest).data->data[h] == NIM_NIL))) goto LA4;
					nimln(154, "intsets.nim");
					h = nexttry_166201(h, (*dest).max);
				} LA4: ;
			}
			nimln(155, "intsets.nim");
			{
				if ((NU)(h) >= (NU)((*dest).data->Sup.len)) raiseIndexError();
				if (!!(((*dest).data->data[h] == NIM_NIL))) goto LA7;
				failedassertimpl_89116(((NimStringDesc*) &TMP722));
			}
			LA7: ;
			n = 0;
			nimln(158, "intsets.nim");
			n = (Trunk166027*) newObj((&NTI166025), sizeof(Trunk166027));
			nimln(159, "intsets.nim");
			asgnRef((void**) (&(*n).next), (*dest).head);
			nimln(160, "intsets.nim");
			(*n).key = (*it).key;
			nimln(161, "intsets.nim");
			memcpy((void*)(*n).bits, (NIM_CONST void*)(*it).bits, sizeof(TY30019));
			nimln(162, "intsets.nim");
			unsureAsgnRef((void**) (&(*dest).head), n);
			nimln(163, "intsets.nim");
			if ((NU)(h) >= (NU)((*dest).data->Sup.len)) raiseIndexError();
			asgnRef((void**) (&(*dest).data->data[h]), n);
			nimln(165, "intsets.nim");
			it = (*it).next;
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_167072)(Intset166031* s) {
	NimStringDesc* result;
	nimfr("$", "intsets.nim")
	result = 0;
	nimln(186, "intsets.nim");
	result = copyString(((NimStringDesc*) &TMP723));
	{
		NI key_167077;
		Trunk166027* r_167083;
		key_167077 = 0;
		nimln(169, "intsets.nim");
		r_167083 = (*s).head;
		{
			nimln(170, "intsets.nim");
			while (1) {
				NI i_167085;
				nimln(349, "system.nim");
				if (!!((r_167083 == NIM_NIL))) goto LA3;
				nimln(171, "intsets.nim");
				i_167085 = ((NI) 0);
				{
					nimln(172, "intsets.nim");
					while (1) {
						NI w_167087;
						NI j_167089;
						NI TMP726;
						if (!(i_167085 <= ((NI) 7))) goto LA5;
						nimln(173, "intsets.nim");
						if ((NU)(i_167085) > (NU)(7)) raiseIndexError();
						w_167087 = (*r_167083).bits[(i_167085)- 0];
						nimln(176, "intsets.nim");
						j_167089 = ((NI) 0);
						{
							nimln(177, "intsets.nim");
							while (1) {
								NI TMP725;
								nimln(349, "system.nim");
								if (!!((w_167087 == ((NI) 0)))) goto LA7;
								nimln(178, "intsets.nim");
								{
									NimStringDesc* LOC16;
									nimln(349, "system.nim");
									nimln(178, "intsets.nim");
									if (!!((((NI) ((NI)(w_167087 & ((NI) 1)))) == ((NI) 0)))) goto LA10;
									nimln(179, "intsets.nim");
									key_167077 = (NI)((NI)((NU64)((*r_167083).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_167085) << (NU64)(((NI) 6)))) + (NU64)(j_167089)));
									nimln(188, "intsets.nim");
									{
										nimln(357, "system.nim");
										nimln(188, "intsets.nim");
										if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA14;
										result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TMP724));
									}
									LA14: ;
									nimln(189, "intsets.nim");
									LOC16 = 0;
									LOC16 = nimIntToStr(key_167077);
									result = resizeString(result, LOC16->Sup.len + 0);
appendString(result, LOC16);
								}
								LA10: ;
								nimln(180, "intsets.nim");
								TMP725 = addInt(j_167089, ((NI) 1));
								j_167089 = (NI)(TMP725);
								nimln(181, "intsets.nim");
								w_167087 = (NI)((NU64)(w_167087) >> (NU64)(((NI) 1)));
							} LA7: ;
						}
						nimln(182, "intsets.nim");
						TMP726 = addInt(i_167085, ((NI) 1));
						i_167085 = (NI)(TMP726);
					} LA5: ;
				}
				nimln(183, "intsets.nim");
				r_167083 = (*r_167083).next;
			} LA3: ;
		}
	}
	nimln(190, "intsets.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TMP727));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, empty_167090)(Intset166031* s) {
	NIM_BOOL result;
	nimfr("empty", "intsets.nim")
	result = 0;
	nimln(200, "intsets.nim");
	result = ((*s).counter == ((NI) 0));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsInit000)(void) {
	nimfr("intsets", "intsets.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_intsetsDatInit000)(void) {
static TNimNode* TMP715[3];
static TNimNode TMP701[4];
NTI166027.size = sizeof(Trunk166027);
NTI166027.kind = 18;
NTI166027.base = 0;
TMP715[0] = &TMP701[1];
TMP701[1].kind = 1;
TMP701[1].offset = offsetof(Trunk166027, next);
TMP701[1].typ = (&NTI166025);
TMP701[1].name = "next";
TMP715[1] = &TMP701[2];
TMP701[2].kind = 1;
TMP701[2].offset = offsetof(Trunk166027, key);
TMP701[2].typ = (&NTI104);
TMP701[2].name = "key";
TMP715[2] = &TMP701[3];
TMP701[3].kind = 1;
TMP701[3].offset = offsetof(Trunk166027, bits);
TMP701[3].typ = (&NTI30019);
TMP701[3].name = "bits";
TMP701[0].len = 3; TMP701[0].kind = 2; TMP701[0].sons = &TMP715[0];
NTI166027.node = &TMP701[0];
NTI166025.size = sizeof(Trunk166027*);
NTI166025.kind = 22;
NTI166025.base = (&NTI166027);
NTI166025.marker = TMP716;
NTI166029.size = sizeof(Trunkseq166029*);
NTI166029.kind = 24;
NTI166029.base = (&NTI166025);
NTI166029.flags = 2;
NTI166029.marker = TMP717;
}

