/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/stdlib_cpuload.o /home/cyril/Projects/provider/nimcache/stdlib_cpuload.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
typedef struct Threadpoolstate185204 Threadpoolstate185204;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Threadpoolstate185204  {
NI calls;
};
N_NIMCALL(NU8, advice_185209)(Threadpoolstate185204* s);
N_NIMCALL(FILE*, open_15417)(NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(NI, ncpicountProcessors)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_28801)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP582, "/proc/loadavg", 13);
extern NIM_THREADVAR TFrame* frameptr_26036;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_26036 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_26036).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_26036;
	frameptr_26036 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_28801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_26036 = (*frameptr_26036).prev;
}

N_NIMCALL(NU8, advice_185209)(Threadpoolstate185204* s) {
	NU8 result;
	FILE* f;
	NF b;
	NI busy;
	NI total;
	NI cpus;
	NI TMP586;
	nimfr("advice", "cpuload.nim")
	result = 0;
	nimln(63, "cpuload.nim");
	f = open_15417(((NimStringDesc*) &TMP582), ((NU8) 0), ((NI) -1));
	b = 0;
	busy = 0;
	total = 0;
	nimln(66, "cpuload.nim");
	fscanf(f, "%lf %lf %lf %ld/%ld", (&b), (&b), (&b), (&busy), (&total));
	nimln(68, "cpuload.nim");
	fclose(f);
	nimln(69, "cpuload.nim");
	cpus = ncpicountProcessors();
	nimln(70, "cpuload.nim");
	{
		NI TMP583;
		TMP583 = subInt(busy, ((NI) 1));
		if (!((NI)(TMP583) < cpus)) goto LA3;
		nimln(71, "cpuload.nim");
		result = ((NU8) 1);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP584;
		NI TMP585;
		nimln(353, "system.nim");
		nimln(72, "cpuload.nim");
		TMP584 = mulInt(cpus, ((NI) 2));
		TMP585 = subInt(busy, ((NI) 1));
		if (!((NI)(TMP584) <= (NI)(TMP585))) goto LA6;
		nimln(73, "cpuload.nim");
		result = ((NU8) 2);
	}
	goto LA1;
	LA6: ;
	{
		nimln(75, "cpuload.nim");
		result = ((NU8) 0);
	}
	LA1: ;
	nimln(79, "cpuload.nim");
	TMP586 = addInt((*s).calls, ((NI) 1));
	(*s).calls = (NI)(TMP586);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadInit000)(void) {
	nimfr("cpuload", "cpuload.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadDatInit000)(void) {
}

