/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cyril/Projects/provider/nimcache/testmacro.o /home/cyril/Projects/provider/nimcache/testmacro.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct Msgsize139004 Msgsize139004;
typedef struct Slice88482 Slice88482;
typedef struct TY139055 TY139055;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  Slice88482  {
NI a;
NI b;
};
struct  Msgsize139004  {
NU8 fixtype;
NU8 constant;
Slice88482 area;
NI size;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY139055 {
  TGenericSeq Sup;
  Msgsize139004 data[SEQ_DECL_SIZE];
};
N_NIMCALL(Msgsize139004, initsize_139013)(NI size, NU8 constant);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_22201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(Msgsize139004, initfix_139020)(NI size, Slice88482 area);
N_NIMCALL(TY139055*, newseq_139050)(NI len);
N_NIMCALL(TY139055*, createformat_139029)(NU8 baseconst, NI sizelow, NI steps, NI stepsize);
static N_INLINE(Slice88482, HEX2EHEX2E_96017)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(TY139055*, HEX26_139177)(TY139055* x, TY139055* y);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, testmacroInit000)(void);
NIM_EXTERNC N_NOINLINE(void, testmacroDatInit000)(void);
NIM_CONST struct {
  TGenericSeq Sup;
  Msgsize139004 data[2];
} CNSTSEQ621 = {{2, 2}, {{((NU8) 0),
((NU8) 0),
{((NI) 0),
((NI) 127)}
,
((NI) 7)}
,
{((NU8) 0),
((NU8) 0),
{((NI) 224),
((NI) 255)}
,
((NI) 5)}
}};
NIM_CONST TY139055* fixints_139160 = ((TY139055*)&CNSTSEQ621);
NIM_CONST struct {
  TGenericSeq Sup;
  Msgsize139004 data[6];
} CNSTSEQ622 = {{6, 6}, {{((NU8) 0),
((NU8) 0),
{((NI) 0),
((NI) 127)}
,
((NI) 7)}
,
{((NU8) 0),
((NU8) 0),
{((NI) 224),
((NI) 255)}
,
((NI) 5)}
,
{((NU8) 1),
((NU8) 204),
{((NI) 0),
((NI) 0)}
,
((NI) 1)}
,
{((NU8) 1),
((NU8) 205),
{((NI) 0),
((NI) 0)}
,
((NI) 2)}
,
{((NU8) 1),
((NU8) 206),
{((NI) 0),
((NI) 0)}
,
((NI) 3)}
,
{((NU8) 1),
((NU8) 207),
{((NI) 0),
((NI) 0)}
,
((NI) 4)}
}};
NIM_CONST TY139055* uintformats_139174 = ((TY139055*)&CNSTSEQ622);
NIM_CONST struct {
  TGenericSeq Sup;
  Msgsize139004 data[6];
} CNSTSEQ623 = {{6, 6}, {{((NU8) 0),
((NU8) 0),
{((NI) 0),
((NI) 127)}
,
((NI) 7)}
,
{((NU8) 0),
((NU8) 0),
{((NI) 224),
((NI) 255)}
,
((NI) 5)}
,
{((NU8) 1),
((NU8) 208),
{((NI) 0),
((NI) 0)}
,
((NI) 1)}
,
{((NU8) 1),
((NU8) 209),
{((NI) 0),
((NI) 0)}
,
((NI) 2)}
,
{((NU8) 1),
((NU8) 210),
{((NI) 0),
((NI) 0)}
,
((NI) 3)}
,
{((NU8) 1),
((NU8) 211),
{((NI) 0),
((NI) 0)}
,
((NI) 4)}
}};
NIM_CONST TY139055* intformats_139274 = ((TY139055*)&CNSTSEQ623);
NIM_CONST struct {
  TGenericSeq Sup;
  Msgsize139004 data[2];
} CNSTSEQ624 = {{2, 2}, {{((NU8) 1),
((NU8) 202),
{((NI) 0),
((NI) 0)}
,
((NI) 2)}
,
{((NU8) 1),
((NU8) 203),
{((NI) 0),
((NI) 0)}
,
((NI) 4)}
}};
NIM_CONST TY139055* floatformats_139288 = ((TY139055*)&CNSTSEQ624);
NIM_CONST struct {
  TGenericSeq Sup;
  Msgsize139004 data[3];
} CNSTSEQ625 = {{3, 3}, {{((NU8) 1),
((NU8) 196),
{((NI) 0),
((NI) 0)}
,
((NI) 1)}
,
{((NU8) 1),
((NU8) 197),
{((NI) 0),
((NI) 0)}
,
((NI) 2)}
,
{((NU8) 1),
((NU8) 198),
{((NI) 0),
((NI) 0)}
,
((NI) 3)}
}};
NIM_CONST TY139055* binformats_139329 = ((TY139055*)&CNSTSEQ625);
NIM_CONST struct {
  TGenericSeq Sup;
  Msgsize139004 data[3];
} CNSTSEQ626 = {{3, 3}, {{((NU8) 1),
((NU8) 199),
{((NI) 0),
((NI) 0)}
,
((NI) 1)}
,
{((NU8) 1),
((NU8) 200),
{((NI) 0),
((NI) 0)}
,
((NI) 2)}
,
{((NU8) 1),
((NU8) 201),
{((NI) 0),
((NI) 0)}
,
((NI) 3)}
}};
NIM_CONST TY139055* extformats_139331 = ((TY139055*)&CNSTSEQ626);
extern TFrame* frameptr_19436;
TNimType NTI139004; /* MsgSize */
TNimType NTI139002; /* Sized */
extern TNimType NTI3602; /* byte */
extern TNimType NTI88482; /* Slice */
extern TNimType NTI104; /* int */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_19436 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19436).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_19436;
	frameptr_19436 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19436 = (*frameptr_19436).prev;
}

N_NIMCALL(Msgsize139004, initsize_139013)(NI size, NU8 constant) {
	Msgsize139004 result;
	Msgsize139004 LOC1;
	nimfr("initSize", "testmacro.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(11, "testmacro.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.fixtype = ((NU8) 1);
	LOC1.constant = constant;
	LOC1.size = size;
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(Msgsize139004, initfix_139020)(NI size, Slice88482 area) {
	Msgsize139004 result;
	Msgsize139004 LOC1;
	nimfr("initFix", "testmacro.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(12, "testmacro.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.fixtype = ((NU8) 0);
	LOC1.area = area;
	LOC1.size = size;
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(Slice88482, HEX2EHEX2E_96017)(NI a, NI b) {
	Slice88482 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(270, "system.nim");
	result.a = a;
	nimln(271, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(TY139055*, createformat_139029)(NU8 baseconst, NI sizelow, NI steps, NI stepsize) {
	TY139055* result;
	nimfr("createFormat", "testmacro.nim")
	result = 0;
	nimln(14, "testmacro.nim");
	result = newseq_139050(((NI) 0));
	{
		NI i_139100;
		Slice88482 HEX3Atmp_139121;
		i_139100 = 0;
		memset((void*)(&HEX3Atmp_139121), 0, sizeof(HEX3Atmp_139121));
		nimln(3548, "system.nim");
		nimln(3550, "system.nim");
		HEX3Atmp_139121 = HEX2EHEX2E_96017(((NI) 0), subInt(steps, 1));
		{
			NI x_139125;
			NI HEX3Atmp_139127;
			NI HEX3Atmp_139129;
			NI res_139131;
			x_139125 = 0;
			HEX3Atmp_139127 = 0;
			HEX3Atmp_139129 = 0;
			nimln(2026, "system.nim");
			HEX3Atmp_139127 = HEX3Atmp_139121.a;
			HEX3Atmp_139129 = HEX3Atmp_139121.b;
			nimln(1874, "system.nim");
			res_139131 = HEX3Atmp_139127;
			{
				nimln(1875, "system.nim");
				while (1) {
					NI TMP611;
					NI TMP612;
					Msgsize139004 LOC5;
					NI TMP613;
					if (!(res_139131 <= HEX3Atmp_139129)) goto LA4;
					nimln(1876, "system.nim");
					x_139125 = res_139131;
					nimln(2026, "system.nim");
					i_139100 = x_139125;
					nimln(16, "testmacro.nim");
					TMP611 = mulInt(i_139100, stepsize);
					TMP612 = addInt(sizelow, (NI)(TMP611));
					LOC5 = initsize_139013((NI)(TMP612), (NU8)((NU8)(baseconst) + (NU8)(((NU8) (i_139100)))));
					result = (TY139055*) incrSeqV2(&(result)->Sup, sizeof(Msgsize139004));
					result->data[result->Sup.len] = LOC5;
					++result->Sup.len;
					nimln(1895, "system.nim");
					TMP613 = addInt(res_139131, ((NI) 1));
					res_139131 = (NI)(TMP613);
				} LA4: ;
			}
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	testmacroDatInit000();
	stdlib_macrosInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	testmacroInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, testmacroInit000)(void) {
	nimfr("testmacro", "testmacro.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, testmacroDatInit000)(void) {
static TNimNode* TMP605[4];
static TNimNode* TMP606[2];
NI TMP608;
static char* NIM_CONST TMP607[2] = {
"fixed", 
"size"};
static TNimNode TMP138[8];
NTI139004.size = sizeof(Msgsize139004);
NTI139004.kind = 18;
NTI139004.base = 0;
NTI139004.flags = 3;
TMP605[0] = &TMP138[1];
NTI139002.size = sizeof(NU8);
NTI139002.kind = 14;
NTI139002.base = 0;
NTI139002.flags = 3;
for (TMP608 = 0; TMP608 < 2; TMP608++) {
TMP138[TMP608+2].kind = 1;
TMP138[TMP608+2].offset = TMP608;
TMP138[TMP608+2].name = TMP607[TMP608];
TMP606[TMP608] = &TMP138[TMP608+2];
}
TMP138[4].len = 2; TMP138[4].kind = 2; TMP138[4].sons = &TMP606[0];
NTI139002.node = &TMP138[4];
TMP138[1].kind = 1;
TMP138[1].offset = offsetof(Msgsize139004, fixtype);
TMP138[1].typ = (&NTI139002);
TMP138[1].name = "fixType";
TMP605[1] = &TMP138[5];
TMP138[5].kind = 1;
TMP138[5].offset = offsetof(Msgsize139004, constant);
TMP138[5].typ = (&NTI3602);
TMP138[5].name = "constant";
TMP605[2] = &TMP138[6];
TMP138[6].kind = 1;
TMP138[6].offset = offsetof(Msgsize139004, area);
TMP138[6].typ = (&NTI88482);
TMP138[6].name = "area";
TMP605[3] = &TMP138[7];
TMP138[7].kind = 1;
TMP138[7].offset = offsetof(Msgsize139004, size);
TMP138[7].typ = (&NTI104);
TMP138[7].name = "size";
TMP138[0].len = 4; TMP138[0].kind = 2; TMP138[0].sons = &TMP605[0];
NTI139004.node = &TMP138[0];
}

